### ISSUE TITLE
Command line support to find template packs

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/templating#1084]
Now that we have support for `--install` and `--uninstall` we should add support to find new template packs from the command line.

Initial thoughts:

 - Create `dotnet new --search`
 - Update `dotnet new --install` to support searching for a template

Let's discuss more and come up with a proposal when we have time.

**Comment by mlorbetske** [comment]
Let's get the set of templates/packs discovered by your NuGet searcher set up as a feed somewhere that we can check at runtime. Let's add a link to it here and in the wiki as well so that the service is discoverable.

The service should list template packs, their current versions and the templates (maybe options as well?) contained in them so that we can use the information for installation suggestions in error cases (ex1. A short name for a template that's not installed is given for the thing to be created - we should offer to install it; ex2. A value for a parameter is specified that isn't available in the installed version of the template but a newer version or different template pack has a template that meets the criteria - we should offer to install in that case too)

**Comment by mlorbetske** [comment]
From @sayedihashimi 

> http://dotnetnew-api.azurewebsites.net/api/templates
http://dotnetnew-api.azurewebsites.net/api/templates/Microsoft.AspNetCore.SpaTemplates.Angular.CSharp
Too see what’s inside of a NuGet package, route should be renamed
http://dotnetnew-api.azurewebsites.net/api/search/angular
Put your search term as the last part of the URL

cc @seancpeters @phenning

**Comment by mlorbetske** [comment]
We should also be able to use this service to determine whether there's an updated version of the template (the exact one that's been resolved to) that's compatible with the version of the engine being used

**Comment by xrcdev** [comment]
uninstall higher version

**Comment by luizmotta01** [comment]
anyone knows a way to go around and check which version is installed? I've looked into the "dotnet/templates" folder, but not founded any custom  template with the ".nupkg" extension

**Comment by phenning** [comment]
@luizmotta01, are you trying to find which version of a custom template is installed?
Running `dotnet new -u` will enumerate the list of template which are installed, along with version information and uninstall commands needed to unsintall if desired.

**Comment by luizmotta01** [comment]
@phenning yes, I actually have a team of developers using a custom template and I have to ensure that when the custom template gets updated everyone in the team can verify the installed version. But I've tried your command suggestion and it solves it. thank you very much!

**Comment by donJoseLuis** [comment]
We moved this item to a project corresponding to the buckets we want to schedule in a road map.  Following that, items in each bucket will undergo a prioritization exercise so we can then have a proper delivery plan.

**Comment by bekir-ozturk** [comment]
`dotnet new --search` was implemented in 5.0.300. Closing this issue.
