### ISSUE TITLE
Suggestion: Use SQL Server security for connection strings on Linux

### ISSUE THREAD

**Issue by livarcocc** [dotnet/templating#1097]
_From @badersur on July 13, 2017 21:3_

## Steps to reproduce

1. `dotnet new mvc -au Individual -uld true`

2. `dotnet restore`

3. `ASPNETCORE_ENVIRONMENT=Development dotnet run`

4. visit http://localhost:5000/Account/Register, enter data & press register

## Expected  behavior
The site should register the user & work without any issue

## Actual behavior
An error occurred with these messages:

```
An unhandled exception occurred while processing the request.

NotSupportedException: The keyword 'integrated security' is not supported on this platform.
System.Data.SqlClient.SqlConnectionString..ctor(string connectionString)
....

```

Solved by changing the connection string to use SQL Server Security:

```
"DefaultConnection": "Server=localhost;Database=aspnet-MVCAuthSQL;Trusted_Connection=False;MultipleActiveResultSets=true;User Id=SA;Password=my-secret-password;"
```

I suggest changing the templates to use SQL Server Security on Linux distributions, or adding another connection string (and suggesting to use it in `Startup.cs`) or at least link to https://msdn.microsoft.com/en-us/library/jj653752(v=vs.110).aspx#sqlserver in `Startup.cs`...

I spent many hours to find the solution (from 4 PM - 11 PM with some breaks!) and I think templates should work by default. Also, the default string seems to applicable for Windows so I believe it should be changed on other platforms.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.1.0-preview1-005051)

Product Information:
 Version:            1.1.0-preview1-005051
 Commit SHA-1 hash:  5e88564e56

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  17.04
 OS Platform: Linux
 RID:         ubuntu.16.10-x64
 Base Path:   /usr/share/dotnet/sdk/1.1.0-preview1-005051
```

_Copied from original issue: dotnet/cli#7156_

**Comment by mlorbetske** [comment]
The --use-localdb option was intended for the Windows-only (as far as I know, I'll confess that I haven't looked very much at the SQL Server on Linux support) LocalDB offering (usually installed along with Visual Studio) where the database is created by the request to use it rather than precreated by the user like in full SQL. For other platforms, the general practice has been to not specify that switch, causing the default provider (SQLite) to be used instead.

I could see the possibility for adding another storage option for full SQL where the database name, user and password would be taken as additional arguments and/or adding documentation on how/where to configure connection strings to use full SQL.

cc @danroth27

**Comment by badersur** [comment]
Hello @mlorbetske and thanks for your reply :)

After installing dotnet 1.1.0-preview1-005077, I feel it would be nice to introduce other arguments instead of `-uld` to choose one of the EF Core date providers.

If I run `dotnet new mvc -h`, I would like to see something like these instead of `-uld`:

```
  -dp|--data-provider   Entity Framework Core data provider (only applies to Individual auth type)

                        InMemory

                        SQLite

                        LocalDB                                         

                        MSSQL

                        MSSQLCompact

                        MySQL

                        Default: SQLite


  --server              The server to connect to (use with MSSQL or MySQL data providers)

                        string - Optional

                        Default: localhost


  --database            The name of the database (use with MSSQL or MySQL data providers)

                        string - Optional

                        Default: aspnet-Folder name-random text


  --user-id             User id to log in to the date provider (use with MSSQL or MySQL data providers)

                        string - Optional

                        Default: sa (for MSSQL) or root (for MySQL)


  --password            Password for the user id

                        string - Optional

                        Default: Empty string

```

This will reduce some time spent on looking for connection strings, nuget packages and Classes/methods... but it may give an impression that these are the only supported data providers!

I was hoping to have something similar to [Laravel's database configuration](https://github.com/laravel/laravel/blob/master/config/database.php) but I forgot that ASP.NET Core is an opt-in framework :/

**Comment by mlorbetske** [comment]
I think this would be related to #698 as well then

**Comment by badersur** [comment]
Yeah, it looks similar to `-dp` switch!

**Comment by mlorbetske** [comment]
@badersur do you think it'd be best to add additional information to #698 or is there enough of a distinction that we should we track this separately?

**Comment by badersur** [comment]
@mlorbetske I think it's fine either way but would be easier to add the other options to #698 and track one issue!

The issue seems to be almost addressed in https://github.com/dotnet/templating/pull/788 except for testing & validating migrations. I'm mostly interested in entity framework's data providers and consider other options as optional and nice to have.

In that PR, SQL provider uses localdb's connection string but I prefer to split them to have LocalDB, MSSQL (for the full SQL) and maybe SQLCompact as well.

**Comment by mlorbetske** [comment]
This issue was moved to aspnet/templating#26
