### ISSUE TITLE
Add commands to set user preferences

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/templating#115]
Something like:

Setting a preference for this particular host (host identifier/version specific)
```
dotnet new3 --set:preference language=F#
```

Setting a preference for all hosts that identify the same way as this one (host identifier specific)
```
dotnet new3 --host:set:preference language=F#
```

Setting a preference for all hosts (not specific to the current host identifier or version)
```
dotnet new3 --global:set:preference language=F#
```

**Comment by enricosada** [comment]
@mlorbetske  in the meantime, it's possibile to read a simple `DOTNET_NEW_PREFERRED_LANG` env var? 
Can be just for .net core sdk 1.0, but will improve **a lot** the experience for f# devs.

i'll do the PR, np. 

It's really tiring to write always `-lang f#`, because that's the main usage for non c# devs /cc @dsyme

i think is really low risk, low impact (pretty sure is just a two line change)

@mlorbetske I think we are late for sdk 1.0, but you have a idea on how to implement these config? mostly about where/how store these config. It's a really nice to have for f# devs.

**Comment by mlorbetske** [comment]
This change to read the environment variable would be made here https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-new/NewCommandShim.cs#L54

For the configuration, we create a .templateengine directory under the user's home directory where we store configuration data.

**Comment by enricosada** [comment]
thx a lot @mlorbetske . added pr https://github.com/dotnet/cli/pull/5679 to add an env var, until `--set` command is ready

**Comment by grinrag** [comment]
This bug is outdated, closing it now. Feel free reopen if it still valid.
