### ISSUE TITLE
Problem in "dotnet new -i "Microsoft.AspNetCore.SpaTemplates::*" 

### ISSUE THREAD

**Issue by Shawn-Fan** [dotnet/templating#1201]
I run dotnet new -i "Microsoft.AspNetCore.SpaTemplates::*" , but i got 2 angular templates tags with same short name same follow:

Templates Tags                                                              Short Name                   Language 
  ......
MVC ASP.NET Core With Angular Web/MVC/SPA          angular                          [C#]
ASP.NET Core with Angular Web/MVC/SPA                    angular                          [C#]
  .......
![image](https://user-images.githubusercontent.com/15960295/29193990-dcc83a16-7de4-11e7-89bc-3b75a0e1b9f8.png)

so , I can not use "dotnet new angular". Please help me how to delete another Template Tag or select one?

**Comment by seancpeters** [comment]
@Shawn-Fan, you can use the template full name on the command line instead of the short name. So if you run:
`dotnet new "MVC ASP.NET Core with Angular"`
then the first Angular template in the list will be created. And if you run:
`dotnet new "ASP.NET Core with Angular"`
the second template in the list will be created.

**Comment by mlorbetske** [comment]
cc @SteveSandersonMS

**Comment by SteveSandersonMS** [comment]
This problem should no longer occur as of `Microsoft.AspNetCore.SpaTemplates` version 1.0.0 or later, as it no longer contains `angular`/`react`/`redux` templates (because those are all built into the .NET Core 2.0 SDK now, via the preinstalled package `Microsoft.DotNet.Web.Spa.ProjectTemplates`).
