### ISSUE TITLE
Global.json template: bad version number

### ISSUE THREAD

**Issue by andiblas** [dotnet/templating#1232]
Today i tried to create a ASP Net Core project from scratch. I found out that when running `dotnet new globaljson` creates a global.json file with this contents:

```
{
  "sdk": {
    "version": "200"
  }
}
```

That version number caught my attention. Therefore, when running other commands such as `dotnet new webapi` threw me errors as seen on the capture below:

![image](https://user-images.githubusercontent.com/11488736/30038175-41c2f034-9198-11e7-9038-a67756929b81.png)

So, i tried to sort of fix this putting a couple of dots to the version number of the `global.json`

```
{
  "sdk": {
    "version": "2.0.0"
  }
}
```
After that, the generation of the new project worked flawlessly:

![image](https://user-images.githubusercontent.com/11488736/30038256-ddf37df2-9198-11e7-89ea-f2c241635915.png)

Is there any chance that the template isn't working properly?

Any environment info needed, feel free to ask.

**Comment by andiblas** [comment]
I've tested that and got the same results :(

![image](https://user-images.githubusercontent.com/11488736/30112845-21fc2df4-92e9-11e7-8f91-05b57b73f8aa.png)

**Comment by mlorbetske** [comment]
@seancpeters any ideas?

**Comment by seancpeters** [comment]
@andiblas - could you also try running:
```dotnet new globaljson --locale en-US```
I want to eliminate the possibility that this is being caused by a localization issue.

**Comment by andiblas** [comment]
I've tested that command and got the same results again. 

![image](https://user-images.githubusercontent.com/11488736/30177706-07cf7a9a-93dd-11e7-93d0-3d90a67a09ce.png)

**Comment by mlorbetske** [comment]
I believe there was a bit of confusion here. The --locale switch (as @seancpeters) mentioned, only governs the output language of the templates, not the message language or the processing of value formats. The way to test for locale related issues would be to try setting the locale of the shell to en-US rather than setting that as the locale passed to `new`. We'll try this out on our side & get back to you.

**Comment by andiblas** [comment]
I'll be here listening this thread in case you need to test something else on my side. Thanks in advance!

**Comment by seancpeters** [comment]
@andiblas - sorry for the delay. I've discovered that the problem is due to a bug with how we deal with numbers in different locales. In some locales the decimal separator is ".", and in other locales it is ",". I'm working on a fix for the issue right now, I'll add a reference to the pull request here.

**Comment by rendmath** [comment]
Same problem here.

Workaround: Switching the preferred Windows language from English (Belgium) (in my case) to English (United States).
