### ISSUE TITLE
Add example(s) for adding custom conditional processing

### ISSUE THREAD

**Issue by patridge** [dotnet/templating#1237]
In a template I'm creating, I want to have conditional content in a Markdown (*.md) file. Just including `#if (someCondition)` doesn't seem to work, but I found some promising information in the [**CustomOperations**](https://github.com/dotnet/templating/wiki/%22Runnable-Project%22-Templates#customoperations-optional-and-specialcustomoperations-optional) section. Unfortunately, I am not sure how to use the various fields/sections to accomplish this.

I'm not totally sure when something should have it's first letter capitalized as the section titles imply, or lower-case as some of the examples suggest (or if that even matters). From what I have read, I was guessing I need a top-level property of `SpecialCustomOperations", so I started with something like this, though I have little clue what some of these values should be.

```json
{
    …
    "SpecialCustomOperations": {
        "*.md": {
            "Operations": {
                "type": "conditional",
                "configuration": {
                    "if": [ "<!--#if" ],
                    "else": [ "<!--#else" ],
                    "elseif": [ "<!--#elseif" ],
                    "endif": [ "<!--#endif" ],
                    "actionableIf": [ "<!----#if" ],
                    "actionableElse": [ "<!----#else" ],
                    "actionableElseif": [ "<!----#elseif" ],
                    "actions": [ "cStyleUncomment", "cStyleReduceComment" ],
                    "trim": true,
                    "wholeLine": true,
                    "evaluator": "C++"
                }
            }
        }
    }
}
```

I'm mostly looking to duplicate what might be set up for XML already, but I don't know how best to do that. That configuration above results in an error like this, so I might need to dig deeper into running things from source at some point.

```
Error reading template from file: /.template.config/template.json | Error = Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'Newtonsoft.Json.Linq.JArray'.
Object reference not set to an instance of an object.
```

**Comment by seancpeters** [comment]
@partridge - The top-level SpecialCustomOperations section is the correct place to setup this type of configuration. The specific error you're getting is because the "Operations" section needs to be an array of objects. Here's the full configuration I think you're looking for (it should operate the same as what is configured for xml file processing):
```
  "SpecialCustomOperations": {
    "**/*.md": {
      "operations": [
        {
          "type": "conditional",
          "configuration": {
            "actionableIf": [ "<!--#if" ],
            "actionableElse": [ "#else", "<!--#else" ],
            "actionableElseif": [ "#elseif", "<!--#elseif", "#elif", "<!--#elif" ],
            "endif": [ "#endif", "<!--#endif" ],
            "trim" : "true",
            "wholeLine": "true",
            "actions": [ "fixPseudoNestedComments" ]
          }
        },
        {
          "type": "balancednesting",
          "configuration": {
            "startToken": "<!--",
            "realEndToken": "-->",
            "pseudoEndToken": "-- >",
            "id": "fixPseudoNestedComments",
            "resetFlag": "_TestResetFlag_"
          }
        }
      ]
    }
  }
```

In general, the casing of every key in template.json should not matter - any read errors due to their case should be considered a bug.
*Note*: the operations types, such as "balancednesting" & "conditional" are case-sensitive and will not work if cased differently. For these specific errors, in an operation type is unknown, when invoking the template, a warning will be displayed, such as:
```Operation type = [balancedNesting] from configuration is unknown.```

For the conditional operation setup, the meanings of the "actionable" vs. "regular" keywords is as discussed in the documentation from the link you referenced. Unless you want to get keep into how the underlying source works, it's safe to assume that `trim` and `wholeLine` should always be true. 

The `actions` value in the conditional config refers to the other operation I've configured in this example. Its purpose is to deal with nested xml-style comments as best as possible. Since in general, nested block comments aren't correct / possible, e.g.:
```
<!-- start outer comment
  <!-- start inner comment
     more stuff
  end inner comment --> 
end outer comment -->
```
This is syntactically incorrect because the "end inner comment -->" actually ends the outer comment. But for template conditional processing we needed a way around this, which as accomplished by what we've called the "pseudoEndComment". When template files are processed with this sort of block-comment configuration, it allows for this type of situation:
```
  <!--#if (true)
	<!-- commented out stuff to include if true -- > 
  #endif-->
```
...note the 'inner' comment ends with `-- >` instead of `-->`. The configuration will recognize it as effectively an end comment and deal with it appropriately. If it is going to get written to an output file, the processing will 'fix' it, changing it from a `pseudoEndToken` to a `realEndToken`.

The `id` of the balancednesting configuration just needs to be unique among the defined operations. The id value is used in the conditional config `actions` to reference the balancednesting config.

The balancednesting configuration also attempts to deal with template authoring errors where block comments are not properly balanced. But it can only do so much, and sufficiently mis-authored files can still have problems. The `resetFlag` is used internally for this purpose, and just needs to be unique among the `flags` in the operations.

This should hopefully get your template working, but if any of this is unclear or not working, or if you'd like to go into more detail about any of it, please let me know what you'd like to know more about.

**Comment by patridge** [comment]
@seancpeters Thank you so much for the explanation. It has been very helpful. Unfortunately, while I've been able to get past that original error, it's now throwing out just a null reference message without any further diagnostic information.

> Object reference not set to an instance of an object.

I tried setting the `verbosity`, but I can't seem to get that to work either (failed attempts: `dotnet --verbosity diag` ["Unknown option: -v"], `dotnet new --verbosity diag` ["Invalid input switch"]).

I tried setting the template to just the minimum with the above "SpecialCustomOperations" setup as well as running it against a near-empty template, both with the same above error message.

**Comment by seancpeters** [comment]
@partridge - can you post your entire template.json? I'll try to diagnose what's going on.

**Comment by patridge** [comment]
@seancpeters Sadly, in making a shareable repro template, my issue went away entirely. At one point, I unintentionally overwrote the problem template in `dotnet new`, so it could have been a fluke artifact that just needed to be cleaned out. Now, neither the sample nor the original cause any errors when generating a new output from those templates.
