### ISSUE TITLE
Allow to specify caret position in a template

### ISSUE THREAD

**Issue by xtmq** [dotnet/templating#1249]
I'd like to specify a file which IDE should open and a position in the file where IDE should put a caret after expanding a template. As far as I understand there is no way to do that right now. 
We are going to integrate the template engine into JetBrains Rider and this is an important feature for us.

**Comment by seancpeters** [comment]
The template engine itself would not be able to implement this functionality because it would be different for each IDE using the template engine. But we have "post actions" which are designed to have a common configuration, and each "host" that integrates using the template engine has the option to implement each post action, or not implement them. 

Here are the current post actions that are defined by the template engine: https://github.com/dotnet/templating/wiki/Post-Action-Registry

We have already defined a post action to configure opening a file in an editor, but we haven't defined how to configure it specify where the caret (cursor) should be placed in the file. It appears that the documentation for this post action is incomplete, but here is an example of a template configured to have a file opened in the editor:
https://github.com/dotnet/templating/blob/rel/2.1.0-preview1/template_feed/Microsoft.DotNet.Common.ProjectTemplates.2.1/content/ConsoleApplication-CSharp/.template.config/template.json

The relevant part of the configuration is at the bottom of the file:
```
  "postActions": [
  ...
  {
      "condition": "(HostIdentifier != \"dotnetcli\" && HostIdentifier != \"dotnetcli-preview\")",
      "description": "Opens Program.cs in the editor",
      "manualInstructions": [ ],
      "actionId": "84C0DA21-51C8-4541-9940-6CA19AF04EE6",
      "args": {
        "files": "1"
      },
      "continueOnError": true
    }
  ]
```

This is a good idea, we just need to decide how to configure specifying the desired position. My thought is to allow configuring the line number & column within the file. If we were to do this, the position would be specified in the "args" part of the configuration, and would look something like this:
```
  "postActions": [
  ...
  {
      "condition": "(HostIdentifier != \"dotnetcli\" && HostIdentifier != \"dotnetcli-preview\")",
      "description": "Opens Program.cs in the editor",
      "manualInstructions": [ ],
      "actionId": "84C0DA21-51C8-4541-9940-6CA19AF04EE6",
      "args": {
        "files": "1",
        "cursorLine": 23,
        "cursorColumn": 37
      },
      "continueOnError": true
    }
  ]
```

I see one potential problem with this idea: The file being opened in the editor could have conditional content, which could cause the specified cursor to be positioned in "different" places depending on which pieces of the conditional content are included. One way to work around this problem would be to define multiple post actions for the same file, with conditions that correspond to the conditional content, and specify different lines & columns - so that with or without the conditional content, the cursor would be placed in the same logical position. This is just a tentative proposal, I'd like to hear what @phenning, @mlorbetske, & @sayedihashimi think about it before we finalize anything.

@xtmq - Were you thinking of using the line & column to position the cursor, or were you thinking of a different way to specify the position?

@phenning - I think your host is the only one that has implemented the "open a file in the editor" post action, is there any additional configuration available that isn't shown in my above example?

**Comment by xtmq** [comment]
@seancpeters Thanks for a detailed reply =) 
In Rider we've already implemented OpenFile post action handling. 

About caret position. 
Personally I don't like numbers like these in a template configuration. It is difficult to support them in consistency: _"I only add a new using directive in a file, nothing will be broken in the template I'm sure"_. Besides we have to recalculate these numbers when we replace template parts, think about conditions (as you told) and so on.

Now in our templates we just have a marker like $caret$, but it will not work in the engine. Another possible approach is defining a caret relative to some text fragment, like _"next line after main method"_ or _"just before View('Home')"_. Now we have to hard code these rules (as regular expressions) in Rider for your .net core templates =) Otherwise user experience is worse than with our own templates. 

And now we are going to rewrite all templates based on your engine. And we do not want implementing caret features just for Rider. It would be nice to unify a solution across all other templates.

**Comment by seancpeters** [comment]
@xtmq - you could continue using the $caret$ marker in your templates. The template engine would just write it to the created file(s) without performing any processing on it. Then your open file action could look for the symbol and place the cursor accordingly. 

Another possibility is to setup the caret position information in Rider host-specific configuration files for the templates. That way you'd have full control over how the positioning is specified for your templates; and could have a fallback action if the position is not specified, such as positioning the cursor at the start of the file. This is probably the best option.

**Comment by xtmq** [comment]
In that case other (non-Rider) templates will not provide information about caret position. But it would be nice to have the same feature across all templates (at least possibility to represented a position in the same way). I'm pretty sure it is useful feature for all templates and IDEs.

**Comment by seancpeters** [comment]
Relative to this, we were just discussing the idea of having the template engine be able to look for any pattern the author specifies, such as "$caret$". It would be able to report the effective position in the output file, and that position would be available for post actions. This is still in the early stages of design, so I don't have any timeframe for when it would be available. But would something like that be sufficient for you?

**Comment by xtmq** [comment]
If you apply all transformations to a file and then remove the $caret$ marker and return its position in post actions(s) then it will solve the issue =) sounds like a good idea actually.

**Comment by xtmq** [comment]
By the way we can specify such markers as comments (/*caret*/ in C# for example) so we will not break template compilation.

**Comment by donJoseLuis** [comment]
This issue was last touched some years ago.  We are working on a new delivery road map.  Please reopen if this is something we want & we'll properly assess its' priority compared to other work aimed at improving the overall templating UX.
