### ISSUE TITLE
Let's add additional information to ICreationPath

### ISSUE THREAD

**Issue by xtmq** [dotnet/templating#1258]
Right now there is now way to identify if a ICreationPath from ICreationResult.PrimaryOutputs represents a project file or any other file (e.g. for opening in an editor). 
This feature is important when a created project(s) should be added to a solution file.

**Comment by seancpeters** [comment]
The post actions are meant to be configured so that the primary outputs to be acted on are referenced in the post action arguments - currently they reference the index of the primary output. But this has numerous shortcomings: for example if a primary output is conditional, the indexes change; as well as your case where you'd just like to what "type" of file each primary output references. 

I have been thinking for a while about a plan to make this better, and I believe it will satisfy your needs. Here is an example of the current configuration for primary outputs (from the XUnit-CSharp 2.1 template):
```
  "primaryOutputs": [
    { "path": "Company.TestProject1.csproj" },
    {
      "condition": "(HostIdentifier != \"dotnetcli\" && HostIdentifier != \"dotnetcli-preview\")",
      "path": "UnitTest1.cs"
    }
  ],
```
We're planning to change this configuration so each output has a name, and can also have arbitrary key-value pair metadata associated with it. The proposed configuration would look something like this:
```
  "primaryOutputs" {
    "<unique name>": {
	  "path": "<path to output file, same meaning as in the current configuration>",
	  "condition": "<optional, same as current configuration>",
	  "args": {
		// author defined key-value pairs
	  }
	}
  }
```
With this change, a post-action implementation could require certain pieces of information in the `args`. If I interpret your post correctly, it sounds as if you want to make a post action that would be able to recognize all of the project files and add them to the solution. This could be accomplished with something like this in the [new, proposed] primary output configuration:
```
  "primaryOutputs" {
    "StartupProject": {
	  "path": "path\to\my\Project.csproj",
	  "args": {
	    "isProject": true
	  }
	},
	"TestProject": {
	  "path": "path\to\my\TestProject.csproj",
	  "args": {
	    "isProject": true
	  }
	},
	"ExtraFile": {
	  "path": "path\to\something.txt",
	  "args": {
	    "openInEditor": true
	  }
	}
  }
```
There would also be some corresponding changes to the post action configuration.

With something like this, the primary outputs could be filtered by the args. They could also be referenced by their names in the post action configurations, which is analogous to the current index-based references.

But, I want to stress that the above is a tentative design and is not guaranteed to be what we ultimately implement - and I don't have a timeframe for when this will become priority.

Another important consideration is backwards compatibility with the existing primary output & post-action configurations. If / when we make this change, part of the work in dotnet/templating will be to make the post actions work with either the new or the old configuration styles. When reading the configuration, we'd probably set a flag indicating the version of the primary output configuration, and make that available to post-actions, so they'd know how to interpret the primary outputs correctly. 

If you have any concerns with primary outputs & post actions that this won't facilitate, please let us know.

**Comment by xtmq** [comment]
Your suggested design looks sufficient and logical =)
