### ISSUE TITLE
dotnet new for template from path fails: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by jannikb-sim** [dotnet/templating#1292]
I do get errors when I try to instatiate from templates that were installed from a file path:

## Steps to reproduce

git clone https://github.com/dotnet/dotnet-template-samples/
dotnet new --install .\dotnet-template-samples\01-basic-template\MyProject.Con\.template.config\
dotnet new sample01

## Expected behavior

dotnet does not throw errors

## Actual behavior

output:
Die Vorlage "Contoso Sample 01" konnte nicht erstellt werden.
Object reference not set to an instance of an object.

## Environment data

dotnet --info output:
.NET-Befehlszeilentools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by seancpeters** [comment]
@jannikb-sim - Try re-installing the template, but make the install path 1 directory higher - what I mean is run:
`dotnet new --install .\dotnet-template-samples\01-basic-template\MyProject.Con\`
instead of
`dotnet new --install .\dotnet-template-samples\01-basic-template\MyProject.Con\.template.json`
and the template should work.

Still, this is a bug, we need to handle situations like your original command differently.

**Comment by jannik2b** [comment]
@seancpeters thanks, your proposed solution works.
