### ISSUE TITLE
Is it possible to ignore files?

### ISSUE THREAD

**Issue by jannikb-sim** [dotnet/templating#1297]
Is it possible, when installing a custom template (dotnet new --install) to ignore some files? For example when developing lets say a DotNetCore template, I will have binaries under /obj and /bin and Visual Studio will create a folder /.vs that should not be part of the final templates source files.
IMHO it should be something similar to what a .gitignore file does. Actually it would be nice if .gitignore could be reused.

To add more perspective: The actual use case is that the template itself will be developed over time, so I will from time to time need to re-install the template. When re-installing it would be cumbersome to manually delete everything that is not wanted.

**Comment by seancpeters** [comment]
Yes, it's possible to do what you're asking. By default, a template will exclude from the output, the following:
- "bin" and "Bin" directories and their content
- "obj" and "Obj" directories and their content
- The ".template.config" directory and its content
- Any files with the extensions ".filelist", ".user", and ".lock.json"

The default configuration can be overridden or added to by defining a custom "Sources" section in your template.json file.

If you want to add additional exclusions, something like this will take care of it:
```
"sources": [
    {
      "modifiers": [
        {
          "condition": "(!IndividualAuth && !OrganizationalAuth)",
          "exclude": [
            "Controllers/AccountController.cs",
            "Views/Account/**",
            "Views/Shared/_LoginPartial.cshtml"
          ]
        },
```
The above is taken from https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates.2.1/content/StarterWeb-CSharp/.template.config/template.json
The "condition" specification is optional, without a condition the excludes will always happen (and with a condition, only when it's true). The "exclude" configuration is an array of additional exclusions, which can be explicit file / path combinations, or include globbing patterns (both are shown above). When excluding a directory, be sure to exclude its content using `/path/to/directory/**`, otherwise, if any file in a directory is not excluded, the directory will be created.

If you want to completely override the default exclusion configuration, the syntax is very similiar, except the exclusions are not under a "modifiers" section, such as:
```
"sources": [
  {
    "exclude": [
      "**/*.foo",
      "**/*.vs"
    ]
```
