### ISSUE TITLE
String parameter converted to number

### ISSUE THREAD

**Issue by sibille** [dotnet/templating#1322]
I'm facing a problem with a parameter: The parameter is of type string, but when putting in a value containing only numbers and dots, like 1.0.0.0, it's value when generating is set to 1. 

We're using the version distributed with VisualStudio, in a former version (1.0.0-beta2-20170518-234) this was working correctly. 

Our parameter configuration is the following: 

"wts.wizardVersion":
{
"type": "parameter",
"dataType": "string",
"replaces": "Param_Wizard.Version"
},

Has this changed? Am I missing something?

**Comment by mlorbetske** [comment]
This looks to be the same as #1302 (fixed by #1299, #1303 and #1308). A version of the engine containing the changes should be included in 15.6 preview2 or higher.

The change was introduced by the change to use the identity value form to generate replacements rather than the parameter's value itself. Since parameters carry the `dataType` property but other symbol types did not, the value from the forms was treated as needing type inference. For cultures where `.` is a thousands separator, `int.TryParse` (using the current culture) returns that the value is, in fact, numeric.

The only odd bit here is that you're indicating that `1.0.0.0` is becoming `1` rather than `1000` - is this correct?

**Comment by sibille** [comment]
I just tried and output is 1000 as you state. I think when I opened the issue it was 1, but I don't remember exactly.

**Comment by mlorbetske** [comment]
Closing this as the fix should be available. Please re-open if that's not the case
