### ISSUE TITLE
dotnet new fails

### ISSUE THREAD

**Issue by jannikb-sim** [dotnet/templating#1323]
## steps to reproduce
I have installed a template from a path which looks like this
`{
  "$schema": "http://json.schemastore.org/template",
  "author": "My Name",
  "classifications": ["ASPNETCore"],
  "groupIdentity": "My Company",
  "identity": "MyCompany.NetCoreTemplate",
  "name": "MyCompany NetCore project template",
  "shortName": "mytemplate",
  "tags": {
    "language": "C#",
    "type": "project"
  },
  "sourceName": "MyCompany.NetCoreTemplate",
  "preferNameDirectory": false
}
`

I installed it by providing the path like this: `dotnet new --install c:\...\.template.config`
The template shows up in the list.
If I run `dotnet new mytemplate` I get an error `Die Vorlage MyCompany NetCore project template konnte nicht erstellt werden. Object reference not set to an instance of an object.`

## dotnet --info
.NET-Befehlszeilentools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by seancpeters** [comment]
@jannikb-sim - The error you're seeing is because some of the template content is outside of the install path, which we don't allow. When you install the template, try using an install path one directory above the .template.config directory. For example, if the .template.config for this template is located at:
`c:\foo\bar\templates\TestTemplate1\.template.config`
try installing using:
`dotnet new --install c:\foo\bar\templates\TestTemplate1\`

Installing 2 directories up from the .template.json file will work, unless the template has custom sources defined which reference content farther up the path.

The error you received is not very intuitive. We've some changes for a future release, which will give a more meaningful error in situations like this - but the error will occur when installing the template, and prevent it from being installed. This is the upcoming change: https://github.com/dotnet/templating/pull/1305
