### ISSUE TITLE
Restore fails with "No Primary Outputs to restore"

### ISSUE THREAD

**Issue by ben-foster-cko** [dotnet/templating#1324]
As per the subject, when adding a post action to restore nuget packages I get the message:

```
The template "Checkout Console Service Template" was created successfully.

Processing post-creation actions...
No Primary Outputs to restore.

```

.template.json

```
{
  "$schema": "http://json.schemastore.org/template",
  "author": "Checkout.com",
  "classifications": [
    "Console"
  ],
  "groupIdentity": "Checkout.Templates",
  "name": "Checkout Console Service Template",
  "identity": "Checkout.Templates.ConsoleService.CSharp",
  "shortName": "cko-console-service",
  "tags": {
    "language": "C#", // Specify that this template is in C#.
    "type": "project"
  },
  "sourceName": "ConsoleServiceTemplate",
  "preferNameDirectory": true,
  "sources": [
    {
      "exclude": ".vscode"
    }
  ],
  "symbols": {
    "skipRestore": {
      "type": "parameter",
      "datatype": "bool",
      "description": "If specified, skips the automatic restore of the project on create.",
      "defaultValue": "false"
    }
  },
  "postActions": [
    {
      "condition": "(!skipRestore)",
      "description": "Restore NuGet packages required by this project.",
      "manualInstructions": [
        {
          "text": "Run 'dotnet restore'"
        }
      ],
      "actionId": "210D431B-A78B-4D2F-B762-4ED3E3EA9025",
      "continueOnError": true
    }
  ]
}
```

**Comment by seancpeters** [comment]
@ben-foster-cko - This error occurs because the restore post-action is meant to run restore on specific *.*proj files which are included as primary outputs in the template.json. (and in a future release, we'll also restore .sln files listed in the primary outputs). To get restore to work, you'll need to add a primary outputs section listing the *.*proj file(s) to be restored. 

Here's an example primary outputs specification, taken from a template in this repo:
```
"primaryOutputs": [
    { "path": "Company.ClassLibrary1.csproj" },
    {
      "condition": "(HostIdentifier != \"dotnetcli\" && HostIdentifier != \"dotnetcli-preview\")",
      "path": "Class1.cs"
    }
  ],
```
... taken from: https://github.com/dotnet/templating/blob/rel/2.1.0-preview1/template_feed/Microsoft.DotNet.Common.ProjectTemplates.2.0/content/ClassLibrary-CSharp/.template.config/template.json

Primary outputs can be unconditional, like the first one listed, or only emitted based on a condition, like the second one. It's ok to have primary outputs that are not appropriate file types for restoring, they'll simply be ignored by the restore post action.

**Comment by ben-foster-cko** [comment]
@seancpeters will this automatically cater for the renamed csproj file in the template?

For example, `SourceTemplate.csproj` will get renamed to the user's project name during creation. Will the above script cater for this?

**Comment by ben-foster-cko** [comment]
It worked, thanks!

**Comment by seancpeters** [comment]
Sounds like you answered your own question via testing :) But I wanted to confirm it anyway: primary outputs will always get substitutions applied to the file names & paths in the same way that the actual template files are adjusted - so they'll always match up.
