### ISSUE TITLE
[loc][Query][.NETCoreTemplateEngine] Localizability of "0; "SingleUpdateApplyPrompt" 

### ISSUE THREAD

**Issue by PDostalek** [dotnet/templating#1342]
**Hi, we have a question from a translator. Could you help please?**

**Source**:
{0} : update ([Y]es|[N]o)?

**File Name:**
localize\ploc\Microsoft.TemplateEngine.Cli.resources.dll

**Resource ID:**
0; "SingleUpdateApplyPrompt"

**Query:**
Please confirm that letters between [ and ] are localizable

**Comment by seancpeters** [comment]
@PDostalek - I have code setup to use the []'d letters as the valid command line inputs. So the full strings would need localization as if the brackets weren't there, e.g. "[Y]es" -> "[O]ui" in French. But then the user would be entering 'O' instead of 'Y', which I'd need to be able to handle.

Is there a way to setup the string to be localized so that the entire string "{0} update ([Y]es|[N]o)" gets localized, and also get the single bracketed letters similarly localized? I could make resource strings for "Y" and "N", but the context of the string they're referring to would be needed to localize them properly.. I'm thinking something along the lines of having 3 strings to be localized, like this:
SingleUpdateApplyPrompt: "{0}: update ([Y]es|[N]o)?"
SingleUpdateYesResponse: "Y"
SingleUpdateNoResponse: "N"
... but the translations would need to correspond. If that's acceptable, great!

If there are other or better ways to deal with situations like this, I'm open to ideas.

**Comment by PDostalek** [comment]
Yes, we agree with this approach . From localization perspective we will have to just ensure that strings will be consistent with ask string. Thanks for cooperation.

**Comment by seancpeters** [comment]
@PDostalek:
I created the necessary localizable strings in #1345. I added commented to the response strings, indicating that they need to be localized the same as the corresponding words in the prompt strings.
There is also a third set of prompt / response strings which didn't originally have the bracketed letter responses. They've also been modified and will need corresponding localization. 

Please let me know if this works for you, or if we need something else.
