### ISSUE TITLE
Using dotnet new for targeting .NET Framework

### ISSUE THREAD

**Issue by ChrisMaddock** [dotnet/templating#1406]
I wanted to use `dotnet new` to create new full framework projects. 

I was initially surprise when this didn't work:

```
dotnet new classlib -f net471
```

Given it's just changing the target framework, I assumed I must be using the wrong tfm or something, so spent a bit of time digging into the docs. Nothing was documented, so I then assumed that it wasn't implemented, and the focus of the default tooling must be on .NET Core/Standard instead. 

Then, however, I came across https://github.com/dotnet/templating/issues/551 - and found out what I want to do is actually perfectly possible with the default tool - just with a seemingly undocumented option!

```
dotnet new classlib --target-framework-override net471
```

Why is this option undocumented? Is it a supported way to use `dotnet new` - or should I expect the option to be removed at any time? I want to write a tool based around the above command - so am keen to understand if I can rely on this option, or should instead write my own template to create a basic net471 csproj. (Or, of course, contribute one to the tooling here!)

**Comment by mlorbetske** [comment]
This has always been a bit of an interesting one, since the templates ship with the dotnet CLI, there's not actually a guarantee that the .NET Framework will be available on the machine the templates are being created on, which is the main reason for not exposing those as accepted values to the `--framework` option. Also, the list of versions of .NET Framework that could be targeted is pretty large in comparison to the available .NET Core versions for most of the templates where it's applicable (the exception being class libraries where the number of netstandard versions + netcoreapp versions is greater) which would draw attention away from the things that will necessarily work on any system with the dotnet CLI.

The `--target-framework-override` option is included on certain templates as a free-text parameter where you can put in whatever you like, it's not guaranteed to be present on all templates. Incidentally, all of the project templates in this repository include the option, I believe on all of the templates built in aspnet/templating have it as well. Usage of this option isn't something we promote using since we can't guarantee that any value put in would work (hence the option being hidden even on the templates that do support it). It's not a feature of the engine and is intentionally made available on the templates offered here, so it's safe to go on using - Visual Studio 2017 uses this option under certain circumstances, where it's known that the template provides it, to create projects targeting .NET Framework.

We have thought about adding an extended mode to help that would show hidden parameters as well to try to be more accurate about what the template supports while preventing options like this from appearing to be things that are encouraged to be or commonly used. Unfortunately, we have not yet fully designed that or started the work. Another approach to the problem that we may investigate in time is to add another parameter type - something like "free text with suggestions" where the available, relevant types at the moment are free text (no suggestions would be offered and content differentiation based on the selected value wouldn't work for framework) or choice (where the only valid options are defined by the template & are offered as suggestions in help - this is the one currently being used).

We're always happy to accept contributions to this project, however, additional templates supporting full framework or specific gestures for the dotnet CLI to support runtimes it doesn't bring with it would likely not be a good fit here.

**Comment by ChrisMaddock** [comment]
> Since the templates ship with the dotnet CLI, there's not actually a guarantee that the .NET Framework will be available on the machine

Aha! That's a very valid reason. I hadn't thought of this - I've been using the dotnet CLI to develop full framework stuff, and hadn't made the connection that it was only installed with .NET Core.

On the extended help mode - that sounds very useful. I wonder if there's a better way to document this `--target-framework-override` option for the specific main console/classlib template. I understand that it's an option specific to these templates - but using these options to create full framework projects sounds like a very mainstream task, and I was surprised the perfect, supported solution buried in an old GitHub PR. (It doesn't sound like there's anywhere else I could have found that information - other that looking at the source code?) 

The main documentation I found was at: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new?tabs=netcore2x. I wonder if it's possible to add something there, maybe more an example for the specific case.

On my problem as a whole - perhaps the intermediate solution is that I create some .NET framework templates as a custom template package, to allow these to be supported via the `--framework` flag.

Thanks a lot for your detailed response - very much appreciate you taking the time out to answer this fully!
