### ISSUE TITLE
Bug renaming Item Template

### ISSUE THREAD

**Issue by dansiegel** [dotnet/templating#1410]
In the Prism QuickStart ItemTemplates, I have templates for different Xamarin Forms Page types (i.e. ContentPage, TabbedPage, etc) which follow the naming schema `{PageType}Template`. 

Upon creating an item like `dotnet new prismitem -page TabbedPage -n MyTabbedPage` only the appropriate template should be created and be named MyTabbedPage. This used to work in older versions of the cli, by renaming the correct View template to ItemTemplate which would then be renamed to MyTabbedPage or whatever the name was. 

Issue first reported dansiegel/Prism-Templates#28

**Comment by seancpeters** [comment]
I've tracked down the problem here, and created PR #1411 to fix it. The problem was that file renames based on the "sources" section of the template configuration were being honored, but did not get the symbol-based fileRename changes applied to them. The symbol-based renames were only being applied if a sources-based rename was not applied. (The configured sourceName, along with the -n flag creates its own symbol-based fileRename).

Thanks for bringing this issue to our attention!

**Comment by seancpeters** [comment]
Fixed by #1413
