### ISSUE TITLE
How to keep some references with same base name from changing

### ISSUE THREAD

**Issue by aronblum** [dotnet/templating#1415]
So everything with my template is working great. Only thing is I have two common libraries with the same base name as the projects I will be making. When creating a new project the template renames these to include the name of the project I am making. Is there any way to perhaps include a wildcard in the config somewhere to say ignore all references to SX.API.CommonV2*?

![image](https://user-images.githubusercontent.com/12314011/36080778-9dbbc9ca-0ffa-11e8-9588-80062f4b3ed1.png)

Thanks a lot for any help!

**Comment by seancpeters** [comment]
@aronblum - I have a couple possible ideas for what you need, but I'd like to get a little more information about your template first. If the template is available on NuGet.org, could you point me to the package name & version? If not, could you post information about your template.json, particularly everything under the "sources" section (if you defined one), and also the 'sourceName' value? Any parameters which specify fileRename would be helpful too. Finally, having the original names of the files you'd like to not get renamed would also be useful.

**Comment by aronblum** [comment]
Hi @seancpeters, below is a copy of what I have in my file:

{
  "author": "aronblum",
  "classifications": [],
  "description": "template description",
  "name": "SX API Template",
  "defaultName": "SX.API.Name",
  "identity": "SX.API.Template",
  "groupIdentity": "SX.API",
  "tags": {
    "language": "C#",
    "type": "project"
  },
  "shortName": "sxapitemplate",
  "sourceName": "SX.API",
  "guids": [
    "{125C34ED-4903-44F7-83F5-BA68259285C5}",
    "{F887230C-91DD-4583-A33F-4DB355CA1439}",
    "{D9B0CB0A-A67E-47A7-B74B-B148E1CAEC84}",
    "{EA36792D-5425-4F92-806C-453A456C96D3}",
	"{75AD2F2D-F390-4AF5-B10A-714DF8AA212B}"
  ],
  "primaryOutputs": [
    {
      "path": "SX.API\\SX.API.csproj"
    },
    {
      "path": "SX.API.DataAccess\\SX.API.DataAccess.csproj"
    },
    {
      "path": "SX.API.Model\\SX.API.Model.csproj"
    },
    {
      "path": "SX.API.Tests.Integration\\SX.API.Tests.Integration.csproj"
    },
    {
      "path": "SX.API.Tests.Unit\\SX.API.Tests.Unit.csproj"
    }
  ]
}

**Comment by seancpeters** [comment]
Thanks for the info. There is not currently an explicit way to prevent file renames, but there are ways to accomplish the same thing.

The easiest way around the file rename problem is to either:
(1) Change the value of "sourceName" so it is not a substring of the file names that shouldn't get changed. At the same time, the places where source name value should get replaced will need to get changed to the new value of the "sourceName".
(2) Change the names of the files whose names shouldn't be changed so their names don't contain the sourceName value. This may cause some other content changes, for example referring to those files.

Number (2) seems like less work. But if those file names cannot be changed, then (1) is the correct way to go. Hopefully with some global search-and-replace, it won't be too painful.

You had also mentioned not wanting the usings in the problematic files to be changed based on the sourceName value. If the entire contents of those files should be copied with no changes in them, they can be specified as "CopyOnly" in the sources section. Since you don't have a sources section already, all you'd need to add is this ("sources" is a top-level key in the template.json schema):
```
  "sources": [
    {
      "modifiers": [
        {
          ""CopyOnly": [
            <individually quoted, comma separated list of files to copy without any template processing, for example:>
             "foo.txt",
             "Bar.cs"
          ]
        }
      ]
    }
  ]
```
Note that marking files as copy only when no template processing should occur will speed up template creation :)

But, if there is some content in those files that needs template processing, we can mark the appropriate sections of the files to suppress certain templating operations. The markup to prevent replacements varies based on the file type, similarly to how template condition syntax varies from file type to file type. For a .cs file, it would look like this:
```
using System;

namespace Company.ConsoleApplication1
{
    class Program
    {
//-:replacements:noEmit
// don't replace the sourceName here: 	Company.ConsoleApplication1
//+:replacements:noEmit	
		
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
		
// DO replace the sourceName here: Company.ConsoleApplication1
    }
}
```

The important pieces are `//-:replacements:noEmit` and `//+:replacements:noEmit`. Note that they only differ by the '-' in the first one and the '+' in the second one. The '-' indicates to turn off the specified type of processing, in this case "replacements". The '+' indicates to turn the specified type of processing back on. The trailing `noEmit` is so that this markup itself does not get written to the target file (which is almost always the desired behavior). If you need the correct syntax for other file extensions, let me know, I can provide the necessary prefix to you.

**Comment by aronblum** [comment]
Hi @seancpeters,

Thank you so much for your help! The "//-:replacements:noEmit" comments did the trick for the using statements. I came across this: [https://github.com/dotnet/templating/wiki/Post-Action-Registry#run-script](url) for a possible way to fix my references. I have written a Powershell script which works, but I am now trying to figure out how to pass through the project name being supplied as a parameter to the script through the postActions section below:

```json
{
  "author": "ablum",
  "classifications": [],
  "description": "template description",
  "name": "SX API Template",
  "defaultName": "SX.API.Name",
  "identity": "SX.API.Template",
  "groupIdentity": "SX.API",
  "tags": {
    "language": "C#",
    "type": "project"
  },
  "shortName": "sxapitemplate",
  "sourceName": "SX.API",
  "guids": [
    "{125C34ED-4903-44F7-83F5-BA68259285C5}",
    "{F887230C-91DD-4583-A33F-4DB355CA1439}",
    "{D9B0CB0A-A67E-47A7-B74B-B148E1CAEC84}",
    "{EA36792D-5425-4F92-806C-453A456C96D3}",
    "{75AD2F2D-F390-4AF5-B10A-714DF8AA212B}"
  ],
  "primaryOutputs": [
    {
      "path": "SX.API\\SX.API.csproj"
    },
    {
      "path": "SX.API.DataAccess\\SX.API.DataAccess.csproj"
    },
    {
      "path": "SX.API.Model\\SX.API.Model.csproj"
    },
    {
      "path": "SX.API.Tests.Integration\\SX.API.Tests.Integration.csproj"
    },
    {
      "path": "SX.API.Tests.Unit\\SX.API.Tests.Unit.csproj"
    }
  ],
  "postActions": [
    {
      "actionId": "3A7C4B45-1F5D-4A30-959A-51B88E82B5D2",
      "args": {
        "executable": "CommonV2Restore.ps1",
        **"args": "(sourceName)"**
      },
      "manualInstructions": [{ 
         "text": "Run 'CommonV2Restore.ps1'" 
         }],
      "continueOnError": true,
      "description ": "This fixes CommonV2 references"
    },
	{
	  "actionId": "210D431B-A78B-4D2F-B762-4ED3E3EA9025",
	  "description": "Restore NuGet packages required by this project.",
	  "manualInstructions": [
		{ "text": "Restore within Visual Studio" }
	  ],
	  "continueOnError": true
	}
  ]
}
```

Do you have any ideas how I can do this? I don't see any documentation or guides as to how to use this. Also, I noticed restoring nuget packages as part of the post build step doesn't seem to work. So I am not sure if there's something wrong there.

Thanks a lot!

**Comment by seancpeters** [comment]
@aronblum - There's currently no way to pass template parameter values to post actions. Run script is generally a last-resort option - and it's a bit fragile because the user would need to have the appropriate asset installed - for your example, powershell - which may not be available on Mac or *Nix, or even on some Windows machines. For run script, the user also has to explicitly opt-in, due the possibility of running arbitrary code.

Visual Studio handles post actions differently than dotnet new - in general each template engine host (VS, dotnet new, VS4Mac, etc.) can choose to handle post actions in their own ways (or not implement them at all). VS doesn't not implement the run-script post action, it would only get run in the CLI.

Also, since Visual Studio does a restore whenever a project is loaded, VS ignores the template restore post action. For your restore not working, is this when you're creating the template in Visual Studio, or by using `dotnet new`? If there problem is that the restore runs, but fails to restore some packages, you'll need to check your package refs & NuGet sources.

For the file rename issue, I'd really recommend going with a change like I outlined above. If you're having trouble making that work, let me know what issues you're encountering and we can work through it more detail.

**Comment by aronblum** [comment]
Hi @seancpeters - It was painful renaming everything so that nothing in my projects are a substring of the sourceName, but it finally all works. Thanks a lot for your help!

One last thing while I am thinking about it; Is there any way to add package restore into the templating with the assumption the template will only be using for VS on Windows? Otherwise it's easy enough to restore after the projects are created.

**Comment by seancpeters** [comment]
@aronblum - glad you got it to work!

VS for Windows will always perform a restore when any project is loaded, including when it creates and loads the generated template content. So you get the restore for free. That restore is why VS on Windows always ignores a template's restore post action - no reason to restore twice. So having a restore post action in your template would not have any effect.

**Comment by aronblum** [comment]
Hey @seancpeters  - No worries!

Last question (a bit off topic), but I am trying create a VSIX from the template project to create something I can push up to a MyGet server and can be added as an extension in VS. Do you have any ideas how I can do that?

**Comment by mlorbetske** [comment]
@phenning may be able to help with the VSIX creation part

**Comment by phenning** [comment]
@aronblum, @sayedihashimi  had recorded a video sometime ago which describes how to get the templates usable in Visual Studio. 

The example shown here uses SideWaffle. 

Even if you don't use SideWaffle, there is good information in there that describes what needs to go into your pkgdef file to install the template and also what needs to go into the .vstemplate file for invoking your template from within Visual Studio.

Here is the link:
https://www.youtube.com/watch?v=5Cb4vOh5Eog

**Comment by mlorbetske** [comment]
It’s been a while since there’s been activity on this issue, is there more to look at here or can this be closed?

**Comment by mlorbetske** [comment]
On second thought, closing this for now, please re-open if there are open items still.
