### ISSUE TITLE
Return code from `dotnet new console` does not include restore result

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/templating#1449]
When attempting a `dotnet new console` on the dotnet\cli daily build, the restore failed and yet the dotnet result returned 0.

See https://github.com/dotnet/cli/issues/8725

**Comment by mlorbetske** [comment]
This is an interesting question - generally we've considered the outcome of the process to be associated with whether or not the content generation itself succeeded (if there's a console app on disk after `dotnet new console`, we consider that success). The individual templates must request that restore happen (via post-actions) but currently there's no way of indicating that a post-action is strictly required for generation to be considered as successful.

Thinking out loud here, but what about a new return code that indicates content generation success but one or more post-actions having failed and an option on post-actions to return the status code of a particular step on failure. It seems like there'll be some issues here (as not all post-actions actually need to invoke external executables), but it seems like an OK place to start thinking about a design. @seancpeters thoughts?

**Comment by seancpeters** [comment]
One concern about changing the return code to reflect the results of the post actions is that it may break backwards compatibility with existing scripted template invocations, but that can probably be dealt with - it's probably a rare case. We could also introduce the change with a major release. Also, until a major release, we could make a flag to opt-in to having the post action results reflect the return code. Or this may not even big a big enough concern to merit worrying about.

All post actions already return a success / failure result which we use when deciding whether to proceed with additional post actions (in conjunction with the ContinueOnError configuration of the post action). This result could be used for the status code determination. 

I like the idea of having an option on post action configurations to indicate whether the result should be reflected on the return status code. It will probably usually be the same as the continue on error configuration, but we should keep them separate, as there will likely be cases where they differ.

One other concern in determining the return code is when the user chooses to opt-out of the post actions that are explicitly opt-in (run script post action). If a user chooses to not run an opt-in post action, would we want the result to be failure? Probably not, but if not running that action causes other post actions to not be run due to the continue on error configuration, we may want to return failure because those didn't run.

For the returned status code in general, perhaps we should come up with a scheme where certain bits are used to indicate the creation result, and other bits indicate other results, e.g. post actions. We may also want to add the results of post actions to the TemplateCreationResult payload.

**Comment by LazarusX** [comment]
While the above discussions focus on whether the return codes during post actions should be propagated, I would like to note that for `dotnet new -i`, restore is a prerequisite step. Currently, if the restore step fails, its return code is not propagated. I don't think that quite make sense since the template is actually not installed successfully (see https://github.com/dotnet/templating/issues/1700)

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by vlada-shubina** [comment]
This is closed with https://github.com/dotnet/templating/pull/3062
- in case post action has `continueOnError: false`, on the error of the post action `dotnet new` will return an error exit code
- in case post action has `continueOnError: true`, on the error of the post action `dotnet new` will return success exit code
- in case the user cancels run script post action, `dotnet new` will return an error exit code
