### ISSUE TITLE
dotnet new -u doesn't work with %USERPROFILE% macro

### ISSUE THREAD

**Issue by scottaddie** [dotnet/templating#1481]
Follow these steps in a PowerShell command window to reproduce:

* Install a project template with the following command. This works.
```console
dotnet new -i %USERPROFILE%\Documents\Templates\GarciaSoftware.WebApiControllerTemplate.CSharp
```
* Try uninstalling this project template with the following command. This **doesn't** work.
```console
dotnet new -u %USERPROFILE%\Documents\Templates\GarciaSoftware.WebApiControllerTemplate.CSharp
```
* Try uninstalling this project template with the following command. This does work.
```console
dotnet new -u C:\Users\<username>\Documents\Templates\GarciaSoftware.WebApiControllerTemplate.CSharp
```

Notice that the template uninstallation doesn't work in a PowerShell command window when using the `%USERPROFILE%` macro. This macro, however, does work for the template installation. I'd expect it to work for uninstall, since it does for install.

It's worth noting that the macro works beautifully for both install and uninstall in cmd.exe.

On my Windows 10 machine, `dotnet --info` returns the following:

```console
.NET Command Line Tools (2.1.300-preview1-008174)

Product Information:
 Version:            2.1.300-preview1-008174
 Commit SHA-1 hash:  b8df89a54f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26216-03
  Build    : f2c3216183d20416568a4bbf5bb7d153e826f153
```

**Comment by mlorbetske** [comment]
I see what's happening, PR coming shortly. For install, the actual path of the thing to install is used & fully resolved by the file system API calls in the engine. For uninstall, the provided string is checked against the configuration to determine which entries to remove, the actual location the thing to uninstall resides at isn't used. In the case of calling from cmd, it seems that the environment variable syntax is being expanded before being passed in, resulting in the string being recorded for the installation request being equivalent to the string the uninstall request is made with. For powershell, since the variable syntax is different, it seems that the installation request
