### ISSUE TITLE
Conditionally require parameter

### ISSUE THREAD

**Issue by hartmannr76** [dotnet/templating#1531]
I've been trying to build a larger template for my teams and one of the "nice to haves" would be conditionally requiring a parameter.

This is brought up in an example in [another issue](https://github.com/dotnet/templating/issues/179#issuecomment-280831830), but wanted to bring it up as a top level topic.

Maybe I'm not doing this right, but right now, there is support for the `isRequired` field, but it is translated [directly as a bool](https://github.com/dotnet/templating/blob/d18c42fe62ca500bfd1afbaa7a6382180dff52ef/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/BaseValueSymbol.cs#L19).

What would be awesome is to evaluate this on the fly:

```
"ParameterA": {
  "type": "parameter",
  "datatype": "bool",
  "defaultValue": "true"
  "isRequired": "false"
},
"ParameterB": {
  "isRequired": "(ParameterA)"
  "type": "parameter",
  "datatype": "string"
}
```
This way, the console output would be something like:
```
dotnet new custom.api 
This works fine since ParameterA is not required!
# or
dotnet new custom.api --ParameterA=true
Mandatory parameter --ParameterB missing for template Api Service Template.
```

**Comment by seancpeters** [comment]
@hartmannr76 - This is a good idea - something we've been discussing off and on for a while. It's not on the immediate agenda, but is definitely in our longer term plans.

**Comment by mlorbetske** [comment]
The biggest issue with making this happen is the delayed evaluation of the symbols (that and the possibility of evaluation loops, but that's not a big blocker) and how to express the conditional requiredness in help. It may be worth making a new symbol type that fits in to the current symbol evaluation phases and/or not using expressions to set the value or exposing the parse structure of conditions so that symbol references can be determined outside of the expression evaluation process (allowing messages like - "Required if {symbol} {equals/does not equal/is greater than/is less than} {value}").

**Comment by donJoseLuis** [comment]
This issue was last touched some years ago.  We are working on a new delivery road map.  Please reopen if this is something we want & we'll properly assess its' priority compared to other work aimed at improving the overall templating UX.

**Comment by mateusdemboski** [comment]
I see that the issue was closed but conditionally require parameter can be so useful in some moments!
Can you guys consider implement it? tkx

**Comment by westdavidr** [comment]
Has this been brought up again? This is something I would really use.

**Comment by vlada-shubina** [comment]
@westdavidr this was delivered in https://github.com/dotnet/templating/issues/4491
