### ISSUE TITLE
Remove cmd file from project after executing

### ISSUE THREAD

**Issue by abhisheksaxena741** [dotnet/templating#1597]
I have one "setup.cmd" file which is executing some operations in it. I works great with post actions.
However, the issue is - when the new project is created, this "setup.cmd" is also gets copied in the project. And i dont want to expose this "setup.cmd" file. 

Please let me know the workaround.

**Comment by mlorbetske** [comment]
I'm inclined to think of this one as "by design" as if we added a "delete file" type action, we'd want to prompt the user for consent or at a very minimum ensure that the target file or directory is part of the generated content.

In this case, the user has already consented to run your script, if it needs to be removed it should likely just include a call to remove itself upon completion. On a personal note, I think leaving the script there for the user to inspect the steps it took is worthwhile, but it may not be meaningful for this use case.

I did some searching and found this post on stack overflow that discusses different approaches for writing self removing batch files: https://stackoverflow.com/a/20333152/1203388

This one's for self removing .sh scripts if that's relevant: https://stackoverflow.com/a/8981233/1203388

Please let us know if these approaches don't meet your needs.

**Comment by abhisheksaxena741** [comment]
@mlorbetske Thanks for the reply. And solution looks good and working when i am executing it as separate "command file(.cmd)" file. 
However, when i am executing with my "setup.cmd" file, then its not working.
Below is the sample file

> @echo off
// nswag commands to generate csharp code
SETLOCAL
SET someOtherProgram=setup.cmd
TASKKILL /IM "%someOtherProgram%"
ECHO "This script will now self-destruct. Please ignore the next error message"
DEL "%~f0"

**Comment by mlorbetske** [comment]
If the call to delete the script didn’t work, I’d add ECHO “%~f0” or turn echoing on in the script so that you can see what it’s trying to do

**Comment by mlorbetske** [comment]
Closing this issue for now as there’s not something related to the templating process here. If there is something, please feel free to re-open
