### ISSUE TITLE
Overwriting and Merging

### ISSUE THREAD

**Issue by jnevins-gcm** [dotnet/templating#1606]
Is there a way to say that a template should not try to overwrite a file at all and just leave it alone if it already exists in the destination directory?

Also, is there a way to say that a template should merge an xml file from the template into an existing file in the destination if it already exists?

**Comment by mlorbetske** [comment]
If you attempt to create a template in a directory where one or more of the template files would conflict with a file that already exists, an error message is displayed indicating that a file (and an indication of which file) would be overwritten and that the `--force` switch needs to be supplied if creation is still desired.

As far as merging content goes, with the current set of operations, no existing content is examined as part of the run. There is an extensibility model that would allow you to create such an operation, you can find the base interface for getting additional operations registered [here](https://github.com/dotnet/templating/blob/d18c42fe62ca500bfd1afbaa7a6382180dff52ef/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/Config/IOperationConfig.cs), and an example of an operation [here](https://github.com/dotnet/templating/blob/d18c42fe62ca500bfd1afbaa7a6382180dff52ef/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/Config/IncludeConfig.cs) with the logic for it [here](https://github.com/dotnet/templating/blob/d18c42fe62ca500bfd1afbaa7a6382180dff52ef/src/Microsoft.TemplateEngine.Core/Operations/Include.cs). Once the operation is created (in a class library targeting .NET Standard 1.6 or lower) and a NuGet package is produced containing it, you should be able to install it with `dotnet new -i {package id} --nuget-source {path to the folder containing your package}`. Once installed, you'll need to configure the operation for use in the file types of interest - this gets a bit more tricky to explain; if you decide to proceed with implementing a custom operation for this purpose, please open a new issue on the topic of consuming a custom component specifically so that it's applicable for everyone & we can help get the configuration setup there.

**Comment by jnevins-gcm** [comment]
Is there a way to silently ignore the file that already exists and not even prompt at all?

**Comment by mlorbetske** [comment]
If the user supplies `--force` on the command line, the check to see if there's existing content is skipped, but there's no way to have that be set in the template, as that decision really belongs with the user
