### ISSUE TITLE
Pass a newline to template variable

### ISSUE THREAD

**Issue by satyajit-behera** [dotnet/templating#1637]
Hi, when I pass a newline character \n in a template variable as below:

templatevariable="\"I am passing this argument \n my newline\"";

it does not write the entire string. It discards the words after \n. 

Can you please look into this. 

This code displays correctly when written to a console application.

Thanks

**Comment by satyajit-behera** [comment]
Thanks @mlorbetske 
I have attached the sample template. It does not accept the \n as a newline and instead add the \n as a simple character to the code. How can I add these 2 variables in multiple lines. 

dotnet new multiline -n MyClass --isMultiline true --myVariables "\"string myVar1; \n string myVar2;\""

[MultilineTemplate.zip](https://github.com/dotnet/templating/files/2261225/MultilineTemplate.zip)

**Comment by mlorbetske** [comment]
I see. It seems the command prompt you're using isn't expanding the escape sequence you've provided (`\n`) - if it had, what you're expecting should work. The template engine itself doesn't expand escape sequences in its arguments. 

In powershell, you could use the following to pass a newline (`` `n`` is the escape sequence for newline in powershell)

```
dotnet new multiline -n MyClass --isMultiline true --myVariables "string myVar1; `n string myVar2;"
```

Having the user input a multiline value seems like it'd generally be problematic due to varied support in the different shells and the user's input likely not matching the formatting of the rest of the template content - have you considered any alternative ways of taking in the value (using separate symbols for each of the lines and using conditions to place the values could be an option if there are a fixed number of expected lines)?

**Comment by satyajit-behera** [comment]
Is there a way we can do this while calling dotnet new?

**Comment by mlorbetske** [comment]
Yes, as mentioned in my second comment, you can use a shell that has an escape sequence that emits a newline character or, as in your reply, you use a different application to pass the argument already containing the newline character.
