### ISSUE TITLE
Parameter alias problem in templates installed from file system

### ISSUE THREAD

**Issue by jMarkP** [dotnet/templating#1662]
I'm developing a new template locally with a parameter symbol I want to specify on the command line. I've found that if you add a parameter symbol to the `template.json` file on disk *after* installing it with `dotnet new -i <PATH>` the parameter appears in the output list, but has no aliases.

Steps to reproduce:

- Create this file:
`./parameter-issue/.template.config/template.json`
````
{
    "$schema": "http://json.schemastore.org/template",
    "author": "Mark Pim",
    "name": "ParameterAliases",
    "shortName": "paramaliases",
    "sourceName": "ParameterAliases"
  }
````
- `dotnet new -i /path/to/parameter-issue`
- Edit the template file:
````
{
    "$schema": "http://json.schemastore.org/template",
    "author": "Mark Pim",
    "name": "ParameterAliases",
    "shortName": "paramaliases",
    "sourceName": "ParameterAliases",
    "symbols": {
        "foo": {
            "type": "parameter",
            "datatype": "string"
        }
      }  
  }
````
- `dotnet new paramaliases -h`
````
Usage: new [options]
...
ParameterAliases
Author: Mark Pim
Options:

          string - Optional
````
- *(Notice no `--foo`)*
- Now `dotnet new -u /path/to/parameter-issue` `dotnet new -i /path/to/parameter-issue`
- `dotnet new paramaliases -h`
````
Usage: new [options]
...
ParameterAliases
Author: Mark Pim
Options:
  -f|--foo
            string - Optional
````

This was surprising behaviour as I'd been previously making changes to the template and source files and rerunning `dotnet new` without uninstalling and reinstalling the template and it had worked, and I'd expect the tool to either not pick up new parameters in the template, or pick them up completely (with aliases). Is this expected behaviour?

## Environment
OS: Windows 10
`dotnet --version`: `2.1.300`

**Comment by mlorbetske** [comment]
Updating source files for the template is expected to work without reinstalling the template. Modifying the template metadata itself, however, does not have the same guarantee. In this particular case, the command line arguments are getting cached on install, but a portion of the template metadata gets reloaded when calling up help (in order to validate any parameters that were passed to it I believe). 

It may be possible for template metadata files to have their last modified time added to the cache & trigger automatic reinstallation if the date differs. @seancpeters thoughts?

**Comment by jMarkP** [comment]
Ah that makes sense. I'm happy to help with a fix if you agree a) it should be fixed and b) that is the correct solution

**Comment by seancpeters** [comment]
Seems reasonable to me, I don't see any real caveats. 

As a workaround, after making changes to the template.json, you can cause the cache to be updated by running:
`dotnet new --debug:rebuildcache`
* Standard Disclaimer: Input flag starting with `--debug:` are not officially supported, and may be removed or change their behavior at any time. (Not that it's likely to happen).

If you're interested in implementing a change for this, I can work with you on the details. The actual cache update can be performed with the existing code that runs when using the --debug:rebuildcache flag, which is found here:
https://github.com/dotnet/templating/blob/4bd80f0577550c7f36867b53d0c074f8f3dcde17/src/Microsoft.TemplateEngine.Edge/Settings/SettingsLoader.cs
...particularly the method RebuildCacheFromSettingsIfNotCurrent.

For this task, the above method probably wants some minor refactoring, moving the actual cache rebuild code into a new method, e.g.: RebuildCacheFromSettings() which does it unconditionally, and only gets called when appropriate. 

The checks for a template.json getting updated and triggering a cache rebuild would need to occur early in the invocation of dotnet new, probably at the same place RebuildCacheFromSettingsIfNotCurrent() is currently called, which is in this file:
https://github.com/dotnet/templating/blob/stabilize/src/Microsoft.TemplateEngine.Cli/New3Command.cs
...in the method ExecuteAsync()

As @mlorbetske mentioned, to facilitate the automatic checking, the file templatecache.json would need to store the timestamps of the various template.json files. One caveat is that this only makes sense for file-based template installs, not zip / nupkg installs. I can get into more details on that as needed.

**Comment by sayedihashimi** [comment]
I think this sounds like a great idea, but we should ensure that it doesn't cause any noticeable perf impact on the end user.

**Comment by seancpeters** [comment]
@sayedihashimi - that is a very good point. The actual cache rebuild happens pretty quick, seems to take < 1 second with the default templates shipped with dotnet new (this can be verified by running `dotnet new --rebuildcache`). The more templates installed, the longer it will take, as each one needs to be dealt with (scales linearly). We'll just have to ensure that the check for the timestamp differences is also quick, which should also scale linearly. 

This does make me think that we might want to have this be an opt-in action, where a user could do a one-time setup indicating they're running in "dev mode", and if not, then this timestamp check is skipped (and possibly other, future enhancements that only make sense in dev type scenarios). I suggest this because the original scenario that began this discussion can only really happen when authoring templates. But "dev mode" might be overkill, these checks will likely be very fast, and only need to be performed on templates installed from files, as opposed to being installed from zips / nupkgs - and that info is directly available in settings.json, which is already needed to do the rescan anyway.

**Comment by mlorbetske** [comment]
From the design Sean and I discussed, non-template authors probably won’t see any difference at all here. It’d just be recording the last modified time (if available) for template.json when we’re already reading it during install & a check on cache load to see if any templates actually have an associated time stamp. On access to a template with a time stamp, the time stamp can be verified & the cache rebuilt if needed - impacting the perf of only that template and only in the case of a change. There’s a possibility of doing something even more tactical and rescanning only that mount point. Default cache build takes less than a second today, so it’s likely not a huge concern either way.

**Comment by sayedihashimi** [comment]
>From the design Sean and I discussed, non-template authors probably won’t see any difference at all here. 

OK, great to hear.

**Comment by jMarkP** [comment]
Thanks all. @seancpeters I've taken a quick look through those areas of the code - it looks from a first glance like we could do this a bit more simply maybe? `RebuildCacheFromSettingsIfNotCurrent()` currently seems to always get called, and starts with:

````
if (IsVersionCurrent && !forceRebuild)
{
    return;
}
````

Could we do something like:

````
IEnumerable<MountPointInfo> mountPointsNeedingRebuild =
  // To be implemented, but includes the IsVersionCurrent 
  //  and forceRebuild check
  FindMountPointsNeedingRebuild(forceRebuild);
 
if (!mountPointsNeedingRebuild.Any())
{
    return;
}
````

If my intuition about the structure of `settings.json` is correct, I guess the `MountPointFactoryId` tells you whether the mount point is a nupkg/zip/files?

I've got a bit of spare time this Friday morning (UK time) so I might try and get a PR together for review if that's OK.

**Comment by seancpeters** [comment]
That sounds about right - but I think if forceRebuild is true, it should always rebuild the cache. That's how the --debug:rebuildcache option is applied.

You're correct about the MountPointFactoryId, we'd only have to look at the mount points that are file based. One thing that may not be intuitive is that nupkg's and zip's are both handled by the same mount point factory / mount point implementation - since nupkg's are just zips with a bit of enforced structure in them.

Definitely feel free to make a PR :)
