### ISSUE TITLE
Why is templating tied to the sdk releases?

### ISSUE THREAD

**Issue by igloo15** [dotnet/templating#1666]
With the introduction of dotnet global tools, why is templating engine not being released as a global tool that can update and grow at a different pace than the dotnet core sdk. 

It feels like a long period of time is between releases of the sdk which is understandable but this tooling doesn't have to wait that long. More frequent releases to get closer to parity with other templating tools in features and fixing bugs would be useful.

Right now with it tied to the sdk and not having it separate as a global tool doesn't make sense.

**Comment by mlorbetske** [comment]
We have prototyped a global tool that would be the backing for dotnet new but still need to figure out how that whole story would fit together. I can’t say for sure yet what the plan is, but we are thinking about this.

**Comment by igloo15** [comment]
Great to hear hopefully this will allow more rapid improvement of the tool. I will keep watch for the changes.

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by bekir-ozturk** [comment]
Hi @igloo15,
 Today, we are doing quarterly releases together with the SDK. Including the previews and the daily builds, we believe we do have a frequent enough cycle to publish our changes to the users. Discussing internally within the team, we have concluded that there wouldn't be much benefit to making the template engine a global tool since we wouldn't be able to release any more frequently than we are releasing today.

 I will close this issue now, but feel free to continue discussing. Let us know if you believe this should be reopened.
Thanks
