### ISSUE TITLE
[Question] Minimum installation for `dotnet new`

### ISSUE THREAD

**Issue by LazarusX** [dotnet/templating#1679]
Our project depends on the awesome `dotnet new` command to scaffold projects, and building happens elsewhere. However, looks like the command requires installing the entire .NET Core SDK which is huge plus its dependencies.

Is there a minimum installation for the `dotnet new` command to only serve the scaffolding task?

**Comment by LazarusX** [comment]
(Sorry for hitting the enter button to soon. Please see my updated issue description)

**Comment by seancpeters** [comment]
We don't currently package a release of dotnet new outside of the SDK. But you could pull down the repo and build it locally. There are a couple differences, the most important being that to use a build of this repo, run the command `dotnet new3 ...` instead of `dotnet new`. The other difference is that the list of initially installed templates are different - new3 has only a subset of the templates available by default with new. But the additional templates can be installed as needed.

If you go this route, I can help you get any templates installed that aren't initially available.

**Comment by LazarusX** [comment]
Thanks!

I think we will stick with the SDK release, but would be excited if there is a lighter one.
