### ISSUE TITLE
Add ability to show and choose templates that are not installed locally

### ISSUE THREAD

**Issue by AndrewBrianHall** [dotnet/templating#1680]
For .NET Core 3.0, ASP.NET Core wants to ability to have templates that are never installed locally (due to various dependencies that are difficult to keep up to date) but appear as options for dotnet new and then use a cloud copy when chosen.

**Comment by sayedihashimi** [comment]
Please keep me posted if you add this ability to VS(Windows). I'd like to add it to VSMac at the same time if possible.

**Comment by mlorbetske** [comment]
This would be an engine feature and would apply to the CLI, so this would be a new drop of the NuGet packages

**Comment by hacst** [comment]
It would be great if this was also something that can be easily used with private nuget servers. The current workflow for using private templates inside a company feels quite clunky to me.

For comparison in the maven/java world the "equivalent" would be maven archetypes. There you configure an archetype repository in a central config once. This allows maven to automatically pick up all templates (aka archetypes) and versions when it comes to searching and selecting a template. No explicit local installation or updates required. No need to explicitely re-state feeds with every invocation. Having the same convenience with dotnet new would be very handy.

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by KathleenDollard** [comment]
It's been a while since this issue has had any comments. Are folks still interested? 

One of several issues in doing this is that a NuGet package may contain numerous templates. Thus, the command would have to include the package Id and the template name (maybe dropping the second if there is only one template). And we'd have to manage help for this scenario, and it would be slow. 

How does this relate to managing private servers? Is it just that if you are managing a private server you really want to ensure that people are using the version of the template you have on your server? 

Is the actual goal here to ensure users do not use an out of date template?

**Comment by hacst** [comment]
Definitely still interested. The use case for sourcing from a private server are purely company internal templates for new services and libraries.

The goal would be to solve both the discovery as well as the update problematic. Users currently cannot discover private templates using normal tooling and if they manually installed a template in the past they are not made aware of updated versions the next time they instantiate the template.

Not installing the template and instead being able to discover the current one in the repository sounded like it could solve both of these problems.

**Comment by baronfel** [comment]
Checking in here - currently we
* check for updated nuget package versions when a template from a nuget package is instanciated
* supply the `dotnet new --update-check` command (and in .NET 7 the `dotnet new update --check-only` command) to allow users to see if there are updates (optionally can apply them automatically with `dotnet new --update-apply` (and in .NET 7 `dotnet new update`)

These both work off of the configured NuGet sources, so a properly-configured NuGet.config should allow for updates from private servers.

The remaining request seems to be for automated or semi-automated install of a template package if instanciating a package :
* that's not installed
* that's known to be in a template package that's available

This is doable for template packages that live on nuget.org, and something like this (npx-style download + run) is something I've wanted to do for a while.  The gap is for having this same experience with private NuGet feeds. @vlada-shubina to support that, we'd probably have to be able to index the private feed (perhaps locally via a direct user command?) and select/merge the indexes with the larger nuget.org index?

**Comment by vlada-shubina** [comment]
This issue seems to raise several points.

-  update for packages from private feeds
This was already addressed and fixed in .NET 6. Checking for update from private NuGet feeds are now supported. It might be slightly complicated in case NuGet feed needs `interactive` authentication as the check for update will fail on template instantiation, however interactive mode is supported with `update` and `update --check` (formerly `--update-check`).

- ability to run templates without installation 
We have a separate issue for that: https://github.com/dotnet/templating/issues/3418
Let me know if we need a separate feature when template will be installed on first run - I would like to create the separate issue for it and close this one.

**Comment by vlada-shubina** [comment]
Closing in favor of https://github.com/dotnet/templating/issues/3418. Please follow this issue if you are interested in running templates that are not installed locally.
