### ISSUE TITLE
Support for multiple templates in a single repo

### ISSUE THREAD

**Issue by janaka** [dotnet/templating#1693]
We would like to be able to have a single runnable repo with multiple templates for optional add-ins. 

We'll have a template for a minimal working app, as a ASP.NET Core backend only app. A developer can spin up a new app with just some Web APIs from this. Say this is an `Add` and `Subtract` API, no database dependencies or client side app.

Another developer wants to spin up a service with a backend + react frontend.

Given the backend code is the same, catering for both these scenarios from a single repo would be we don't end up with code drift and simplifies template code updating effort.

**Comment by seancpeters** [comment]
@janaka:

In general, the originating source of the template content doesn't matter, it's how the templates get packaged which matters. Depending on how different all the scenarios are, one way to do this would be to have only 1 template with a lot of conditions so that with certain input(s), the correct content is generated. As an example, the template named `mvc` which ships with dotnet new allows creation of a project with or without auth. This is the same template used to create `ASP.NET Core WebApplication` | `Web Application (Model-View-Controller)` projects in Visual Studio. The source for this template can be found here: https://github.com/aspnet/Templating/tree/master/src/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-CSharp

Alternately, multiple templates could be created from the same source project, each one authored & packaged so that only the desired content is produced for each template.

As a minimal example, consider a source project with 3 .cs files:
- Program.cs
- Foo.cs
- Bar.cs
...and a Project.csproj file

And these 6 template-based project creation scenarios from that source:
- Everything - include all 3 files
- Program.cs only
- Program.cs & Foo.cs
- Program.cs & Bar.cs
- Foo.cs
- Bar.cs

For each of these, Program.cs would need appropriate conditions to only reference Foo and/or Bar, as appropriate. Similarly, Project.csproj would need to have template conditional statements to only include the appropriate pieces. Alternately there could be separate .csproj files for each desired template.

There is currently no way to directly share content among the templates in a template pack. So
to use an approach like this, you'd still need a template.json for each template being created, and the appropriate content files would need to be packaged with eaeh template. 

But, if there are pieces of template.json configuration that need to be shared among the various templates, it is possible to set things up so those pieces don't need to be duplicated in multiple template.json files. There is an optional section of the template.json format called `additionalConfigFiles`. The key is a top-level element and the value is an array of additional .json files which will get merged with template.json before processing. Using this, each of the templates could have a template.json containing the configuration specific to their respective templates, and also contain an appropriate `additionalConfigFiles` list. During the template packaging process, the common configuration file(s) would need to get copied to the content of the templates that need them, into the relative locations specified in each template.json's `additionalConfigFiles`.

**Comment by janaka** [comment]
@seancpeters thanks for sharing those options.

**Comment by janaka** [comment]
@mlorbetske potentually yes.

Though being able to have multiple template.json files on a repo and generate templates for each would be simpler I feel.

**Comment by mlorbetske** [comment]
It is possible to have multiple template.json files in the same repo and generate template content for each (we even do that in this repo here https://github.com/dotnet/templating/tree/stabilize/template_feed).

If the templates need to share files between them, it's possible to customize the [sources](https://github.com/dotnet/templating/wiki/Reference-for-template.json#source-definition) using the `source` and `target` properties to indicate where the files should come from and where they should be placed to things that wouldn't be included in the template by default.

**Comment by janaka** [comment]
Will close this issue while we try those ^ suggestions. Thanks.
