### ISSUE TITLE
Template ASP.NET Core web app (Model-View-Controller) could not be created

### ISSUE THREAD

**Issue by prasadraavi** [dotnet/templating#1708]
Hi Friends, 

I am new to dotnet core. I am trying to install dotnet core web app mvc template on my windows 10 home version but unable to do it. Could someone help me in understanding what is that missing and how to fix this issue. 

![dotnet core web app template issue](https://user-images.githubusercontent.com/9433003/48992184-8a0a0d80-f15c-11e8-8733-542cc2f618de.png)

Thank You.
Prasad Raavi

**Comment by seancpeters** [comment]
@prasadraavi - It appears that your problem is happening because of write permissions on your file system. When running `dotnet new [template name]`, the content is placed in the current directory, unless an output path is given with the `--output [output path]` (or equivalently `-o [output path]`). From the screenshot above, you're running `dotnet new mvc` from `c:\`. If you change directories to a location when you have write permissions, this error should stop happening. Similarly, specifying a directory with write permissions via the -o flag should accomplish the same thing. For example: `dotnet new mvc -o c:\temp\test_mvc\` (assuming you have write permissions there).

**Comment by prasadraavi** [comment]
Thank you mlorbetske. I got it.
