### ISSUE TITLE
Combine parameters

### ISSUE THREAD

**Issue by DenisPimenov** [dotnet/templating#1721]
Is it possible as now to combine multiple parameters?
Example case :
```
{  
   "symbols":{  
      "name":{  
         "type":"parameter",
         "defaultValue":"Service",
         "replaces":"_App",
         "dataType":"string",
         "fileRename":"_App"
      },
      "createdate":{  
         "type":"generated",
         "generator":"now",
         "parameters":{  
            "format":"MM/dd/yyyy"
         },
         "replaces":"01/01/1999"
      },
      "fullname":{  
         //--combine name with createdate
      }
   }
}

**Comment by seancpeters** [comment]
This is not currently possible, but I like the idea in general. 

For combining the parameter values, we'd have to define what type of combinations are valid. For example concatenating the values, possibly with a specified separator would be the most straightforward thing to do. Is this what you had in mind?

**Comment by seancpeters** [comment]
I agree, a new generated symbol type would be the correct way to do this. I like the name "concat", or possibly "join". I think we should have an optional configuration option on the symbol definition, to specify a string literal to use as a separator between the symbol values - in the same way String.Join() works. It could be added to the config like this:
```
{
  "fullname" : {
         "type":"generated",
         "generator":"concat",
         "parameters":{  
            "symbols" : ["$name", "any string value", "$createdate",....]
         },
         "separator": "-"   // optional, default is empty string.
  }
}
```

If you want to make a pull request, that would be great! The implementations of https://github.com/dotnet/templating/blob/stabilize/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/Macros/IMacro.cs in this repo are all pretty all similar to each other, and can be used as examples.

My only concern is in the "symbols" section allowing both string literals, and references to other symbols. There would need to be some logic so that if one of the entries in the "symbols" array cannot be resolved as a symbol, it would be used as a string literal, otherwise the value of the named symbol would be used. I think that would be ok, the only problem would be if a template author wanted to use a string literal that is also a symbol name. But there are ways around that problem, such as defining a "constant" symbol for the string literal value. If it becomes a problem, in the future we can extend the symbol definition to something like this:
```
{
  "fullname" : {
         "type":"generated",
         "generator":"concat",
         "parameters":{  
            "symbols" : [
               { "type": "symbol", "value": <symbol name> },
               { "type": "literal", "value": <any string value> },
               ...
            ]
         }
  }
}
```
But that can be done in the future if needed. The way you proposed should be fine :)

**Comment by DenisPimenov** [comment]
Yes I agree to add the separator option and I like the name "join". In my example, I tried to resolve string constants and parameter references by adding the $ character. But if you think that there may be problems I can try to implement your grammar. I watched other macros and I will try to make a pull request

**Comment by seancpeters** [comment]
The `$` would work, but it would be inconsistant with other configuration definitions. But it's an interesting idea, I'll give it some thought.
