### ISSUE TITLE
Usability of 'dotnet new'

### ISSUE THREAD

**Issue by livarcocc** [dotnet/templating#1750]
@matkoch commented on [Sun Jan 27 2019](https://github.com/dotnet/cli/issues/10665)

The usage experience with `dotnet new` is honestly a bit painful when working locally with custom templates. Specifically, I would like to ask for:

- having the opportunity to uninstall templates by short name (I think that's unique)
- being able to see a version in the list of installed templates
- getting a _clear_ notification, whether a template was installed or uninstalled, instead of printing all available templates

**Comment by livarcocc** [comment]
cc @kathleendollard

**Comment by mlorbetske** [comment]
Hi @matkoch

For the first item, short name or name are intentionally not unique, they are used as a beginning disambiguator for which set of content to use. Consider the short name console - there's a template for the 1.0/1.1 targeting flavor of console, 2.0, 2.1, 2.2 and 3.0, each is a different template in a different package, multiple can be installed at the same time and they collapse into a single display template (as determined by groupId) and are addressable by the short name of at least one of the individual templates. Each one of these comes in a separate package (console happens to ship in the same package as class library), and install happens at the package (or directory) level, not on a template by template basis. These things combine to make something like `dotnet new -u console` very ambiguous - should it remove just the default console or everything that exists in any group addressable by the name console? Should it remove the package that delivered it (which would remove class library as well) or just that template? If you update the package, should it somehow prevent console from coming back or allow it? What's the process for getting sub-package/directory content back once uninstalled?

For the second, version in terms of individual templates is also one of those things that seems like a straightforward proposition but really is not. Version may not apply at all (at least not in a meaningful way) to templates if installed from a disk location, network share, or (eventually) a git repo. Even in the installation via package case, multiple packages at multiple versions can contribute to the same "display template", displaying all that information could be quite verbose & we often get complaints about the list mode overrunning the console buffer already. That's not to say that the current design for the list view must be adhered to, but if it's not wide like it is now, it'll likely need to convert to being long & more entries in a long list make the list less useful. There's a possibility of listing all the contributing templates' source/version (if applicable) information in detailed help for an individual template - similar to how we present provenance information in the new Web Application project dialog.

For the third, I wholeheartedly agree. having better visibility in to what happened during installation is something that should be improved. We should indicate whether we've switched to "component scan" mode (which often trips people up - packages containing DLLs get scanned for extensions to the engine rather than for templates), we should list the installed templates after the fact, we should display the set of template.json files (or, given that alternate engines can be used behind the engine, whatever the marker is for being considered a template candidate). We should provide hints about how to use the trace switches if something does go wrong.

One of the "all up" experience improvements we've been considering is to offer a site that can be launched from the command line that gives a more graphical view in to things. For example, finding packages available for installation would be visible there, the template list, their provenance (source, author, version if applicable, etc.) and possibly an experience for instantiating the templates or generating the scripts to do so. With a more rich view, it's much easier to expose things like this - maybe even along with options to suppress individual templates, set preferences (default language being a relatively common ask), etc.

If the first two items are addressed either by the explanation or the direction we're thinking, I'd like to close this issue and concentrate on the third, tracking it in a separate issue to allow any thread attached to the issue to be focused on a single topic. Please let us know what your thoughts are.

**Comment by mlorbetske** [comment]
#1706 can be used to track including provenance information in detailed help for a template
#1655 can be used for installation experience improvements

**Comment by KathleenDollard** [comment]
@mlorbetske 

Thanks for the detailed explanations. 

1) I agree that installing or uninstalling should be at a package level. There might be more work to consider around providing insight into what package a template is from or allowing users/organizations to hide or otherwise tune the templates displayed. 

2) I'd like to talk more about this - at least so I understand it. It's confusing for customers to select the right template, and I don't think an experience of global.json for the purpose of template version only makes sense. I understand that there aren't easy answers on this. 

3) I would really like richer experiences for all of our (potentially) NuGet driven experiences to feel unified - tools, templates, and probably packages. So I'd like to talk more about this and your thoughts on delivering a browser experience.

**Comment by maartenba** [comment]
One example I encountered today:

1) Install any new template
2) Run `dotnet new -u` and get back a list of installed templates, including `Microsoft.Azure.WebJobs.ProjectTemplates`!
3) Run `dotnet new -u Microsoft.Azure.WebJobs.ProjectTemplates`, get back `Could not find something to uninstall called 'Microsoft.Azure.WebJobs.ProjectTemplates'.`
4) Try it with the name, e.g. `dotnet new -u AzureFunctions`, same error.
5) Try it with the short name, e.g. `dotnet new -u func`, same error.
6) Browse through `%APPDATA`, find the template, remove it. Uninstall worked!

So wholly agree with @livarcocc here, uninstall is a bit of a pain.

**Comment by kierenj** [comment]
I'm trying to do the same - develop local templates - and I've found it pretty difficult so far.

First, when I install from a local path, I get a "usage" output, and list of templates.  It seems the template is installed, but why no message, "Template X successfully installed"?

I can also install any folder - `dotnet new -i .`, which automatically searches for subfolders and installs templates - but again, without indicating what's actually happened.  It just prints the "usage" (suggesting to me that I made a mistake) and lists all installed templates.  I have to scroll up through loads of stuff to see if there was any output, and then... there wasn't.  It's a bit surprising.

Then when I want to uninstall.  I can't use the short name, but importantly, nor can I use the same path I used to install.  E.g.: `dotnet -i ./MyTemplate/content` seems to install, then `dotnet -u ./Template/content` *fails* saying it can't find anything to uninstall.  I need to use the full canonical path?

I've raised https://github.com/dotnet/docs/issues/12002 in case these are just documentation issues ?

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by donJoseLuis** [comment]
Tracking the individual issues called out in this one...

- #2338 uninstall templates by short name
- #2337 ability to see a version in the list of installed templates 
- #1706 can be used to track including provenance information in detailed help for a template
- #1655 can be used for installation experience improvements

Moving forward we'll track one item per issue & close bulk issues, respectively
