### ISSUE TITLE
Please add template to the Wiki

### ISSUE THREAD

**Issue by sharpninja** [dotnet/templating#1770]
I've created a template for adding xUnit test classes to nuget.  It's package name is GatewayProgrammingSchool.xUnit.CSharp.  It's repository https://github.com/gatewayprogrammingschool/xUnit.Template

If there's a more formal way to submit this I'd like to know.

Thanks!

**Comment by mlorbetske** [comment]
That's a good question as to how to submit templates for inclusion on the wiki, since we've changed things to not allow general editing of the wiki, this is the first request we've gotten. @AngelosP any thoughts?

In the meantime, if you could post a snippet of the markdown with text that'd make it fit with the other entries in the wiki, we can get it included.

**Comment by sharpninja** [comment]
| [xUnit Test Template](https://github.com/gatewayprogrammingschool/xUnit.Template) - Adds a xUnit test file to an existing test project. | `dotnet new -i GatewayProgrammingSchool.xUnit.CSharp`|

**Comment by mlorbetske** [comment]
I've added the template to the wiki, thanks!
