### ISSUE TITLE
Nuget packages in VSIX for the new template engine

### ISSUE THREAD

**Issue by jlchavez** [dotnet/templating#1774]
In the old template engine we could include as assets the nuget packages so that the included nupkg wouldn't be downloaded from the web making it slower for the template to be complete.

Currently I've developed a startup toolkit for asp .net core that make building complete apps faster, and it includes 10 packages that if small it would be better that they don't require to be online to start working.

In the old templeting engine the wizard would pull them from the vsix, but since the new templating uses this path. Is there a workaround code sample or a way to include them?

Thanks

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by grinrag** [comment]
@jlchavez as I understand this is VS only related issue. We are going to create an issue in the VS bug tracker. I will update this issue with the result as I get feedback. Probably this is not P1 for the VS roadmap.

**Comment by grinrag** [comment]
@phenning Phil, do you know who can help with this issue?

**Comment by phenning** [comment]
I couldn't find the opened issue.I I opened another VS internal back log item.

**Comment by vlada-shubina** [comment]
@phenning could you please share the public link to ADO task to this issue for tracking? thank you

**Comment by phenning** [comment]
Not public, but the investigation is work-item 1330799 in AzDO.

For reference, here is the link to the documentation for the packages and VSIX mentionedf:
https://docs.microsoft.com/en-us/nuget/visual-studio-extensibility/visual-studio-templates

To be candid, We haven't made much progress on this simply due to the way restore currently works for .NET Core templates, and due to other priorities.

In the .NET template engine based templates package references are made directly in the project file. We would need instead to have packages installed via a post action. We currently do  have a post action to add package references implemented in Visual Studio, but it only supports the non repository based NuGet API. We could add a property to the post action which indicates that the package should be installed from a package repository, along with the package id of the target VSIX's packages. 

Alternatively, or additionally we could could also support the "template package repository" approach desribed in the link where you would ship the nupkgs inside the template nupkg. Since this would be a template package based feature, and not confined to VSIX - it would be good for the CLI to also support this particular feature. 

@jlchavez, Have you seen the new feature in NPD which allows you to surface your templates directly in the new project dialog without the need of creating stub vstemplate files, but instead installable via dotnet new? Is the packages repository in VSIX still relevant to you, given that feature, or would a template repository approach better serve you?

**Comment by bekir-ozturk** [comment]
I will close this issue as it is not directly related to template engine. Please feel free to discuss further under this thread.
