### ISSUE TITLE
Help on Custom Operations...and everything else...

### ISSUE THREAD

**Issue by andrekiba** [dotnet/templating#1814]
Is there a reliable way to find at least necessary informations about anything related to templates??? After some years it's unbelivable this lack...
Trying to find even the smallest thing it's a tremendous effort.
About custom operations here 
["Runnable Project" Templates](https://github.com/dotnet/templating/wiki/%22Runnable-Project%22-Templates#configuration)
I can find
``	
//#if (A)
		// comment related to the 'if' content
		default content // also appropriate if A is true
	////#elseif (B)
		//// comment related to the 'elseif' content
		//content for when B is true and A is false
	////#else
		// comment related to the 'else' content
		// content for when both A & B are false
	//#endif
``
But what is A?? Can I calculate it using symbols defined in the `template.json`??

**Comment by mlorbetske** [comment]
In this case `A` is a symbol defined in `template.json`, that's correct. If you have specific scenarios that you'd like to see better documentation for, it'd help us to mention specifically what they are so that we can put those together.

The resources we currently have available as far as documentation goes are linked from here https://github.com/dotnet/templating/wiki#template-authoring with a bunch of samples available here https://github.com/dotnet/dotnet-template-samples
