### ISSUE TITLE
.Net new with multiple template versions

### ISSUE THREAD

**Issue by satyajit-behera** [dotnet/templating#1861]
Dotnet new --install {package name} is essential for creating any file or project using .NET new command in the .NET core.

During the process, only one version of the template is installed.

Can we maintain multiple instances of templates for the same package?

Thanks

**Comment by mlorbetske** [comment]
Are you looking to install multiple versions of the same NuGet package specifically or to have multiple versions of a template's content available to the user?

**Comment by satyajit-behera** [comment]
Thanks @mlorbetske 
Looking at multiple version of same nuget package gets installed as different version of the template and I can access both with a version number parameter.

**Comment by mlorbetske** [comment]
This is interesting, but you should consider package versions to be a linear upgrade path, just like referencing libraries via NuGet. Ex. If you have Newtonsoft.Json version 9.0.1 installed and upgrade to Newtonsoft.Json version 10.0.2, there isn't an expectation that you can still use the 9.0.1 behaviors, nor that 9.0.1 remains somehow.

The pattern for side-by-side, version-linked template content has been to include the package versions in the package id. Ex. `MyTemplate.1.0` version 1.1 and `MyTemplate.2.0` version 1.1 where, since the package IDs are different, it makes sense to have them installed together and allows bug fixes to be performed in either the 1.0 content or the 2.0 content without having to worry about which order the user installs the templates in.
