### ISSUE TITLE
Surfacing templating engine via Web API

### ISSUE THREAD

**Issue by hananiel** [dotnet/templating#1878]
I am working on making this templating engine available via a webapi/website ui. As an example of how this could be helpful - see start.spring.io . Then this template engine could be useful outside the cli, namely other editors such as Rider, Code, VS, and even curl. The core abstractions and implementations appear to be focussed on a CLI host. Do you have any plans to support a web host ? Specifically publishing the existing projects as nugets + help with error reporting (instead of Reporter tied to ansiconsole  should be a logger) . Any pointers would be helpful.

**Comment by seancpeters** [comment]
This project is actually already used in Visual Studio, and I think Rider too. The repo is slightly misleading because it contains 2 somewhat distinct features, namely:
- The CLI host (assembly Microsoft.TemplateEngine.Cli)
- The core template engine (all other assemblies)

We've kept the CLI host implementation separate from the core engine so that it can be integrated with other "hosts". A "host" is an implementation of ITemplateEngineHost:
https://github.com/dotnet/templating/blob/master/src/Microsoft.TemplateEngine.Abstractions/ITemplateEngineHost.cs

The DefaultTemplateEngineHost is one implementation of the ITemplateEngineHost interface, and can be used as an example:
https://github.com/dotnet/templating/blob/master/src/Microsoft.TemplateEngine.Utils/DefaultTemplateEngineHost.cs

The CLI specifically used the ExtendedTemplateEngineHost:
https://github.com/dotnet/templating/blob/master/src/Microsoft.TemplateEngine.Cli/ExtendedTemplateEngineHost.cs
The CLI used New3Command.cs to process console inputs and interact with the host, and make calls to invoke templates, install templates, uninstall templates, show help, etc. Just keep in mind that everything in the Microsoft.TemplateEngine.Cli assembly is specific to the cli host, but can be used to demonstrate interactions with the core engine. 

The assembly Microsoft.TemplateEngine.Edge is meant to be for public facing API calls - you shouldn't have to make direct calls into other assemblies.

I can go into more details on specific points, but hopefully this will help get you started.

**Comment by hananiel** [comment]
@seancpeters thank you so much! I didn't realize this about Microsoft.TemplateEngine.Edge  - thats helpful!

**Comment by seancpeters** [comment]
One more thing I thought of that might be useful: The Microsoft.TemplateEngine.Abstractions assembly is also public facing, and only contains interfaces - but you may have figured that out already :)

**Comment by hananiel** [comment]
@seancpeters I am not finding these either in nuget.org or myget ... can you point me to the public feed for Microsoft.TemplateEngine.Abstractions and Microsoft.TemplateEngine.Abstractions. I only see the beta feed ...

**Comment by seancpeters** [comment]
You'll need to build from source at this point. There is some documentation on the repo main page, but it may be a bit outdated. If so, let me know - it'll be a good reason for me to update it :)

**Comment by hananiel** [comment]
@seancpeters As I made progress with this effort, I found a couple of sticking points with Microsoft.TemplateEngine.Edge project. It looks like the [SettingsLoader ]( https://github.com/dotnet/templating/blob/master/src/Microsoft.TemplateEngine.Edge/Settings/SettingsLoader.cs) doesn't create cache from settings when cache is not present. Something in the dotnetcli seems to be doing this. So I wanted to override this behavior but although this class is public, it has a lot of dependencies on internal fields and methods that make it hard to override the behavior: Factory Guids, [ComponentManager](https://github.com/dotnet/templating/blob/master/src/Microsoft.TemplateEngine.Edge/Settings/ComponentManager.cs), [TemplateCache](https://github.com/dotnet/templating/blob/master/src/Microsoft.TemplateEngine.Edge/Settings/TemplateCache.cs) is public, but WriteTemplateCaches is internal (used by SettingsLoader), MountPointManager is internal. Would you consider making some of these interfaces public/protected or have other ways to reuse functionality by overriding parts of it. Alternatively, if there is a way to force creating locale specific and generic caches from settings without doing all this please let me know - I couldn't figure it out.

**Comment by hananiel** [comment]
Also, I was having trouble with the performance of this project running inside a Web Context.  This call new TemplateCreator(EnvSettings).InstantiateAsync(...) seems to be taking over a second. Is there any way to make it faster?

**Comment by donJoseLuis** [comment]
@hananiel greetings.  Created #2329 to track the perf issue you mentioned above.
