### ISSUE TITLE
Source-build patch removal for templating

### ISSUE THREAD

**Issue by crummel** [dotnet/templating#1927]
Source-build has some patches that we are currently applying to your repo.  This issue tracks removing the patches.  These patches can be found at https://github.com/dotnet/source-build/tree/release/3.0/patches/templating.

Patches that have the responsibility "Repo" and the Disposition "Incorporate" are patches that we believe are valid source-build fixes that should be moved into your repo.  Please let us know if these don't seem like good patches.  Any changes with the responsibility "source-build" is something that we plan to keep going forward or integrate in another way - please also let us know if you think there may be problems with those patches.

Patch name | Type | Disposition | Responsibility | Notes
-- | -- | -- | -- | --
templating/0001-Don-t-build-test-projects-when-building-from-source.patch | ProjRemoval | Incorporate | Repo |  
templating/0002-Use-source-built-version-of-Newtonsoft.Json.patch | Flow | Incorporate | Repo |

**Comment by crummel** [comment]
cc @mlorbetske

**Comment by seancpeters** [comment]
@crummel 
I'm working on applying these patches to dotnet/templating. There's a couple issues:

From the link provided, there are only two patches available - as opposed to the 3 listed here. They're:
- 0001-Don-t-build-test-projects-when-building-from-source.patch 
- 0002-Use-source-built-version-of-Newtonsoft.Json.patch

0001 matches what's listed here. 
0002 from the link is named like 0003 here.

I can successfully build locally with 0001 applied, but with 0002, I cannot build locally since NewtonsoftJsonPackageVersion is not defined. If I define NewtonsoftJsonPackageVersion in /Directory.Build.props I can build locally. Just not sure how that's going to affect source build.

**Comment by crummel** [comment]
Thanks for taking a look at this!  I updated the initial comment.  What we're aiming for would be:
- NewtonsoftJsonPackageVersion is defaulted to whatever you want.
- You use Arcade-style version imports (in which case Arcade takes care of this) or import `DotNetPackageVersionPropsPath` if it exists after setting your defaults.  Then we'll reset that property.

Does that seem reasonable?

**Comment by seancpeters** [comment]
Sounds good to me. I've made a PR for the changes here #1956 
I'll flow it to master too.

**Comment by vijayrkn** [comment]
https://github.com/dotnet/templating/pull/1956/files
