### ISSUE TITLE
Support for verbosity in dotnet new

### ISSUE THREAD

**Issue by isaacrlevin** [dotnet/templating#1948]
I came across this comment in a [closed issue](https://github.com/dotnet/cli/issues/9165#issuecomment-385222281) where this has been talked about, but I see value in having more verbose logging for `dotnet new`. Here is my scenario. I want to be able to create custom templates with configuration based on options (think --auth for dotnet new webapp). If something goes wrong in the project generation, I have no idea why. It would be nice to see some logs for the transform piece. More than happy to even do a PR if I got some guidance on where to look.

**Comment by seancpeters** [comment]
An effort was begun with #1305 to provide more detailed logging of problems with template authoring and installation. That PR setup the mechanisms for reporting these types of issues, but it only actually added messaging for a very limited subset of the possible problems that could occur. Adding additional trace messaging using this type of logging is probably the easiest way to make the output more verbose for these situations. Additional traces could be added for other situations if desired. A --verbose flag could be implemented that turns on logging for all the tracers.

The aforementioned PR adds two flags, which are meant to log as follows:
--trace:install - for logging issues that prevent installation from occuring.
--trace:authoring - for logging issues during content generation which are caused by a misconfigured template.

Note: Any flags for dotnet new that contain a colon ":" are considered experimental and are subject to change / removal at any time. These are generally the same set of flags that are not offered in the help display when running `dotnet new -h`.

**Comment by PiotrJustyna** [comment]
Yeah, having the same problem using the following command:

```
dotnet new --trace:install --trace:authoring -i ./bin/Release/PiotrJustyna.ConsoleTemplate.CSharp.0.1.0.nupkg
```

output:

```
piotr@EMEA00304 OrleansTemplatePractice % dotnet new --trace:install --trace:authoring -i ./bin/Release/PiotrJustyna.ConsoleTemplate.CSharp.0.1.0.nupkg
Usage: new [options]

Options:
  -h, --help          Displays help for this command.
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
...
```

So no idea really what is going on 🤔 The `nupkg` file does get generated, though, and the `dotnet pack` command does not complain.

**Comment by bozturkMSFT** [comment]
Logging is being overhauled soon, which will also include an option for verbose logging. Please track #3152.
