### ISSUE TITLE
Renaming or removing part of a template path installed by the file system breaks dotnet new

### ISSUE THREAD

**Issue by Thraka** [dotnet/templating#1955]
If you install a template by file path, say `c:\mytemplates\template1` and then later delete `mytemplates` or even rename it, the `dotnew new` command breaks completely. You cannot uninstall, install, or do anything with that command. You also don't see the real problem of what template file is causing the problem. 

😮 

```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   c:\program files\dotnet\sdk\3.0.100-preview6-012264\

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf
```

**Comment by seancpeters** [comment]
Installing a template pack from a file-based source (as opposed to a zip or nupkg) is a developer scenario that isn't fully supported. When dotnet new installs a template pack, if it's from a zip or nupkg, the content is copied into the dotnet new configuration hive directory, and used from there. 

On windows, the location is under: `%USERPROFILE%\.templateengine\dotnetcli\<version>\packages/`

On *nix, the location is under ~/.templateengine/dotnetcli/<version>/packages/

For file based template pack installs, the content remains in its original location, so that changes are available without re-installing.

As a workaround to get your install working again, you could first try:
`dotnet new --debug:rebuildcache`
This will attempt to recreate your configuration hive, but there are situations it also cannot recover from, if the hive is sufficiently broken.

If that doesn't work, a more drastic command is:
`dotnet new --debug:reinit`
This resets your install to its initial state, which means that any templates not installed in-box will be lost.

Disclaimer: Any input flag beginning with `--debug:` is not fully supported and subject to change at anytime - which is why they're not publicly documented.

That said, I agree that the experience you're describing is far from ideal. Dotnet new should be able to recover from a situation like this, without causing any problem to the user. At this point it does not, but should be fixed to deal with this sort of thing.

**Comment by donJoseLuis** [comment]
sounds like a bad UX.
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by vlada-shubina** [comment]
This is fixed in https://github.com/dotnet/templating/issues/2630. Closing the item as duplicate.
