### ISSUE TITLE
Web template requires a bower dependency

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/templating#196]
As described on dotnet/cli#4076. Using this issue to track the work.

/cc @mlorbetske

**Comment by danroth27** [comment]
@sayedihashimi Do we have a plan or resolution for this for RTM? I'd like to be able to update our ASP.NET Core tutorials to stop using Yeoman and use `dotnet new` instead

**Comment by sayedihashimi** [comment]
@danroth27
>@sayedihashimi Do we have a plan or resolution for this for RTM? I'd like to be able to update our ASP.NET Core tutorials to stop using Yeoman and use dotnet new instead

In the next release we will have `dotnet new3` which has all the templates you're interested in. After the next release `dotnet new3` will replace `dotnet new`.

Does that answer your question?

**Comment by danroth27** [comment]
As long as there is a `dotnet new` starting point that lets me get started with ASP.NET Core without having to install Node or Bower then I'm happy. I'm looking for something like the ASP.NET Core Empty template in VS.

**Comment by blackdwarf** [comment]
@danroth27 you always ask the hard questions. 😉 It should be `dotnet new3 web`. Use `dotnet new3 -l` to list out all the templates.

**Comment by sayedihashimi** [comment]
Yes as @blackdwarf mentioned you can use `dotnet new3` and later that will become `dotnet new`. We have some good help so try the following:

 - `dotnet new3 --help`
 - `dotnet new3 web --help`

**Comment by seancpeters** [comment]
One caveat with using `dotnet new3 -l` is that it will only list the templates that are valid in the context of your current directory. For example if you're in a directory that already contains a project, then only item templates will be listed. The way around that problem is to use the -all flag, which ignores the context. Both of the following do the same thing:
- dotnet new3 -all
- dotnet new3 -l -all

This bites me semi-regularly, and I'm probably not alone in that regard.

**Comment by blackdwarf** [comment]
@seancpeters what is this..."item template" magic you speak of? And more to the point, does it have different restrictions w.r.t what it

**Comment by seancpeters** [comment]
@blackdwarf There isn't really much difference between project & item templates. They're processed identically to one another. The conceptual difference is that an item template can't stand alone, whereas a project template can. Currently, the only thing we have that would be considered an item template is the nugetconfig template, which adds a very bare-bones nuget.config file to the target directory.

**Comment by blackdwarf** [comment]
How much work would there be to add, if needed, a SLN file item template?

Thanks
Z

Sent from my tricorder

________________________________

**Comment by seancpeters** [comment]
Probably very little, if you just want something basic. Check out the nugetconfig template (there's hardly anything there):
https://github.com/dotnet/templating/tree/master/template_feed/Microsoft.DotNet.Common.ItemTemplates/content

**Comment by blackdwarf** [comment]
@seancpeters why thank you, this is pretty good. And item templates to not fail instantiation if there is an existing item in the dir, correct?

**Comment by seancpeters** [comment]
Correct, if I understand you right. We don't currently have a restrictions on where you can instantiate an item template.

**Comment by mlorbetske** [comment]
The comments on what happens when trying to make or list project templates when there's already a project in the target directory are now being tracked as #198 

As for the actual bower dependency - `new3` (soon to be `new`) templates ship the expected packages in the template itself (like VS does) so that bower isn't required to run immediately after creation. With that in mind, should this issue remain open (as the issue is not present in new3 templates)? If we want to start a discussion on the default client package manager used, we should probably move the discussion to aspnet/templates

@blackdwarf @danroth27

**Comment by blackdwarf** [comment]
@mlorbetske I would close it. I just used it to inquire with @seancpeters about the item templates, since I noticed something weird happening when I'm in the folder and I do `new3 -l`. 😄

**Comment by mlorbetske** [comment]
sweet, thanks!
