### ISSUE TITLE
Update incorrect NuGet packaging documentation

### ISSUE THREAD

**Issue by fabriciomurta** [dotnet/templating#2135]
While I written this report I was using:
- Windows 10 10.0.17763.737
- DotNet CLI 3.0.100
- Visual Studio Community 16.3.1

In the [Custom templates for dotnet new](https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates#packing-a-template-into-a-nuget-package-nupkg-file) article, linked from the first link [in the _Template Authoring_ section of the main wiki page](https://github.com/dotnet/templating/wiki#template-authoring), it suggests .nuspec should *not* be required if using the `dotnet pack` command, and that files included as `content` in the project would be bundled in the target NuGet package.

This is not true at least with a simple set up. First, it requires the **package.nuspec** file, contrary to what I understand by reading the section in the article pointed above. By consequence, the files added to the NuGet package should be listed in the `<Files>` XML tag in the **package.nuspec** file.

To reproduce the issue, just follow the article, adding the mentioned sections to the **.csproj** file, and a simple template project, also including its files as 'content' to the package building project, then try running `dotnet pack` in the latter project's folder.

Notice there shouldn't be any **package.nuspec** file at that point, expecting `dotnet pack` to build the info from the project file.

**Comment by donJoseLuis** [comment]
We should verify the repro & updated documentation accordingly.

**Comment by vlada-shubina** [comment]
@fabriciomurta 
I have followed the steps as explained in [Custom templates for dotnet new ](https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates#packing-a-template-into-a-nuget-package-nupkg-file)  article and was able to create the package without **package.nuspec** file. However, I was using dotnet 3.1.401.

If this issue is still occurs, could you please try it when using dotnet 3.1? 
If this doesn't help, could you please provide the source code of the project you are trying to pack and exact error message that you encounter. 

Thank you.

**Comment by fabriciomurta** [comment]
Sorry for the silence guys! I will try to re-check this later this week

**Comment by vlada-shubina** [comment]
@fabriciomurta I'm closing this issue due to no feedback. Please feel free to reopen if you still have any issues related to it. Thank you.
