### ISSUE TITLE
Is it possible to create a template which modifies existing files?

### ISSUE THREAD

**Issue by Adrian10988** [dotnet/templating#2148]
EG:
I execute some template to
- modify an existing controller by adding a new endpoint
- modify an existing domain class to add an entry method which the controller can use
- modify an existing repository to add an entry method with the domain can use

I understand that I can use template for anything greenfield, but I would like to add functionality for brown field development. I find myself consistently writing the same boiler plate code when it comes to simple logic / reads and that is just setting up the data flow pipeline through all the solution layers.

**Comment by jzabroski** [comment]
You used to be able to do this with .NET Framework and nuget packages like WebExtensionEx (this is how logging frameworks like Elmah grew to huge popularity among novice ASP.NET engineers because it was so easy), but due to the move to [Microsoft.Extensions.DependencyInjection](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection?view=dotnet-plat-ext-3.0) interfaces, the ability to install "magic nuget packages" that transform a file is no longer supported, as there is no way to know where to glue-in the ambient context.

**Comment by MaxCrank** [comment]
We're trying to resolve similar problem. Adding new service to nginx configs, docker-compose yamls etc. would be extremely useful in addition to plain service sources and a reference to a new project for existing solution...

**Comment by KathleenDollard** [comment]
The current templating engine is not well suited for this and I think this would be best done in conjunction with an option to have generative/reentrant style of templating. That would be a large undertaking, so we can either close this or put it on the backlog to track what we would include if we ever include an alternate template structure.

**Comment by YuliiaKovalova** [comment]
Closing. We do not plan to support modifying existing files except for some dedicated cases which are already supported by post actions.
