### ISSUE TITLE
Force parameters to be specified if another is specified

### ISSUE THREAD

**Issue by vb-software** [dotnet/templating#2173]
Documentation doesn't indicate this is already a feature but it would be nice if specifying one parameter forces other parameters to required only if that initial parameter is used.

**Comment by donJoseLuis** [comment]
Let's add a page in the Wiki describing the behavior of related parameters.
Minimum content:
1. description
1. example

**Comment by vlada-shubina** [comment]
The issue suggests a new feature which doesn't exist yet. Moved to Template Engine backlog.

**Comment by KathleenDollard** [comment]
The simplest way to do this would be to require a change to System.CommandLine, since it will be our parser and it does not support this. That would allow the parser to do the validation. We could probably also do it in a post-validation step, but lets see whether we have other post validation needs after we move to the new parser. 

I do not want to do this unless we find a way to express this clearly in help. Having this dependency without being able to communicate it does not seem helpful. OTOH, this problem is real. 

Let's leave this on the backlog and review after we have the new parser in place.

**Comment by KathleenDollard** [comment]
If this affects your templates, let us know. I have the ASP.NET Auth templates in mind on this, but if there are other scenarios, please add them.

**Comment by vlada-shubina** [comment]
Related use case is: https://github.com/dotnet/templating/issues/4102 - disable parameter B is parameter A is not specified.

**Comment by sayedihashimi** [comment]
If we do this work we should coordinate to ensure that we can properly support this in VS.
