### ISSUE TITLE
Complex Conditionals Fail if not Wrapped in Parentheses

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/templating#2209]
This conditional fails to execute correctly and you end up with the code below in the final project output:

```c#
#if Foo || Bar
// Some code
#endif

#if !Foo
// Some code
#endif

```

This successfully removes the code if the condition fails:

```c#
#if (Foo || Bar)
// Some code
#endif

#if (!Foo)
// Some code
#endif
```

This only seems to be the case with complex conditionals. A simple conditional succeeds with or without brackets:

```c#
#if Foo
// Some code
#endif

#if (Foo)
// Some code
#endif
```

The reason I'd like this fixed is that it's very easy to get this wrong and I also get warnings from C# analzers about unnecessary paranthesis.

**Comment by jzabroski** [comment]
@RehanSaeed How do you reproduce this issue?  It looks like you're complaining about a C# language standard specification, not dotnet templating.

Also, did you mean "Complex Conditionals Fail if not Wrapped in **_Parentheses_**"?

**Comment by RehanSaeed** [comment]
I don't think it's related to just `.cs` files but affects all templating engine `if` statements in other file types too. I would have thought `if` statements should work with or without parenthesis.

Reproducing it is as simple as adding the above conditions in a file.

Fixed the title.

**Comment by grinrag** [comment]
I can reproduce the issue. Set the low priority, since we have a workaround, but I agree that it should be able to process complex conditionals w/o wrapping them into parentheses. I will take a look, as I get more time for this issue.

**Comment by AR-May** [comment]
I will leave a comment in order to save progress on the issue, as I spent some time investigating this question. 

Currently, we look at the first token after the `if` token that we recognize as a valid expression. And this becomes the expression to evaluate (if it is true or false) and then process the if-endif section accordingly. That may be some single bool value/variable or some complex expression in parentheses. 

The reason for this is that one could have such code in a template:
```
    <!--#if (Foo || Bar) -->
    <None Include="Foo.cs" />
    <!--#endif -->
```
There is no special field in template.json for specifying the token for the end of expression (like "-->" in the example above) unlike it is done for `if`, `elseif`, `endif` etc. So, this is apparently the way to define where is the end of the expression.

So, I suppose that we cannot fix this without losing backward compatibility if we are speaking about the default behavior. I suggest discussing with PM about adding functionality for this in the future as a non-default option (adding some options for template.json for this perhaps?).

**Comment by jzabroski** [comment]
@AR-May I didn't understand .  There are no tests in this project that cover wrapping #if expressions in a comment.  Is that part of the specification?

**Comment by AR-May** [comment]
@jzabroski  There is a test in `Microsoft.TemplateEngine.Cli.UnitTests.KitchenSinkTests` that covers this situation. This is actually how I found the problematic template. I implemented reading the expression until the end of the line and this test failed.

  [Here](https://github.com/dotnet/templating/blob/master/test/Microsoft.TemplateEngine.EndToEndTestHarness/test_templates/ConfigurationKitchenSink/Company.ClassLibrary1.csproj) is the problematic template.

**Comment by KathleenDollard** [comment]
The problem here, and @AR-May can correct me if I am wrong, is that we don't really understand the context where we are doing replacements. While @jzabroski 's request is immensely reasonable we don't have a good handle that we are in C# code, nor a full parser to understand the code. And, even if we solve those, we have a super high bar for breaking changes in templates, even if the new break is due to an old bug (similar to the Roslyn bar for breaking changes). 

@jzabroski can you work around this by setting the parens check to info or not having treat warnings as errors turned on? 

I don't think you can ignore the warning at just this location because the #pragma would then be in your generated code.

**Comment by jzabroski** [comment]
Hi @KathleenDollard

 I came away realizing I didn't know how to interpret the kitchen sink test, so I just gave up on this project.  I just realized that dotnet/templating wasn't worth my time supporting as part of my open source projects.  Hope that doesn't sound harsh - it's just the value play isn't there for me to push this tech.  I would have thought the Overview https://github.com/dotnet/templating#overview was enough to understand how to use the language, but after seeing the kitchen sink, I realized it was more complicated than what I wanted.  I originally wanted something less complicated than T4 Text Templates, and close to yeoman but better than yeoman.  You can see my request for a "better yeoman" here: https://github.com/dotnet/templating/issues/2140

**Comment by KathleenDollard** [comment]
To protect backward compatibility we are not going to fix this. 

I am adding it to our open issue on template validation. This is a bit of a nasty gotcha, but changing this in a random SDK upgrade does not seem a good idea since it will change template behavior. 

@jzabroski I agree that it would be nice if we were a template language not replacements via JSON. I don't think we fit your scenario. The good part of CLI templates is that if you have a simple project with certain types of replacements, you can ensure your project is valid _before_ running your template. This allows the workflow - Make the project you want, make the template, tweak it. It does not enable the scenario you are looking for.
