### ISSUE TITLE
Template Wishlist

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/templating#233]
Moved here on behalf of @piotrpMSFT from dotnet/cli#4675

This issue tracks asks for additional CLI Templates that folks would like to have access to. Think of these as Up For Grabs work items for folks that want to build CLI templates. Let us know if you're interested in taking one of these on!

 - [ ] Starter Solution - a library, a test project, and a sln file to match #3503
 - [ ] Self-contained deployment with a Dockerfile
 - [ ] Console application with a Dockerfile
 - [ ] Extensibility with a target
- [ ] CLI tool template? 
 - [x] ASP.NET Web API
- [x] Empty solution file (item template)
- [x] Global.json
- [ ] Dockerfile and vscode launch/task configs

**Comment by blackdwarf** [comment]
From @clentfort

A "ASP.NET Web API" template for `dotnet new` would be nice. :)

**Comment by mlorbetske** [comment]
@blackdwarf @clentfort a Web API template is available for C# in `dotnet new` as of yesterday

**Comment by piotrpMSFT** [comment]
:D

**Comment by enricosada** [comment]
- global.json ?

**Comment by mlorbetske** [comment]
Added global.json and Dockerfile and vscode launch/task configs  to the list

**Comment by dasMulli** [comment]
I'd have a global.json template at https://github.com/dasMulli/global.json-template/tree/master/DasMulli.Templates.GlobalJson/content/GlobalJson

If there is interest, i could contribute it to the item templates in this repository.

**Comment by mlorbetske** [comment]
@davidfowl global.json item template for dotnet new - thoughts?

**Comment by enricosada** [comment]
yes, please.

Is really useful to teach how to create templates (`dotnet new template`).
Awesome if this contains also props to show things (how to add a prop, how to add a conditional in source file, or csproj/fsproj).
So more a guidance, but working

**Comment by akerd** [comment]
With release of dotnet core 2.0.0 preview1 I read that VB.Net is now supported. It would be nice have a basic template that support that language too.

**Comment by anweiss** [comment]
Any word on the Docker support?

**Comment by mlorbetske** [comment]
I know @glennc is looking in to adding docker support

**Comment by patridge** [comment]
@blackdwarf Out of curiosity, what exactly are folks looking for out of the "CLI tool template?" wishlist item in the first comment?

**Comment by radu-matei** [comment]
Just cross-posting from #823 - an option to have `.gitignore` per project or per solution would be extremely helpful.

**Comment by grinrag** [comment]
After approval from PM, we will decide which new templates from that list we can implement. Also, we will open a separate issue for every template for better progress tracking.
Consider the following list during the discussion:

- [ ]  Starter Solution - a library, a test project, and a sln file to match #3503
- [ ] Self-contained deployment with a Dockerfile
- [ ] Console application with a Dockerfile
- [ ] Dockerfile and vscode launch/task configs

**Comment by bekir-ozturk** [comment]
@KathleenDollard Can you check the list and see which ones to plan?

**Comment by baronfel** [comment]
* Docker 
  * This would be a prime one to do when we have contextual information about the project being scaffolded into (e.g. after the constraints work in https://github.com/dotnet/templating/issues/3107 is done). We need information about the output path of a project, its TFM, etc in order to correctly generate a dockerfile.
  
* CLI Tool template
  * this is a good idea, but we'd need to coordinate with the SDK team about their recommendations for tool authors. Right now a tool is just a console application with two additional MSBuild properties set, and that's not difficult enough to justify the effort in my opinion.
    *  `<PackAsTool>true</PackAsTool>`
    * `<ToolCommandName>CUSTOM NAME GOES HERE</ToolCommandName>`

* Starter solution
  * I see this one as a _lot_ of work. What we do in templates has a _lot_ of weight, and if we choose some practice or a particular tool in this template, we put our thumb on the scale in a pretty major way. There are a number of whole-solution templates that seem to be filling this need well already.

* VS Code tasks/launch configurations
  * VS Code provides extensibility points for generating tasks and debug launch configurations that can be 'ejected' by a user into task.json/launch.json files.  This generative capability means they can be updated as your projects change without having to track them in a file.  Therefore we should not make a template specifically for these items, and instead should request updates to Omnisharp to provide these tasks and launch configs.  I've implemented this for Ionide for F# and it works well, and the practice is common across other ecosystems like node/golang/etc.

* Extensibility
  * Assuming this means MSBuild here. I agree strongly with this, and will likely push for the MSBuild team to create/maintain author a template. We've only recently started documenting Task/Target guidelines (in the final stages of some updates to that work right now, as a matter of fact), but then it would be a good thing to create a template that captures that guidance.
