### ISSUE TITLE
`dotnet new --list` table truncated when run in subprocess

### ISSUE THREAD

**Issue by Deadpikle** [dotnet/templating#2360]
### Problem description

Some software that I am building calls `dotnet` as a subprocess (in C# land, a `Process`) without a console window. It parses the output and shows it to the user. However, with .NET 5, the template names are truncated.

To see this easily on macOS, install the .NET 5 preview SDK (preview 1+), then run `dotnet new --list | cat` in a terminal. You wouldn't normally run the output through `cat`, of course, but any other process/pipeline that gets the data is going to be truncated. You can also see an example more akin to what I am doing here: https://github.com/Deadpikle/DotnetProcessTesting (see the flag at the top of `Main`).

### Problem Cause

PR #2270 (fix of #2062) made tables look really nice on smaller console windows. It handles redirection if the output is redirected (https://github.com/dotnet/templating/blob/master/src/Microsoft.TemplateEngine.Utils/EngineEnvironmentSettings.cs#L109), but still acts as though the console is small (https://github.com/dotnet/templating/blob/master/src/Microsoft.TemplateEngine.Utils/EngineEnvironmentSettings.cs#L105).

As a console user, I really like data being easily read if I don't care about full template names! As a console user, I don't like having to re-run commands to see full template names if I do care about seeing the whole thing (resize window -> re-run command). As a developer wanting to use `dotnet` from another program, I'd rather see full template names than truncated ones.

### Possible solutions

1. Increase the [`DefaultBufferWidth`](https://github.com/dotnet/templating/blob/master/src/Microsoft.TemplateEngine.Utils/EngineEnvironmentSettings.cs#L105) to a much larger number so that redirected output gets all full template names. --- have tested this locally and it works to fix my specific use case. It is probably the easiest "quick fix" here.
2. Add a command line parameter that can be used to avoid any data truncation. (The benefit of this option is, as a user, I could always use this flag and simply make my console window bigger to see all data rather than having to re-run the command in a bigger window.)
3. Change [this line of code](https://github.com/dotnet/templating/blob/master/src/Microsoft.TemplateEngine.Cli/HelpAndUsage/HelpForTemplateResolution.cs#L201) from `.DefineColumn(t => t.Name, LocalizableStrings.Templates, shrinkIfNeeded: true)` to `.DefineColumn(t => t.Name, LocalizableStrings.Templates, shrinkIfNeeded: !Console.IsOutputRedirected)` ---- tried this locally and it didn't seem to work for some reason (data wasn't truncated when output not redirected)
4. Otherwise fix it so that redirected output is not truncated. `dotnet` doesn't know how the data will be used, so my opinion is that it's best to not truncate data so that whatever software is calling `dotnet` will have all data available.
5. ???

### Context

I previously posted about this here: https://github.com/dotnet/sdk/issues/10885 -- but the issue belonged here and not the .NET SDK repo. I apologize for posting in the wrong place.

**Comment by grinrag** [comment]
@Deadpikle thank you very much for such a detailed description of the problem and provided possible solutions.
Another problem which I see here - if you redirect the output to a file, it's also truncated.

About provided solutions:

1.  OK, I agree that 80 chars by default it's not enough for most cases. But it's a workaround and someone can add a new template with even longer `Template` name.

2. I believe the default behavior should be to **NOT** truncate output, and do this only if a command-line parameter was provided. That is option 4.

3. Probably instead of `!Console.IsOutputRedirected`, we can try look at `ProcessStartInfo` for `Process.GetCurrentProcess()`. I didn't check it yet.

4. see 2

5. We can add a command-line option to list output fields, something like `--fields shortname, language`, could be useful

Feel free to make a PR and we can continue the discussion there. Otherwise, I can take a look, when I get time for this issue.

**Comment by Deadpikle** [comment]
@grinrag  I've opened up a PR for recommendation numbers 2 and 4 with a new command line parameter here: #2364

I like the idea that you listed in 5., but that feels like a new feature rather than a fix, so I decided not to tackle that.

Thanks for your time and reply.

**Comment by grinrag** [comment]
@Deadpikle thank you very much for the PR. Since there were several people involved in the discussion of #2270, I have to contact them and ask why they made that decision. Also, I have to take a look at other dotnet CLI tools, the behavior should be homogeneous across all of them.

To unblock you, we can merge only the first part, increasing the default output width. This change is harmless.

**Comment by grinrag** [comment]
The main issue with running `dotnet new` as a subprocess and table truncating is resolved with PR #2365. 
I am closing it now.
