### ISSUE TITLE
When SDK template library no longer return a template with OptionalWorkload=true, it should be removed

### ISSUE THREAD

**Issue by grinrag** [dotnet/templating#2427]
Implement the mechanism (just reuse the mechanism for the `--uninstall` option) to automatically remove all the templates marked with `OptionalWorkload=true` and which are not in the list returned by API

**Comment by ladipro** [comment]
@grinrag just to clarify, we want to be removing optional workload templates from the cache when a) the new API no longer returns them or b) when they don't exist on the filesystem anymore?

The title suggests a) but the initial comment talks about b). Since we'll have to be calling the API on each startup and cross-checking its results with the cache anyways, it looks like b) should be cheap to implement but I'll defer to you. Thanks!

**Comment by grinrag** [comment]
@ladipro, thank you. I edited the issue description.
