### ISSUE TITLE
No 'launchSettings.json` in web related templates

### ISSUE THREAD

**Issue by peterblazejewicz** [dotnet/templating#248]
I could be missing information about RC content state, but the aspnet/Templates project has `launchSettings.json` template content, while the `dotnet new3` tool does not.
I've used VS 2017RC to generate content, the `dotnet new` does now have them (while still shipping `web.config`).

Thanks!

**Comment by mlorbetske** [comment]
Launch settings are used by Visual Studio only & are generated on first open of the project. Similarly, in self host models, the web.config file is not required, publish will automatically generate a web.config when publishing & a web.config file template has been added if it needs customization.

The main motivation behind removing web.config is the confusion that we're seeing around people wanting to continue modifying appSettings in that file instead of appSettings.json

cc @sayedihashimi

**Comment by peterblazejewicz** [comment]
So should I remove entire `Properties/launchSettings.json` from templates content?
What about Azure? Is the Kudu service feasable of generating required files?

**Comment by mlorbetske** [comment]
It's my understanding is that the `launchsettings.json` file is read only by Visual Studio for determining what the available actions for `F5`, so Kudu or other build systems shouldn't need to generate it. Let's wait for @sayedihashimi to confirm though.
