### ISSUE TITLE
Customers with 16.7 who installed 5.0 preview 8 ended up with 5.0 templates

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/templating#2615]
The 5.0 SDK requires 16.8 so we won't load in 16.7.  The 5.0 preview 8 templates targeted 5.0 by default so some customers saw an experience where they would new a project, target 5.0 by default, and couldn't build. This was resolved when we changed the templates to target 3.1 mostly as a side-effect.

In the future for 6.0, 6.0 will be the default for all templates and so this will be an issue with 16.11 and 6.0 previews.

See https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1238005

**Comment by marcpopMSFT** [comment]
Basically, there needs to be a minVS version like there is for the SDK or templates need to respect the sdk version.

**Comment by vlada-shubina** [comment]
@marcpopMSFT 
I'm not sure if we need to fix something for it in template engine. 
Host is responsible for template resolution, thus Visual Studio host in this case should filter unsupported templates out. 
Imo it makes sense that VS host:
- do not show templates with unsupported frameworks at all
- for templates that have a mix of supported and unsupported frameworks, only show supported frameworks

@phenning  what do you think?

**Comment by phenning** [comment]
@marcpopMSFT We also have a chicken and egg problem here. Since the SDK and VS are decoupled, there exists a desire to use an underdevelopment version of the SDK on current versions of the product. This is generally enabled by the use preview SDKs flag in Visual Studio. So at the time of the earlier preview releases, templates coming from the 5.0 SDK were supported by 16.7.  

We are currently looking into adding a supported hosts/min hosts metadata for the host file schema for Visual Studio which should be able to alleviate issues like this in the future.

**Comment by marcpopMSFT** [comment]
Sounds reasonable.  Having a support host data would allow VS to choose which templates to load.

**Comment by vlada-shubina** [comment]
Moved to VS backlog: https://devdiv.visualstudio.com/DevDiv/_queries/edit/1253901
