### ISSUE TITLE
What is the initial setup for `dotnet new3 mvc --auth Individual` SQLite database?

### ISSUE THREAD

**Issue by peterblazejewicz** [dotnet/templating#266]
I've used to advice to call `dotnet ef database update` before running MVC project with SQLite datbase, but that is no longer a case with new dotnet tooling. 
What is the supposed UX scenario to get MVC with authorization backed by SQLite to run?

> dotnet run
Hosting environment: Production
Content root path: /Users/piotrblazejewicz/development
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {9dc754fa-11c3-436b-9235-b123c11babb3} may be persisted to storage in unencrypted form.
fail: Microsoft.EntityFrameworkCore.Query.RelationalQueryCompilationContextFactory[1]
      An exception occurred in the database while iterating the results of a query.
      Microsoft.Data.Sqlite.SqliteException: SQLite Error 1: 'no such table: AspNetUsers'.
         at Microsoft.Data.Sqlite.Interop.MarshalEx.ThrowExceptionForRC(Int32 rc, Sqlite3Handle db)

https://github.com/aspnet/EntityFramework/issues/7538
https://github.com/aspnet/EntityFramework/issues/7358

**Comment by mlorbetske** [comment]
@peterblazejewicz that's still the correct command to call, but you'll need to reference the CLI tool (Microsoft.EntityFrameworkCore.Tools.DotNet) to run that command.

We should look at including this reference in the templates - there was originally some concern about creating a cyclic dependency for the CLI by including them, but that seems to have been resolved.

Perhaps we should also run the initial migration on the SQLite database included in that template so that it works without having to do apply migrations first.

**Comment by peterblazejewicz** [comment]
> but you'll need to reference the CLI tool (Microsoft.EntityFrameworkCore.Tools.DotNet) to run that command.

> We should look at including this reference in the templates - there was originally some concern about creating a cyclic dependency for the CLI by including them, but that seems to have been resolved.

The template already contains reference to tools:
```
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.0.0-msbuild3-final" />
```
https://github.com/dotnet/templating/blob/master/template_feed/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-CSharp/Company.WebApplication1.csproj#L26

I've used that template.

This cannot be marked ` VS2017 Post-RTW` as one should be able to run SQLite or in-memory-store out-of-the box at the time of the release I think. I should be able to run this sample right now

@rowanmiller can you help with this?

**Comment by mlorbetske** [comment]
@peterblazejewicz sorry, I mentioned to wrong package. `Microsoft.EntityFrameworkCore.Tools.DotNet` is what's needed currently - it allows you to apply the initial EF migration to the SQLite database. There's currently also a bug in the template that prevents the database from being copied to output on build - #280 fixes these issues & applies the initial migration to the SQLite database so that immediately after creation you're able to register in the app.

**Comment by rowanmiller** [comment]
Just to add a little more clarity. The `Microsoft.EntityFrameworkCore.Tools` package contains the PowerShell commands that are used within Visual Studio, and is just installed as a usual package reference.

`Microsoft.EntityFrameworkCore.Tools.DotNet` has the .NET CLI commands, and needs to be listed as a `DotNetCliToolReference` in the project.

```
<ItemGroup>
  <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet"
                          Version="1.0.0-msbuild3-final" />
</ItemGroup
```

**Comment by peterblazejewicz** [comment]
OK. Proven to work with just released RC4 bits:
```
dotnet ef database update

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.17
Done.
```

**Comment by sayedihashimi** [comment]
Can we close this?

**Comment by peterblazejewicz** [comment]
@sayedihashimi Yes, with remarks that cli does not warn or point user what to do next in order to get DB sample running correctly. This could be part of docs I think

**Comment by sayedihashimi** [comment]
We should consider adding a post action that instructs the user with those instructions. Reopening.

**Comment by seancpeters** [comment]
This is fixed with the templates in rtw.
