### ISSUE TITLE
How to run template pack tests?

### ISSUE THREAD

**Issue by iTiamo** [dotnet/templating#2660]
I have created my own template pack and am trying to implement tests [according to the documentation.](https://github.com/dotnet/templating/wiki/Testing-your-templates)

I have written my own JSON file to perform these tests, but I couldn't find how to run them? It also isn't mentioned in the documentation.

Any guidance would be helpful.

**Comment by vlada-shubina** [comment]
@iTiamo you can run the tests using [ProjectTestRunner ](https://github.com/dotnet/templating/tree/master/tools/ProjectTestRunner) project locally (test class is Battery.cs)

Unfortunately, the documentation is outdated and these tests are not run in CI anymore. I will fix documentation to reflect this.
Please let me know if you have any other questions, otherwise closing the issue.

**Comment by iTiamo** [comment]
Unfortunate @vlada-shubina. I have updated my code base to run the same tests with xUnit.
