### ISSUE TITLE
Possible to allow both ".gitignore" and "gitignore" as short names for gitignore template?

### ISSUE THREAD

**Issue by jkotalik** [dotnet/templating#2695]
I see myself constantly mistyping the command to add a gitignore to a project.

Would it be possible to allow ".gitignore" as a short name for the gitignore template? Or are multiple shortnames not supported?

**Comment by vlada-shubina** [comment]
@jkotalik thank you for suggestion.
We are hesitant to implement it at the moment, however we might reconsider the decision in case the issue gets more community feedback. 

I will keep the issue open for some tine to see if anyone else is interested in similar features.

**Comment by augustoproiete** [comment]
@vlada-shubina I don't have the specific need that @jkotalik suggested for the alternative .gitignore (but I'm not against it either), I'd be interested in **support for multiple shortnames in general** that I could use in other templates (e.g. that I provide for my projects)

**Comment by DavidKarlas** [comment]
@jkotalik It turns out there is a way to do what you want to do... Its called --alias, its well hidden feature that we new maintainers of project didn't know until now :)
Type:
```
dotnet new gitignore --alias .gitignore
```
Can everything will just work...
I opened issue to document this behavior: https://github.com/dotnet/templating/issues/2731

@augustoproiete subscribe to https://github.com/dotnet/templating/issues/2704 to follow progress on that feature.
