### ISSUE TITLE
Warn against creating nested .NET Core projects

### ISSUE THREAD

**Issue by ladipro** [dotnet/templating#2736]
It is trivially possible to create a broken project hierarchy with `dotnet new`. For example, running this in an empty directory:

```
> dotnet new console
> dotnet new console -n AnotherConsole
```

makes the project created with the first command not buildable:

```
> dotnet build
...
Program.cs(7,21): error CS0017: Program has more than one entry point defined. ...
```

Less contrived examples:
- A webservice in directory `foo` and clients living in its subdirectories `foo\client1`, `foo\client2`.
- A library and test project(s) in its subdirectories.
- ... or any other attempt to nest projects like this.

.NET Core projects by default build all sources in the project directory and all subdirectories, recursively. This makes placing projects in directories that are a direct or indirect parent of one another a really bad idea. However, it is not enforced anywhere, not even documented, as far as I can tell. It leads to all kinds of hard-to-diagnose build errors or even run-time bugs should the top level project be buildable anyways. New .NET developers or developers migrating from .NET Framework might find this surprising and such a negative first impression may put a stain on the platform for them.

I propose that `dotnet new` implements a check for this scenario and warns the user. Yes, it includes walking the entire directory subtree but this is what build is going to do anyways so if it takes a long time and TE detects it, it's still a win which could prevent the user from falling into another pitfall - placing projects in directories with an excessive number of files and getting what looks like build hangs.

But wait, why isn't this implemented in MSBuild?
- Making MSBuild warn against such project structure could be a breaking change and TE, as a tool used predominantly interactively, has arguably higher tolerance to breaking changes. Moreover, nested project files could still be used for a legit purpose and ignoring a one-time TE warning is nicer to the user than having to suppress a warning that would otherwise be spewed every time the project/solution is built.
- The developer may of course get into this situation by moving directories around but that's an explicit and manual action (as opposed to the `dotnet new` magic) so it should be clear that if something stopped working after an action, then undoing said action will fix it.
- Making MSBuild warn against a long-running glob expansion (e.g. ```"**/*.cs"```) is something MSBuild should have, too, and is being looked at separately.

The issue described here exists in Visual Studio as well. I first ran into this by creating a project and solution file on command line and then creating another (nested!) project in VS and adding it to the existing solution. Same as with `dotnet new`, VS didn't give me any hint that what I was doing is wrong. I just got a solution that didn't build and I was scratching my head trying to figure out why.

**Comment by DavidKarlas** [comment]
One way to solve this confusion/issue would be that `dotnet new console` always creates new console project in subfolder with same name as current subfolder, so if user is in folder `C:\Projects\MyNewProject\` and executes `dotnet new console` it would create new project in `C:\Projects\MyNewProject\MyNewProject\MyNewProject.csproj` instead `C:\Projects\MyNewProject\MyNewProject.csproj`.

So it would act same as specifying `-n $CurrentFolderName` if no `-n` is specified.

One of main problems with current way of working is that even as experienced developer if I run `dotnet new console` and later decide I want to add `Library` or `UnitTest` project I need to do following steps:
 1. Create subfolder for current project
 2. Move all content to that subfolder
 3. Run `dotnet new library -n MyLibrary`
 4. Run `dotnet new sln`
 5. Run `dotnet sln add MyNewProject\MyNewProject.csproj`
 6. Run `dotnet sln add MyLibrary\MyLibrary.csproj` 

With solution I'm proposing steps 1,2,4,5 wouldn't be needed.
And probably even 6 could be fixed, by auto adding .csproj to .sln that is in current directory.(CLI needs to add post action for that)

Problem with this solution is... `dotnet build` will fail(same way as it does for `dotnet new console -n hello` today), because current folder doesn't have `.sln` or `.csproj` file in folder for `dotnet build`. But this would be solved by always creating `.sln` file for `dotnet new console` if there is no `.sln` currently present or `dotnet build` checking subfolders, but that is bigger change...

**Comment by vlada-shubina** [comment]
@shanselman could you please review the concern in this issue and the impact it does for the new users?  Is it something that can be improved only via enhancing documentation and tutorials or should we consider fixing it relatively soon in template engine?
Does the solution suggested by @DavidKarlas above make an improvement worth to consider?

Thank you.

cc @KathleenDollard

**Comment by bozturkMSFT** [comment]
After discussing with PM, it was decided that we will not deliver this.
