### ISSUE TITLE
Need to be able to specify dotnet UI language and support localized messages

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/templating#2754]
See https://github.com/dotnet/msbuild/issues/1596#issuecomment-667665304

when I type `dotnet new -i Microsoft.PowerShell.Standard.Module.Template`, there's a first few messages that are printed in local language (in my case, Korean) saying "determining projects to restore". I've tried setting chcp 437, $env:DOTNET_CLI_UI_LANGUAGE = "en-us" and $env:VSLANG=1033 but none of them seem to work.

Reported by @Gnbrkm41

**Comment by DavidKarlas** [comment]
Message about "Determining projects to restore..." is coming NuGet/MSBuild and will be fixed once original bug is fixed
But `dotnet new` indeed doesn't respect any of this, so what needs to happen is this:
https://github.com/dotnet/sdk/blob/52f079f4/src/Cli/dotnet/commands/dotnet-new/NewCommandShim.cs#L84 needs to be changed to `CultureInfo.DefaultThreadCurrentUICulture` because thats what uts set here https://github.com/dotnet/sdk/blob/52f079f4/src/Cli/dotnet/UILanguageOverride.cs#L27

**Comment by DavidKarlas** [comment]
While fixing this, drop `--locale` option to align with all other `dotnet cli` tools... https://github.com/dotnet/templating/blob/c7c62e0b99d4e7574dfa1743e057791a00fd9010/src/Microsoft.TemplateEngine.Cli/New3Command.cs#L510
