### ISSUE TITLE
Translate console and library templates in templates_feed

### ISSUE THREAD

**Issue by DavidKarlas** [dotnet/templating#2821]
Prepare templates https://github.com/dotnet/templating/tree/master/template_feed for localization, send to localization team and update when they send translations back.

**Comment by bozturkMSFT** [comment]
This will need to happen after arcade has the tools to support template localization. That will probably not ready within the timeframe of our localization epic. This is also not actionable for us aside from making sure this isn't forgotten.
I will remove this from localization pipeline and move it to May sprint. Let me know if you think otherwise.

**Comment by vlada-shubina** [comment]
Already done, closing.
