### ISSUE TITLE
Document template resolution process

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#2824]
Create developer reference document explaining template resolution logic and filtering rules applied.

**Comment by DavidKarlas** [comment]
Here is something I started some time ago:


# Template Resolution
This document will explain how template resolution works when user executes `dotnet new console`.

## Filtering templates
First thing that happens for template resolution is that we filter templates. This happens in
[Microsoft.TemplateEngine.Cli.TemplateResolution.TemplateResolver.PerformCoreTemplateQuery](https://github.com/dotnet/templating/blob/467e0b7/src/Microsoft.TemplateEngine.Cli/TemplateResolution/TemplateResolver.cs#L256), that uses following filters:
 * [NameFilter](https://github.com/dotnet/templating/blob/467e0b7/src/Microsoft.TemplateEngine.Edge/Template/WellKnownSearchFilters.cs#L9) which filters with `TemplateName`(so in our scenario `console`) compares to "Name"(`Console Application`) and "Short Name"(`console`).
   * Partial: If template name is not specified or partial string match
   * Exact: If `TemplateName` == "Name" or "Short Name"
   * Mismatch: All other cases
 * [ContextFilter](https://github.com/dotnet/templating/blob/467e0b7/src/Microsoft.TemplateEngine.Edge/Template/WellKnownSearchFilters.cs#L68) which filters with `--type` parameter which can be `item` or `project`, for example `dotnet new web --type item` will create `Web Config` file.
   * null: If `--type` is not specified
   * Exact: If `--type` value matches
   * Mismatch: Otherwise
 * [LanguageFilter](https://github.com/dotnet/templating/blob/467e0b7/src/Microsoft.TemplateEngine.Edge/Template/WellKnownSearchFilters.cs#L99) which filters with `--lang` parameter
   * null: If `--lang` is not specified
   * Exact: If `--lang` value matches
   * Mismatch: Otherwise
 * [BaselineFilter](https://github.com/dotnet/templating/blob/467e0b7/src/Microsoft.TemplateEngine.Edge/Template/WellKnownSearchFilters.cs#L126) which filters with `--baseline` parameter
   * null: If `--baseline` is not specified
   * Exact: If `--baseline` value matches
   * Mismatch: Otherwise
 * [ClassificationsFilter](https://github.com/dotnet/templating/blob/467e0b7/src/Microsoft.TemplateEngine.Edge/Template/WellKnownSearchFilters.cs#L146) which filters with `TemplateName`(so in our scenario `console`) compares to Tags `Common` and `Console`.
   * Exact: If all Classifications have match in `TemplateName`
   * Partial: If some Classifications match `TemplateName`
   * null: If:
     * `TemplateName` is not specified
     * Template.json doesn't have Classifications
     * No matches

This filters can return:
* `Exact`/`Partial`: Only difference between `Exact`/`Partial` is for `NameFilter` result, to remove all templates that don't have `Exact` match if there is any `Exact` match.
* `Mismatch`: This will remove template from consideration regardless of other filters results.
* `null`: This means ignore me, like filter doesn't exist.

We filter list of templates that those who returned `null`, `Exact` or `Partial` for all filters and `dotnetcli.host.json` doesn't have `hidden`=`true`.

We further filter this list to include only templates that have `Exact` matches of `NameFilter` if there are any such template.

## Grouping templates into groups
Once we have list of templates we group them by GroupId.

### Filtering groups by default language

If we have multiple groups we try to apply default language filter in case that filters down to single group, otherwise we return error Ambiguous, and display list of all matching templates to user.

Reason we don't filter by default language eariler is that if we filtered by default language eariler we would drop `dotnet new templateNameWithOnlyF#` and if default was `C#` we wouldn't get this far... Hence do it here only if there are multiple matching goups...

## Selecting template from single group

### Check for Ambiguous Parameter Value inside individual template
First thing that we do we check all templates indiviually and see if any has AmbiguousParameterValue, such example is `-f net` where `netcoreapp1.0` and `netcoreapp1.1` are 2 choices in same template.json.

### Check if template is invokable
Then we do fairily interesting filtering if [template is invokable](https://github.com/dotnet/templating/blob/0ce1628/src/Microsoft.TemplateEngine.Cli/TemplateResolution/TemplateMatchInfoExtensions.cs#L53-L68) that looks like this:
```csharp
x.Kind == MatchKind.Exact
||
    // these locations can have partial or exact matches.
    x.Kind == MatchKind.Partial
    && (x.Location == MatchLocation.Name || x.Location == MatchLocation.ShortName || x.Location == MatchLocation.Classification || x.Location == MatchLocation.Author)
||
    x.Location == MatchLocation.OtherParameter && x.Kind == MatchKind.SingleStartsWith
```

We do this check this late, so we can display error message for invalid parameters like `-f 123` and list possible options, if we filtered before, we couldn't do that.

### Check for Ambiguous Parameter Value inside whole group of templates
Example is `-f net` where `net5.0` and `netcoreapp3.1` are 2 choices in two different template.jsons.

### Picking template with highest Precedence
So now that we have list of valid templates in single group + all parameters matching. This can happen if user doesn't specify `-f net5.0`, so all C# `console` templates are valid... In this scenaior `Precedence` value specified in each template.json file is picked.
