### ISSUE TITLE
Ability to execute some custom code after running the template engine

### ISSUE THREAD

**Issue by fubar-coder** [dotnet/templating#286]
This would allow fetching some data from a remote source and creating additional source files. Related to #234, but not limited to dotnet restore.

**Comment by mlorbetske** [comment]
Hi @fubar-coder, we've intentionally avoided allowing the execution of arbitrary code carried by the template for a variety of reasons (security, cross platform compatibility, different callers running the same actions in different ways). That said, we realize that not everything that one could want to do during template creation will be covered by what we've built in this engine, so we've provided extensibility points to allow customizations (like you see in action in #242) - content authors can create these extensions (we'll be documenting instructions on how to do these sorts of things soon) and provide the `PostActions` section in their template with instructions on how to acquire their extension.

For the particular case of getting some data from a remote source for use in the content generation process (or to add additional files to the output), we're looking at making a general purpose construct out of this (read some data from a source, use it as part of content generation) though we're still hashing out the details of how it would work. We'd love to hear about your use case so we can make sure it's accommodated in that work.

cc @sayedihashimi

**Comment by fubar-coder** [comment]
We have several kind of data sources, including (but not limited to):

- XML files
- ZIP files containing one XML file ([example](https://github.com/dataline-gmbh/HealthInsurance.Germany.ContributionRate/blob/master/test/Dataline.HealthInsurance.Germany.ContributionRate.Tests/Daten/EBSD0-GES_V51_2016_0211.zip?raw=true))
- XLS(X) files
- CSV files
- record-style text files ([example](https://github.com/dataline-gmbh/SocialInsurance.Germany.Messages/blob/release/0.4.0/test/Dataline.SocialInsurance.Germany.Messages.Tests/aager/eaag0001.a15))
- PDF files

I'm glad that we don't have to import Access MDB files any more 😏 .

**Comment by Grinderofl** [comment]
@mlorbetske Could be the second person to request this kind of functionality but perhaps more specific? If I was able to plug my own C# code into the template generation pipeline. Since the templating engine can be used to create valid compiling code, I'd like to be able to say, use Roslyn to edit my created classes dynamically. I was working on https://github.com/grinderofl/tempest prior to discovering dotnet new3 (thanks guys, I think yours is way more promising ;)), which supported exactly that - mainly because the template creator was supposed to write C# anyway. It supports hooking in your own custom transformers into the pipeline, etc. I suppose Tempest was meant as more of a general purpose scaffolding engine than necessarily a templating engine....


So I guess what @fubar-coder is asking for really, is that instead of this being a TEMPLATING ENGINE, maybe, while the name stays the same, the purpose of this project could really be a  PROJECT/SOLUTIno SCAFFOLDING ENGINE? 

Our company has long been interested in seeing if we could somehow decorate dotnet new with our own bells and whistles to add our internal nuget packages, maybe our own startup configuration that builds on top of the default project files, which we wouldn't have to concern us with at that point, because our sources would just come on top of it. 


I understand that arbitrary code execution is not ideal and that in reality the code can do just about anything, but I think an option for this would be to let the user know that "this template is executing its own code. Are you sure you want to allow it?". It's all fine and dandy that you can tell the user to run commands after executing the templates, but if you're working in a digital agency and you have a lot of new projects which all need the exact same setup, it would save a lot of time and be really great if I could automate the whole shabang instead of having to do "dotnet new internalsdk <project>" -> "Thanks for creating new Internal SDK project. Please run 'dotnet internalsdk install <arguments>' to finish installation" -> "cd <project>; dotnet internalsdk install <arguments>". Mind you this would involve having to add your own file accessors, parsers, and savings, all in your custom code.  

Which brings me back to being able to being able to intercept say individual files, and modify them before they get written to disk - as well as add new ones. 

Maybe I need to look at the code first to see how feasible that is... but at least our company would sure love it!

**Comment by mlorbetske** [comment]
@Grinderofl great post & use case - we've got a bunch of the support for this already but there are a few things we've got left to take care of before we start really telling that story well. I'll respond with a more detailed explanation & pointers to the places that one would use to accomplish this a bit later in the day (need to run at the shortly or I'd get all the information together now).

The general push back on arbitrary code is more on the notion of "arbitrary scripts to run" intermixed with template content payload that run after generation has completed. I've been talking with our security folks pretty regularly on this topic & we're working out what the real template installation experience would look like - this would be the point at which we'd indicate that extensions (or whatever name ends up being used) are required to generate the content for a particular template successfully.

**Comment by sayedihashimi** [comment]
I like the idea of allowing execution of arbitrary code because it enables scenarios that we can't really envision or have the resources to support in a first class way.
We do have to be careful here though, and not just from a security perspective. From a security perspective I think we can get things lined up to let the user know that code will execute and have them explicitly agree to it.
The fact that the templates are designed to be consumed by different hosts (i.e. command line, Visual Studio, VS for Mac, VS Code, etc) means that executing code may need to be different based on the end scenario. For example if you had a post action that called `node.exe`, on the command line you'd probably just call `node.exe` that's on the path, but in Visual Studio we can use `node.exe` from the VS install directory or implement the code in a way that doesn't directly call the .exe.

There's a similar feature in NuGet packages, the powershell scripts. The powershell scripts have enabled a lot of cool packages to be created, but I also know that it has caused problems. For example the scripts don't execute outside of VS, and even if they did there is no `$DTE` object so it doesn't work. Also after users create `.ps1` files to fill gaps but when those gaps are filled people don't necessarily migrate to the new first class way but instead keep doing what they are doing.

**Comment by Grinderofl** [comment]
Also on the side of security - when you use stuff like yeoman, you can already execute arbitrary code ;) I would like to argue at this point that since the templates are (I assume?) meant to be used by developers who, if they have any idea what they're doing and have a good reason to be installing templates from "questionable" sources, probably have a reason to trust any code they may run; and if they are novices, they would likely be using **official** template sources which are generally well vouched for and curated against malicious code, as most of them happen to also be open source.

I also think that it's fine if one would have to support all individual platforms that exist, for execution. The template engine would at that point just have to have a mechanism that works out the correct one, provided one exists with said platform.

I'm more than happy to provide additional feedback as well as perhaps try to improve the feature a little once the basic support is there? I have a rather keen interest in scaffolding and template generation, and this project is looking rather good if it gets plenty of extension points!

**Comment by mlorbetske** [comment]
Sorry for the long delay. Here are the different extension points we currently have

Things that participate in the actual generation process (assuming extensions to the [Runnable Project Generator](https://github.com/dotnet/templating/tree/master/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects) - or generally any generator based on our [stream processing core library](https://github.com/dotnet/templating/tree/master/src/Microsoft.TemplateEngine.Core)) implement [IOperation](https://github.com/dotnet/templating/blob/master/src/Microsoft.TemplateEngine.Core.Contracts/IOperation.cs) and are provided by [IOperationProvider](https://github.com/dotnet/templating/blob/master/src/Microsoft.TemplateEngine.Core.Contracts/IOperationProvider.cs) implementations
- [Replacement](https://github.com/dotnet/templating/blob/master/src/Microsoft.TemplateEngine.Core/Operations/Replacement.cs)
- [Conditional](https://github.com/dotnet/templating/blob/master/src/Microsoft.TemplateEngine.Core/Operations/Conditional.cs)
Their usage in the generation process gets wired up through [configuration](https://github.com/dotnet/templating/wiki/%22Runnable-Project%22-Templates#configuration) (see `SpecialCustomOperations`)

For things that run after generation has finished, implementations of [IPostAction](https://github.com/dotnet/templating/blob/master/src/Microsoft.TemplateEngine.Abstractions/IPostAction.cs) are the way to accomplish that.
- [Restore](https://github.com/dotnet/templating/blob/4da0a69b70ac542a6fa87b2892147a26406b6282/src/Microsoft.TemplateEngine.Cli/PostActionProcessors/DotnetRestorePostActionProcessor.cs)
These get hooked up via configuration as well (see the `PostActions` section in the [configuration](https://github.com/dotnet/templating/wiki/%22Runnable-Project%22-Templates#configuration))

Adding an entirely different generator can also be accomplished by implementing [IGenerator](https://github.com/dotnet/templating/blob/a76fa40872c0013a88847de8dbfd812afb34efd8/src/Microsoft.TemplateEngine.Abstractions/IGenerator.cs)
- [RunnableProjectGenerator](https://github.com/dotnet/templating/blob/a76fa40872c0013a88847de8dbfd812afb34efd8/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/RunnableProjectGenerator.cs)
These implementations get checked against all template sources to discover their own marker files - you wouldn't use `template.json` for these, but whatever configuration file the generator itself expects (ex. a Visual Studio template engine running behind the IGenerator interface would look for a `.vstemplate` file in the source directory instead).

For all of these, the extensibility model is just to implement the interface (using a unique GUID for each component - no export or anything like that is required) and package it up as a nupkg. Running `dotnet new -i {the package}` will make all the components in the package available for use.

**Comment by fubar-coder** [comment]
Is there a sample where I can find the implementation of IOperationProvider and/or IGenerator as NuGet package to see how the package layout has to be?

**Comment by mlorbetske** [comment]
Both of these are actually NuGet packages in the repo (they're not pulled together by project references). You can see the actual package here https://dotnet.myget.org/feed/templating/package/nuget/Microsoft.TemplateEngine.Orchestrator.RunnableProjects

**Comment by fubar-coder** [comment]
Can I use this package as reference to build my own, that I can then install with the new dotnet CLI tools to make the new project templates available for `dotnet new`?

**Comment by mlorbetske** [comment]
@fubar-coder yep, for the development time experience though, you can tell it to install the folder containing the templates rather than having to create and install a package each time you want to make an update. Once you want to distribute it, then you'd want to package it up and publish to NuGet.

You might also want to check out @RehanSaeed's excellent post about creating templates http://rehansaeed.com/custom-project-templates-using-dotnet-new/.

**Comment by sayedihashimi** [comment]
I believe we've implemented this. @mlorbetske do we still need this issue?

**Comment by andycmaj** [comment]
> For all of these, the extensibility model is just to implement the interface (using a unique GUID for each component - no export or anything like that is required) and package it up as a nupkg. Running dotnet new -i {the package} will make all the components in the package available for use.

having trouble with this guidance. I am trying to develop a custom `IPostActionProcessor` following these instructions.

### dotnet new version

```bash
╰ dotnet new --debug:version                                                                            16:23:16
Template Instantiation Commands for .NET Core CLI

 Version:     1.0.1-beta3-20180215-1392068
 Commit Hash: 51a14e2ec1a696bb78868f4623ce010311ce206a
```

### My postactions project

#### csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netcoreapp1.0</TargetFramework>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <DebugType>full</DebugType>
        <DebugSymbols>true</DebugSymbols>
        <VersionPrefix>1.0.3</VersionPrefix>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.TemplateEngine.Abstractions" Version="1.0.2-beta3-20180417-325" />
        <PackageReference Include="Microsoft.TemplateEngine.Cli" Version="1.0.2-beta3-20180417-325" />
    </ItemGroup>
</Project>
```

#### action
```csharp
using System;
using Microsoft.TemplateEngine.Abstractions;
using Microsoft.TemplateEngine.Cli.PostActionProcessors;

namespace PostActions
{
    public class TestAction : IPostActionProcessor
    {
        public static readonly Guid ActionProcessorId = new Guid("01483af4-3f00-454c-9412-69ea39a62f39");

        public Guid Id => ActionProcessorId;

        public bool Process(IEngineEnvironmentSettings settings, IPostAction actionConfig, ICreationResult templateCreationResult, string outputBasePath)
        {
            settings.Host.LogMessage("HI MOMMMMM");
            Console.WriteLine("IS THIS WORKING");

            throw new Exception("foooo");

            // return true;
        }
    }
}
```

#### nuspec
```xml
<?xml version="1.0"?>
<package>
    <metadata minClientVersion="2.7">
        <id>PostActions</id>
        <version>0.0.0</version>
        <title>PostActions</title>
        <requireLicenseAcceptance>false</requireLicenseAcceptance>
        <developmentDependency>true</developmentDependency>
        <description>template post-actions</description>
        <dependencies></dependencies>
        <packageTypes>
            <packageType name="Template" />
        </packageTypes>
    </metadata>
    <files></files>
</package>
```

### template that uses the postactions

```json
{
  "$schema": "http://json.schemastore.org/template",
  "author": "Andy Cunningham",
  "classifications": [
    "api",
    "swagger",
    "docker",
    "react",
    "redux",
    "spa"
  ],
  "identity": "Templates.FrontEnd",
  "name": "frontend service",
  "shortName": "frontend",
  "sourceName": "Templates.FrontEnd",
  "tags": {
    "language": "C#",
    "type": "project"
  },
  "preferNameDirectory": true,
  ],
  "postActions": [
    {
      "actionId": "01483af4-3f00-454c-9412-69ea39a62f39",
      "manualInstructions": [
        {
          "text": "nothing to do"
        }
      ],
      "continueOnError": false,
      "description ": "Says hello"
    }
  ]
}
```

### testing the template

```
$ dotnet new --install /Workspace/nexxusnew/src/PostActions/bin/Debug/PostActions.1.0.3.nupkg
$ dotnet new --install /Workspace/nexxusnew/src
$ dotnet new frontend
The template "standard frontend service" was created successfully.

Processing post-creation actions...
Description:
Manual instructions: nothing to do
```

doesn't look like the postaction is actually getting executed.

any advice here? shoudl i open a new bug for this?

**Comment by seancpeters** [comment]
@andycmaj - Your code and configuration look fine, so the most likely cause of the problem is that your custom post-action code is not being correctly installed. The CLI your'e running is pretty old, I believe that component installation does not work correctly in that version.

Unfortunately dotnet new isn't very good with feedback about what actually got installed. The best way to check if it was installed is to check this configuration file:
`%USERPROFILE%\.templateengine\dotnetcli\v1.0.1-beta3-20180215-1392068\settings.json`
...or if you're on *nix, then it's in:
`\.templateengine\dotnetcli\v1.0.1-beta3-20180215-1392068\settings.json`
(the version directory under `dotnetcli` might be a little different than what I'm showing here).

In this file, look for your ActionProcessorId guid. If it's there, then your component was correctly installed. The guid should appear in multiple places in that file, including one entry under `ComponentGuidToAssemblyQualifiedName` which should also contain the name of your component: `PostActions.TestAction`

But with the version you're running, it probably won't install correctly. If it's not installed, I'd first recommend installing a newer version, if that's possible for you.

**Comment by andycmaj** [comment]
thanks for the snappy response, @seancpeters!

I'm actually not sure how to install a newer `dotnet new`. 
any pointers to docs for this?

sorry if this is a dumb question... i did try to find some docs on this

**Comment by andycmaj** [comment]
ok updated my SDK version and now i'm at

```bash
╰ dotnet new --debug:version                                                                            22:30:37
Template Instantiation Commands for .NET Core CLI

 Version:     1.0.2-beta3-20180406-1563557
 Commit Hash: 9331d3937ca61f1183ffab80ecba6bd6ce9ba3d9
```

updating dotnet sdk and re-installing the post-actions worked!

```
╰ dotnet new frontend -D foo --force                                                        4 ↵  22:33:40
The template "standard frontend service" was created successfully.

Processing post-creation actions...
HI MOMMMMM
IS THIS WORKING
foooo
```

thanks! this is awesome :)

**Comment by mlorbetske** [comment]
Closing this since it seems to have been resolved with the post-action extensibility

**Comment by RussKie** [comment]
This is awesome, thank you 👍

**Comment by mosBrkr** [comment]
> Closing this since it seems to have been resolved with the post-action extensibility

Could it be that this isn't supported anymore? I just tried to write my own post-action extension as @andycmaj described above, but I can't find the NuGet package 'Microsoft.TemplateEngine.Cli'.

**Comment by vlada-shubina** [comment]
@mosBrkr we are not distributing `Microsfot.TemplateEngine.Cli` anymore for various reasons.
We added the https://github.com/dotnet/templating/issues/3225 to make post actions extendable via different means.  If you're interested, please upvote and watch that issue.
