### ISSUE TITLE
Updated template not being offered on --update-check

### ISSUE THREAD

**Issue by timheuer** [dotnet/templating#2930]
Scenario:
I have a template package that is versioned and released on NuGet.  I had installed version 1.0.3 on my machine.  I went to release version 1.0.5 and it is published/listed on NuGet.

I use the CLI and `dotnet new --update-check` 

Expected Results:
It shows me 1.0.5 which is the latest

Actual Results:
It shows me 1.0.4 which is not the latest

![image](https://user-images.githubusercontent.com/4821/109854373-d1b95280-7c0b-11eb-8dd5-c25f5a0626e0.png)

**Comment by vlada-shubina** [comment]
@timheuer we are well aware of this issue. It happens because updates are checked against search cache stored on blob and updated once per 2 weeks. 
We are fixing it at the moment by switching to use NuGet API to check for updates. This is already available in feature/template-discovery branch and will be merged to master end of the March. 

I will keep the issue open and will close it once the feature is in master. Thank you.

**Comment by vlada-shubina** [comment]
We implemented check via NuGet API (available in main branch), now the update information is available immediately. 
Also API is forced not to use cache, so issue of local NuGet cache being old also eliminated (https://github.com/dotnet/templating/issues/2874) .
