### ISSUE TITLE
`dotnet new Razor` has weird result

### ISSUE THREAD

**Issue by DavidKarlas** [dotnet/templating#3038]

**Comment by bozturkMSFT** [comment]
Tags are no longer matched with `dotnet new` anymore. This issue is fixed in main branch already. Closing.

**Comment by vlada-shubina** [comment]
This happens due to `razor` is synonym short name to `webapp`. We only show first name in the list, therefore `razor` was not visible anywhere.

I will move it to May to fix it:
- we should show all short names in --list (and other table outputs)
- for template resolution where we consider all short names in the group, we should show all names in the grou
- we should test if existing templates are sharing too much names in 2.1 - 6.0, if yes we should consider showing only highest precedence short names
- when fixing above consider refactoring of the code
 - `TemplateGroup`s should be created as first step of template resolution logic and matching should be done through them
 - `TemplateGroup` should carry all the logic of short names in use.
 - eliminate `SetupTemplateInfoWithGroupShortNames` and related classes - this should be done inside template group.

![image](https://user-images.githubusercontent.com/56045248/115260534-85828d00-a13b-11eb-9439-41bc9090cf50.png)
