### ISSUE TITLE
Only show project templates by default with "dotnet new --list"

### ISSUE THREAD

**Issue by bekir-ozturk** [dotnet/templating#3108]
Extracting from work item: https://github.com/dotnet/sdk/issues/10587#issue-558633139

@davidfowl wrote on Feb 2, 2020 (irrelevant sections are removed):
>A few observations:
> - It's not clear which templates are item vs project templates.
>
>Some suggestions:
> - Show project templates by default and have an option to show all templates (or to filter by a specific template type)

**Comment by baronfel** [comment]
This is made slightly more complex because 'global' items like editorconfig, gitignore, etc. are all currently `item` templates. Once constraints are in, we will start doing this by default, because `items` will begin to declare their requirements in terms of constraints, and items that don't satisfy their constraints simply won't be listed.

**Comment by vlada-shubina** [comment]
Closing. The templates shown in the list can be restricted by constraints instead. Also comment above makes it clear that showing only project templates is not an option.
