### ISSUE TITLE
Unable to run 'dotnet new -i' on project templates that contain certain named files

### ISSUE THREAD

**Issue by swirlywonder** [dotnet/templating#3167]
### Description

I have created a dotnet project template for a third-party cms to expedite setup. One of the dlls explicitly included by the platform (not from a nuget package) is named Ude.NetStandard.dll.

If that file is included, the install is unsuccessful but no error message is shown. All the files remain stuck here:
`.templateengine\dotnetcli\v5.0.203\content`

Even if I remove the file from the template, it will continue to fail unless I delete the `content` folder (this template was built locally using the same version number which likely caused this collision). As long as that file is not present the template install will succeed and work as expected so this exact file is the cause.

This issue is present in dotnet v5.0.203.

### Expectations

1. If a dotnet template fails to install, there should be an error message
2. If a failure does occur, the content directly should be cleaned up
3. The template engine shouldn't assume that the word "netstandard" in a file name means netstandard.dll
4. I'd like to get a fix or workaround so that this file can be included in the template

**Comment by swirlywonder** [comment]
FYI, I have just confirmed that renaming `Ude.NetStandard.dll` to `Ude.Something.dll` does work correctly so the literal use of the word "netstandard" appears to cause the problem.

**Comment by DavidKarlas** [comment]
This is bug is fixed in .NET 6 SDK, problem is that we have concept of Components which loads .dlls and yes we have hardcoded "netstandard" check in .dll name...
There are 2 problems in .NET 5 SDK...
1) We don't actually check if .dll has Components inside(your doesn't) and still consider it as Components .dll
2) Once we detect components we stop loading Templates...

Unfortunately there are only 2 possible workarounds, none is ideal:
1) Preferred one: Don't include this .dll into your template and instead add it as PackageReference:
Add following lines to your .csproj file:
```xml
<ItemGroup>
  <PackageReference Include="Ude.NetStandard" Version="1.2.0" />
</ItemGroup>
```
and delete .dll from your project.
2) Rename the dll. :(

**Comment by swirlywonder** [comment]
@DavidKarlas Thanks so much for the confirmation and followup. This isn't a deal-breaker in my case because I'm only making these templates to save myself setup time, however I did want to report it because I lost several hours trying to pinpoint the exact reason. My template from last year worked fine and this year wouldn't run even with identical structure... As it turns out 
it was simply because they moved to support NetStandard and that dependency name changed. It's usually the little things...

I will consider using your suggested workaround (the first not the second lol) until .NET 6 comes out in November.

No further action is required on this ticket. Thank you for time!
