### ISSUE TITLE
dotnet commands extremely slow 

### ISSUE THREAD

**Issue by loligans** [dotnet/templating#3198]
When running dotnet commands under poor network conditions the command takes ~20 seconds to terminate. The actual code completes rather quickly.

```
time dotnet new sln -n MyTestProject
The template "Solution File" was created successfully.
dotnet new sln -n MyTestProject  0.97s user 0.28s system 5% cpu 21.339 total
```

Repro Steps:
_Under a spotty network connection_
dotnet new sln -n MyTestProject

**Comment by bekir-ozturk** [comment]
Hi @loligans,
 This issue is likely caused by "checking for updates of the template" that you are trying to instantiate.
 This issue should now be fixed as updates for SDK templates are no longer checked during template instantiation. Update checks should also be faster now as we have made some improvements in that front.
 Please let us know if the issue persists.
