### ISSUE TITLE
defaultName option not working as expected with Item templates

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/templating#3222]
defaultName option not working as expected with .NET CLI Item templates.

Have defined a defaultName with a valid value in the template.json, but it is never used when a name is not provided while invoking the dotnet new command.

The value for the name always defaults to the current folder name.

Have tried with both stable .NET 5 and .NET 6 Preview 4, results are one and the same, for item templates, it always defaults to the current folder name if value not specified for both .NET and Custom templates.

To simulate the issue, run the following command:

```console
dotnet new razorcomponent
```

**Comment by vlada-shubina** [comment]
@egvijayanand 
thank you for reaching us.

This is expected behavior of `dotnet new`: if the name is not specified, the name of current directory is used instead.  `defaultName` from template.json is not used by `dotnet new`.

There is a request to provide a way to use `defaultName` instead of current directory name in https://github.com/dotnet/templating/issues/2303 and https://github.com/dotnet/aspnetcore/issues/11824, therefore this issue is a duplicate. Could you please consider following those issues instead? Thank you.

Closing as a duplicate.
