### ISSUE TITLE
'dotnet new android' produces invalid images

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/templating#3325]
Our templates: [microsoft.android.templates.30.0.100-preview.6.56.nupkg.zip](https://github.com/dotnet/templating/files/6697578/microsoft.android.templates.30.0.100-preview.6.56.nupkg.zip)

If you `dotnet new android` you get a broken image that is coincidentally ~8kb:

![image](https://user-images.githubusercontent.com/840039/123003404-c46dd280-d378-11eb-94a6-00c8c06684d0.png)

This broken image causes `dotnet build` to fail when calling the underlying Android tooling:

```
Resources\mipmap-xxxhdpi\ic_launcher_round.png error APT2000: failed reading from input: PNG chunk type 49444154 is too large: chunk length is 10836 but chunk starts at byte 45/8187.
```

If I unzip this file myself (with a tool like 7-zip), it is actually larger than ~8kb:

![image](https://user-images.githubusercontent.com/840039/123003490-e1a2a100-d378-11eb-957f-b5d2d65d7ffe.png)

I suspect if a template has a file larger than ~8kb you'll hit this issue.

This started happening in Maestro bumps here:

* https://github.com/xamarin/xamarin-android/pull/6029
* https://github.com/xamarin/xamarin-android/pull/6034

So likely the issue started somewhere bumping .NET 6.0.100-preview.6.21313.2 to 6.0.100-preview.6.21321.13.

**Comment by vlada-shubina** [comment]
@jonathanpeppers I tried to reproduce this bug, but was not able two - the files in template and in generated output are identical.
We were not touching core template engine (the assembly that generates the files) since preview 5. Anything else that can affect this? 

In general I would recommend to use "copy-only" mode for files without replacements (see the [link](https://github.com/dotnet/templating/wiki/Reference-for-template.json#content-manipulation)). This will avoid any file modification, the file will be copied from template content, and also should be faster as template engine will not scan the file content for variables.

**Comment by jonathanpeppers** [comment]
I can confirm adding this to our `template.json` works around the issue:
```json
  "sources": [
      {
        "source": "./",
        "target": "./",
        "copyOnly": "**/Resources/**/*.png"
      }
  ],
```

I'll set this up on any iOS/Android templates for `.png` files, thanks. It should improve performance as well.

**Comment by vlada-shubina** [comment]
The cause of the issue is: https://github.com/dotnet/docs/issues/24649.
It affects only .NET core running on runtime later then .NET 6 preview 6, it does not affect full framework versions. 
We will need to rewrite portions of the code in `TemplateEngine.Core` using `stream.Read` in a wrong way (about 20 occurrences). 
This is tentatively scheduled for preview 7, might slip to rc1. 
For those affected, please consider to use `copyOnly` (see https://github.com/dotnet/templating/issues/3325#issuecomment-866833952) in case the files should be just copied to target folder without any modifications, especially in case of binary files; and see if it solves the problem.

It is strongly recommended to **use `copyOnly` for all binary files in your templates**  (even without the context of the bug) as template engine is scanning files byte wise for making replacements. In case of the match the byte content will be replaced even in binary files, and this leads to corrupted file after template generation. Using `copyOnly` in your template for the files that should be copied without modifications also improves performance when instantiating the template.
