### ISSUE TITLE
sourceName replacement does not work correctly with snake-case template projects

### ISSUE THREAD

**Issue by airzym** [dotnet/templating#3506]
When a template project is snake cased (e.g. `dotnet_template.csproj`) the `souceName` replacement does not respect the target casing everywhere (appsettings.json, namesapce names etc). (e.g. `dotnet new mytemplate -n Dotnet.Template`)

### Reproduction Steps:

- Clone and install the following template (note the use of snake case): https://github.com/airzym/dotnet_template
- Run `dotnet new airzym_webapi -n Dotnet.Template`

While it does appear to correctly name directories and `.csproj` files. you will see namespace's are generated as `namespace dotnet.template...` instead of `namespace Donet.Template...`.

**Comment by AR-May** [comment]
@airzym 
sourceName renames is quite a tricky thing. It is not only one replacement that will apply to your code (sourceName -> name), but a bunch of them.
You can take a look at this [wiki page](https://github.com/dotnet/templating/wiki/Naming-and-default-value-forms) to understand which replacements are generated and applied to filenames and to file content given a pair of sourceName/name when you run `dotnet new`. 

I believe that problem is that the one you chose is ambiguous. That means that there will be more than one generated replacement for the same key and what you get as a result of the replacement is not quite deterministic and in different situations the same string is replaced differently (you can not distinguish the lowercase and not lowercase). So, it seems that snake cased sourceName is not a good choice and the generated replacements will not work well. You can  also look at some simple templates in our repo for an example for a good sourceName: https://github.com/dotnet/templating/tree/main/template_feed

**Comment by AR-May** [comment]
Hope my answer was helpful.
I am closing this issue. Please do no hesitate to reopen the issue if you have more questions.
