### ISSUE TITLE
dotnet new -l : Table view can be improved on.  

### ISSUE THREAD

**Issue by chad-ramos** [dotnet/templating#361]
# Issue
The combined length of the **Template**(name), **Short Name**(shortName) & **Tags**(classifications) fields causes unpleasant line-breaks when greater than the width of your console.  Ultimately this equates to a bad UX.   

![default](https://cloud.githubusercontent.com/assets/3170200/23240878/78e276c6-f935-11e6-85e7-63e3b69a3eea.jpg)

# Reproduce
When defining your template meta-data in **template.json**, add a large **name**, **shortName**, **classifications** or combination of the threes.

# Possible solutions
### 1

- Determine an average default console width.  For example, you can use the default width cmd or powershell opens with on windows. 
- Truncate a determined combination (add ellipsis) of the three fields in question, so that there will be no break.
- The user would be able to then drill down into that template for more details and a full view of any possible truncated strings. 

### 2

- Abandon the table view all to together in favor of a stacked view.
- To be quite honest, this seems to be best practice these days.
- If you have a lot of templates, finding one might be a bit hard but I don't believe that this issue is fixed with a table either.

**Comment by mlorbetske** [comment]
We're looking at improving the table in the time between now and having the interactive mode come online. What you're seeing is the result of some overly simplified calculations on how the table's columns have their sizes calculated & a missing application of the table maximum width (bounding it to the current console size). We're hoping to get working on the fix for this (and the corresponding issue with parameter help) next week.

**Comment by Eilon** [comment]
I have a PR for this here: https://github.com/dotnet/templating/pull/2270
