### ISSUE TITLE
"dotnet new project-template" / "dotnet new item-template"

### ISSUE THREAD

**Issue by tintoy** [dotnet/templating#374]
Hi.

Is anyone working on templates that create project / item templates? I've been doodling around on this, and if nobody else has I'd be happy to contribute what I've got after tidying it up.

**Comment by mlorbetske** [comment]
Sounds great! If you want to distribute them on your own though, I know @sayedihashimi has been working with a bunch of folks on templates of different kinds too, he'd have some good info on how they're thinking of doing distribution and updating of their content. We're also going to be adding a section to the readme soon that lets people know who's been working on templates and where to get them from.

**Comment by sayedihashimi** [comment]
>Is anyone working on templates that create project / item templates?

This sounds like an interesting idea. I think this would be better executed as a community project (where I'm including myself in the community). In the past I've been a driver for the [SideWaffle](https://github.com/ligershark/side-waffle) project, which is a popular template pack for VS2013/2015 and it leverages the existing .vstemplate infrastructure. The model that we used there was that we had a single repository for templates and a single .vsix which contained all the templates for VS users. Going forward we will be using the Template Engine to create templates and templates will be shipped in individual nuget packages instead of coming via a single .vsix. We haven't started this effort yet, but I'd like to get that going and I think your suggestion of `project-template` and `item-template` would be a good fit for that. 

If you're interested we can discuss more with @RandomlyKnighted (SideWaffle core contributor) and get started with that. One thing we will have to figure out is how we can surface the templates we create in VS. We will likely need to create a custom wizard(s), and need some help from @mlorbetske to get going there.

**Comment by tintoy** [comment]
I'm interested :)

**Comment by RandomlyKnighted** [comment]
That sounds great. I'm a little behind on the dotnet new stuff at the moment.  @sayedihashimi Do you know of any documentation or blog posts that talk about how to create a template with dotnet new and package it correctly for nuget? I'd like to look at the process and see what all is involved before we start everything.

**Comment by tintoy** [comment]
I know you didn't ask me, but can at least offer a working sample that needs no extra tooling :-)

https://github.com/tintoy/ps-core-module-template

**Comment by sayedihashimi** [comment]
I've created a new discussion at https://github.com/ligershark/side-waffle/issues/401.

@RandomlyKnighted see 
 - https://aka.ms/dotnetnew-intro
 - https://aka.ms/dotnetnew-create-templates

**Comment by mlorbetske** [comment]
Since the template templates now [exist](https://github.com/tintoy/dotnet-template-templates) and have been added to the Wiki (thanks @tintoy!) should this issue be closed?
