### ISSUE TITLE
How can i get started with debugging?

### ISSUE THREAD

**Issue by taori** [dotnet/templating#3884]
I have tried to follow the wiki but if i select the main branch i get this:

![grafik](https://user-images.githubusercontent.com/5545184/132533870-c66f38ed-fda2-4bb0-84d7-65ec01e98127.png)
When i follow the link i get 404, assuming because 7.0 alpha is a hidden release i cannot get access to

if i checkout release/5.0.4xxx i get this:
![grafik](https://user-images.githubusercontent.com/5545184/132534208-02712aff-138f-4995-89d8-bb71bfc67e40.png)

Is there a specific branch i can checkout which usually works?

**Comment by bekir-ozturk** [comment]
Hi @taori,
 Have you tried running `build.cmd` on main branch? This should resolve your issue with missing 7.0.0-alpha runtime. Let me know if you get any errors.
 If it doesn't work, you can run this command on powershell to get yourself unblocked:
```powershell
&([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://dot.net/v1/dotnet-install.ps1'))) -Runtime dotnet -Version 7.0.0-alpha.1.21453.1 -InstallDir 'C:\Program Files\dotnet'
```
You may need to run powershell as admin to be able to install the runtime into `C:\Program Files\dotnet`.

I will check the issue with `release/5.0.4xx` branch.

**Comment by bekir-ozturk** [comment]
build.cmd on `release/5.0.4xx` branch is correctly installing the SDK on my machine. There are compiler errors because the branch has outdated analyzers that need a version bump. I suspect that the reason your build.cmd run has failed is that the dotnet.exe is already running and therefore the extraction fails to override it. Can you retry after making sure dotnet.exe is not running in the background?

Do you specifically need the `release/5.0.4xx` branch? If not, I recommend sticking to the main branch as we have many changes to the engine after 5.0.

Let me know how it goes and we can further investigate if you are still getting errors.

**Comment by taori** [comment]
Ok so this is my feedback:

"5.0.4xx" issue was fixed by using a powershell with admin privileges
"main" issue was fixed by running `&([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://dot.net/v1/dotnet-install.ps1'))) -Runtime dotnet -Version 7.0.0-alpha.1.21453.1 -InstallDir 'C:\Program Files\dotnet'` as you suggested.

Thanks a lot!
