### ISSUE TITLE
"How to build and run the latest" - Moving towards an explicit explanation....

### ISSUE THREAD

**Issue by chad-ramos** [dotnet/templating#399]
### Issue
Obviously my position approaching this, is an outsider looking in.  One looking to make contributions to this project would require a ramp-up, of which starts with [How to build and run the latest](https://github.com/dotnet/templating#how-to-build-and-run-the-latest). 

The combination of the four steps that are outlined and how I (an outsider) perceive them, fails to produce a working dev environment.  Of which, I would attribute to implicit explanations. 

### Breakdown

**Prerequisites**

- Though to one it might seem obvious, things like denoting vs 2017 is a requirement is of value to others. 

**Step 1: Get the SDK for your platform from dotnet/cli**

- More explanation is needed as to what version is required and how to maintain version compatibility moving forward. 
- Do we need 1.0.x, 1.1.x, 2.x?  Do we need RC or Alpha? 

**Step 2: Clone this repository to your local machine**

- Simple enough on the surface but details on branching strategies and expectations would go a long way.
- For example, as of the date I am writing this, it appears the default branch is rel/vs2017/post-rtw.
  - If the expectation is for contributes to branch off of branch-x, explicit explanation would go a long way.  

**Step 3: Run the setup script**

- Again, simple enough but results in an unclear outcome.  See next step...

**Step 4: That's it! Now you can run dotnet new3**

![untitled-1](https://cloud.githubusercontent.com/assets/3170200/23528117/7a210a02-ff4d-11e6-8983-cd84aaaef32a.jpg)
 
- Running through the steps as I have viewed them, has resulted in the above. 
  - ```dotnet new --help``` produces expected output while ```dotnet new3 --help``` does not.

### Solution
It would be of value to open up the conversation early about the process I or any other potential new contributor goes through when trying to ramp up the knowledge set needed to contribute to this project.   Personally, I would be more then willing to document the knowledge gained as I progress through this process.  Be that via the wiki or readme.

**Comment by mlorbetske** [comment]
Hi @chad-ramos, answers to your questions below. I totally agree that we should get more crisp about these things in our docs (and yes, if you're up for enhancing our getting started steps, we'd be more than happy to take a PR or a wiki update :) )

For step 1:
The latest 1.1 RC SDK is the one we've been using (build 004771 or higher should work)

For step 2:
Yep, we've got #288 tracking this, trying to get to this soon. The active development branch is rel/vs2017/post-rtw at the moment.

For step 3:
When the setup script runs, it builds & makes `dotnet new3` available (by adding it to the path), but only for that console session. To use it in a new console session, setup needs to be run again.

**Comment by chad-ramos** [comment]
@mlorbetske In regards to step 3...

- Can please offer up more details on your definition of "**console session**"?
- Is the expectation that I should be able to build and launch a console session from the  **DotnetNew3.sln"?
- Or is the expectation that the **setup** script patches a local install of the SDK?

In regards to, **DotnetNew3.sln**, can you offer up advice on how to re-align these references...
![untitled-2](https://cloud.githubusercontent.com/assets/3170200/23640614/70c440b8-02b4-11e7-8e6f-6dc5cbcc258c.jpg)

**Comment by mlorbetske** [comment]
A console session in this case refers to the period of time in which the command prompt window is open.

Ex.
* Start cmd.exe <-- This start the console session
* CD into the templating repo sources
* Run setup.cmd
* Use `dotnet new3`
* Close that instance of cmd.exe <-- This terminates the console session

When running setup, no modification is performed to any installed SDK on your machine, it just adds `dotnet-new3.exe` (produced by the build) to the `PATH` - this is also why after the end of the console session that `dotnet new3` isn't available in other windows (`SET x=...` only updates the environment variables for the console session it's executed in). After #401, gets merged, running setup will make `dotnet new3` available in not just the current console session, but any console sessions started _after_ setup has been run

To your questions about DotnetNew3.sln, this project cannot be F5'd (or even built in Visual Studio without at least partially building from the command line first) - it's separated from the other projects to prevent undesired build characteristics. In addition to just being separated from the other projects, it refers to them as packages rather than projects - those packages are produced by the setup script (the NuGet.config by the project points to the location the setup script produces the packages). Depending on the order of events in producing the packages & opening the solution, restore may or may not find the packages in the artifacts directory and produce errors such as these. The references are, in fact, correct, so there's nothing that needs fixing there. Fortunately, we've managed to move nearly all of the code out of that project, so there's very little interesting in there anyway.

**Comment by chad-ramos** [comment]
@mlorbetske Thank you for the additional details.  I have manage to get a session up that responded to ```dotnet new3```.  That being said, can you speak to the debugging experience?  Maybe offer some basic bullet points about how you typically launch the project and debug an active session.

**Comment by mlorbetske** [comment]
Currently, the way to do debugging is to do the normal build via `setup` and then call `dotnet new3 --debug:attach`. This will cause a `Console.ReadLine()` to stop execution of the engine very early on, giving you the opportunity to attach a debugger to the process. Once it's attached, return to the console and press enter to resume execution of the code.

**Comment by chad-ramos** [comment]
@mlorbetske Per your instruction I followed these steps...

- Opened up a cmd prompt, cd(ed) to setup script and ran it successfully.
- Ran ```dotnet new3 --debug:attach```.
  - I am assuming this is caught in ```New3Command.Run()```, which basically pauses execution of the logic loop until a new key is hit?  Of which, as you noted, should allow me to attach the debugger to that current session. 
- In VS, I hit ```ctl + alt + p```, locate the running cmd process and attach the debugger to it.
- Jump back to the cmd prompt and hit enter.

It is at this point I am stuck.  
- Am I correct in stating that I should now be able to in theory set a breakpoint inside ```New3Command.Run()```, run a new command against ```dotnet new3``` and get that breakpoint to hit?
- Currently, I am unclear how to get symbols to load which is prohibiting any breakpoints from being active.

![untitled-1](https://cloud.githubusercontent.com/assets/3170200/23771293/13c119ca-04dc-11e7-8a4e-9c25b17325c1.jpg)

Greatly appreciate the time. Cheers...

**Comment by mlorbetske** [comment]
@chad-ramos you'll want to attach to `dotnet-new3.exe` rather than `cmd.exe`

**Comment by chad-ramos** [comment]
@mlorbetske So this time around....

- Ran setup
- Ran ```dotnet new3 --debug:attach```
  - Of which, appears to pause the console while it waits for input.
- Attached to ```dotnet-new3.exe```
  - Attaching produces an identical situation to the illustrated in my last picture.  No symbols being loaded.
- Went back to the command line and hit ```enter```

When I hit ```enter``` this time, it immediately shuts down the current debug session.  Am I correct in saying the attachment is "transactional" to the ``dotnet new3 --debug:attach``` command being ran? In other words every time you want to debug, you get one logic loop before having to "re-attach".

Thoughts?  Still unclear how to actually hit a breakpoint.

Again, thank you for working through this with me.

**Comment by mlorbetske** [comment]
Try this sequence of events:
+ Run setup 
+ Type "debug" and press enter (this runs a script to set the build to debug mode, this could be run before setup instead of running it twice if you call the script directly instead of via the alias that's set by the first setup)
+ Run setup again
+ dotnet new3 --debug:attach
+ Attach to the dotnet-new3.exe process
+ Press enter in the console to stop blocking
+ Breakpoints should now be hit 

You're correct in saying that there's one shot at debugging per time running dotnet new3.

**Comment by chad-ramos** [comment]
@mlorbetske -  That did it!  I opened up a PR with these topics detailed in the README. #417

**Comment by chad-ramos** [comment]
@mlorbetske - With #417 being merged, any issues with closing this "Issue"?

**Comment by mlorbetske** [comment]
Sounds good. Thanks @chad-ramos for writing up the detailed instructions!
