### ISSUE TITLE
.NET 6 - dotnet project templates -  NuGet package and VSIX ?

### ISSUE THREAD

**Issue by jonmikeli** [dotnet/templating#4021]
Hi,

Since dotnet templates (CLI)  are now visible in Visual Studio, is there a way to install these templates through a VSIX ?
Ex: add the NuGuet package somewhere in the VSIX, and when the VSIX is "installed", it installs the dotnet project template (dotnet new install...).

If this has not been implemented, any way to do it?
Thanks.

**Comment by sayedihashimi** [comment]
@jonmikeli yes you can ship .net cli templates in a VSIX, more info at https://github.com/sayedihashimi/template-sample#how-to-ship-a-template-inside-of-a-visual-studio-extension-vsix

**Comment by sayedihashimi** [comment]
That behavior is by design, a VSIX is specific to the version of VS in which it is installed. We have no plans to support that scenario. You could potentially implement that in your VSIX via a custom wizard, but it likely wouldn't be supported.

**Comment by jonmikeli** [comment]
Many of them actually ;) :).

**Comment by Mrxx99** [comment]
> @jonmikeli Note: if the user installs templates via the CLI and in a VSIX, I believe the highest version will win. Not 100% on that though.

That seems to be not true, for me it always prefered tha CLI templates when they were installed, even if the version of the nupkg of the CLI version was lower compared to the version of the nupkg included in the VSIX (VS2022 and VS2022 preview). Is that a bug in VS? Because here updating the extension will still give old templates then.

**Comment by sayedihashimi** [comment]
@Mrxx99 do you need to ship the templates both in a VSIX and the CLI? I’m wondering if the CLI templates are working if you must have the VSIX as well? If so, which is the preferred method for users to install them?

**Comment by Mrxx99** [comment]
@sayedihashimi Sorry for the late reply.
The best experience for the user would be to ship the templates in both CLI and VS, as many not on windows or using VS Code or Rider would need the CLI templates, but users on VS would rightfully expect the templates to be there if they only install the VSIX (which also does other things beside providing templates).
But at the same time the user should have a good experience when having both installed CLI templates and VSIX, e.g. because first using VS Code and later transitioning to VS. The problem with the current approach is, that if the user start with CLI templates and installs say version 1.0, then switches to VS and does not update the CLI templates. Now he can't use new templates in VS even though they are provided by an updated VSIX with the included templates approach because the older CLI templates are preffered.

I also think that most users that use VS have both CLI and VSIX installed because that is the consequence when they follow the docs. Here talking about [Avalonia](https://docs.avaloniaui.net/docs/getting-started).
Avalonia currently has the old template approach in VSIX and CLI templates but VSIX templates are lacking behing because developers don't want to maintain the templates twice. That's why the approach of including the dotnet-new templates in the VSIX would be great and solve this **if** VS did not have the bug to always prefer the CLI templates.

The solution and also most intuitive way would be (like you also [assumed](https://github.com/dotnet/templating/issues/4021#issuecomment-945990751) it already is) to prefer the highest version of the template between CLI and VSIX.
