### ISSUE TITLE
Creating T4 Template in .netcore

### ISSUE THREAD

**Issue by ali-raza-iftikhar** [dotnet/templating#408]
Hi i am totally lost. How to write a T4 template for .net core. and what will be dependencies and what will be the scaffolding command for this template.
I am doing development in VS2015 Windows.

**Comment by mlorbetske** [comment]
Hi @ali-raza-iftikhar unfortunately, this repo doesn't relate to T4 or VS2015 tooling. For the command line scaffolding experience in .NET Core (for ASP.NET), you'll want this repo https://github.com/aspnet/scaffolding - it uses Razor views to do the content templating rather than T4 though. For questions/issues with T4 and/or VS2015, I'd suggest filing an issue on [Connect](https://connect.microsoft.com/), but I'm not aware of any command line tooling for T4 and .NET Core.

**Comment by ali-raza-iftikhar** [comment]
Thanks for this help. :-)
