### ISSUE TITLE
Caching issue impacting local folder templates

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/templating#4155]
There is some caching issue happening that is impacting local template dev experiences. I've noticed that when I create a template that doesn't have any symbols, after adding symbols later they are not properly detected. Try these steps.

- Create a project template in a folder that doesn't have any symbols
- Install the template with `dotnet new --install [folder-path]`
- Modify source template to have one or more symbols
- Uninstall the template with `dotnet new --uninstall [folder-path]`
- Install the template with `dotnet new --install [folder-path]`
- Run template specific help with `dotnet new [template-name] -h`

When you run the help, you'll notice that the parameters appear but the names for the options will not appear on the left side of the descriptions. If you try to execute the template and pass in a param it will fail.

To fix this sometimes you can change the id of the template, but in other cases you'll need to actually move the template to another folder to get it to install correctly. I have a video below showing you what happens, but you can also see that I ran into this issue when I was presenting at dotnet conf. Here are the timestamps where I ran into this.
 - https://youtu.be/iHDOiO_Wf78
 - https://youtu.be/iHDOiO_Wf78?t=1553

https://user-images.githubusercontent.com/1283154/143909623-3e97db57-41da-47ae-bf54-0f6c10a59a4e.mp4

cc @vlada-shubina @phenning @vijayrkn

**Comment by vlada-shubina** [comment]
@sayedihashimi thanks for pointing this out. Have you tried `--debug:rebuild-cache` flag to see if it fixes the issue?

The criteria for folder-based package is last modification date of the folder: if it's changed, the template will be rescanned. I believe if you just change the template.json the folder modification date is not changed, but I will do more testing.  `--debug:rebuild-cache` will force rescan. 

The issue with help might be in caching host data - host data is now cached, and detailed information is not. Since we are moving to new parser with this part totally reengineered, unless this issue needs fix in 6.0.2xx I would prefer not to invest in this.

As folder mount points are mainly used for authoring, I think it makes sense to adjust the criteria to check the last modification date for all files in the package. It might be a performance hit, especially if folder has many files, however the authoring experience may improve. We also may introduce a debug flag for rescanning single package, however documenting using `--debug:rebuild-cache` might be also a way.

@DavidKarlas @baronfel what are your thoughts?

**Comment by sayedihashimi** [comment]
@vlada-shubina how do I run that? I tried the following, but got errors.

```bash
C:\temp> dotnet new --debug:rebuild-cache
Error: Invalid option(s):
  --debug:rebuild-cache
For usage information, run:
   dotnet new -h

C:\temp> dotnet new --install C:\data\mycode\template-sample\src\Content\ --debug:rebuild-cache
Error: Invalid option(s):
  --debug:rebuild-cache
For usage information, run:
   dotnet new **-h**
```

**Comment by vlada-shubina** [comment]
@sayedihashimi apologies, it is `--debug:rebuildcache` (without dash).

**Comment by baronfel** [comment]
I think it makes sense to do more expensive-but-correct things to make local template development easier. Let's do the last-modification-checks for folder installs 👍

**Comment by vlada-shubina** [comment]
Re-running `dotnet new --install` on folder already installed, should reload the content of that folder (basically reinstall it).

**Comment by vlada-shubina** [comment]
https://github.com/dotnet/templating/pull/4754 fixes the problems in this issue:
- cache is rebuilt after uninstall to ensure that uninstalled templates are removed from cache.  Fixed logic in determination when cache is outdated.
- folder packages: last change date is updated to installation date time if last write date time is later
- `dotnet new install smth --force` will reinstall the template even if already installed.

Decided not to check last modification date of each file in the folder as it might be pretty expensive in case template contains lots of files. Moreover, we only interested to see if configuration is changed at that point, but don't have any API to get list of configuration files (might be an improvement in future).

**Comment by ajdvoynos** [comment]
I'm still facing this on 6.0.400 (which I believe should have this fix?). I still have to use `--debug:rebuildcache` or `--debug:reinit` to get the parameters to show up correctly after any changes. 

`--force` flag doesn't seem to work either.

**Comment by vlada-shubina** [comment]
@ajdvoynos the change wad done only in .NET 7. It was not backported to .NET 6 unfortunately.
