### ISSUE TITLE
Guid sample in wiki no longer works

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/templating#4186]
The guid sample no longer works https://github.com/dotnet/templating/wiki/Available-Symbols-Generators#guid.

I created a template for this https://github.com/sayedihashimi/template-sample/tree/main/src/Samples/14-guid.
All guids are generated as D.

----
Update (13.12.2021)

Action items:
- [ ] fix example in [wiki](https://github.com/dotnet/templating/wiki/Available-Symbols-Generators#guid)
- [ ] deprecate `format` in generator definition in favor of using `guids` in `template.json`
- [ ] add documentation on how to use `guids` in `template.json`
- [ ] remove/deprecate guid generator from schemastore [json schema](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/template.json#L50)

Related bug:
- https://github.com/dotnet/templating/issues/3130

**Comment by vlada-shubina** [comment]
I found this one: https://github.com/dotnet/templating/issues/1737 and though it is closed it was never fixed.

@sayedihashimi to fix your example, you need to use `defaultFormat` instead of `format`, then it would do what is explained. 

For `format`, as far as I understand the idea was to generate parameter for each format as `<symbol name>-<format>` and then use it for replacements. But it doesn't work at the moment, and I believe it doesn't work since https://github.com/dotnet/templating/issues/1737

**Comment by vlada-shubina** [comment]
I found the way how it may work however:
```
    "id01": {
      "type": "generated",
      "generator": "guid",
      "replaces": "myid01",
      "parameters": {
        "format": "NDnd",
        "defaultFormat": "N",
      }
    },
    "id01-N": {
      "type": "bind",
      "binding": "id01-N",
      "replaces": "myid01-N"
    },
    "id01-D": {
      "type": "bind",
      "binding": "id01-D",
      "replaces": "myid01-D"
    },
    "id01-N-LC": {
      "type": "bind",
      "binding": "id01-n",
      "replaces": "myid01-n"
    },
    "id01-D-LC": {
      "type": "bind",
      "binding": "id01-d",
      "replaces": "myid01-d"
    },
```
but even in this case, casing won't work due to https://github.com/dotnet/templating/issues/3130

@sayedihashimi do you see any value in having guid generated symbols over `guid` in `template.json`. 
`guid` is working through generated symbols but it uses all generated parameters properly and imo it's more smooth way of authoring as it may do format conversion seamlessly. 

I may suggest the following alternatives:
- we deprecate `guid` generators in favor of `guid` in template.json
- we keep `guid` generators but only with `defaultFormat`. `format` becomes obsolete, anyway it doesn't work as expected.
- we keep `guid` generators and fix the `format` to do binding as above automatically. However I'm in doubt if it brings any benefit over using `guid` section.

**Comment by sayedihashimi** [comment]
Thanks Vlada, I have updated my sample showing this https://github.com/sayedihashimi/template-sample/tree/main/src/Samples/14-guid.

I like using the `guids`property in `template.json`. With that property is it possible to generate different formats as well? If so, then I see no reason to keep the `guid` generator. If you are looking to deprecate it, I can modify my tool to detect usage so that we can get an idea of how broadly it is being used.

**Comment by vlada-shubina** [comment]
> With that property is it possible to generate different formats as well?

Yes, you may. For example, if `guid` has `D` format and content has same guid in `N`, when replacing the format of final guid will be changed too.

**Comment by vlada-shubina** [comment]
Action items:

- [ ] fix example in [wiki](https://github.com/dotnet/templating/wiki/Available-Symbols-Generators#guid)
- [ ] deprecate `format` in generator definition in favor of using `guids` in `template.json`
- [ ] add documentation on how to use `guids` in `template.json`

**Comment by vlada-shubina** [comment]
@baronfel we triaged item as for action items above, please comment in case additional actions are required, otherwise feel free to remove assignment/label.

**Comment by baronfel** [comment]
@vlada-shubina the proposed plan looks good to me. We'd also need to update the `template.json` schema in schemastore, I'll add an item for that.

**Comment by JanKrivanek** [comment]
- [x] [`guid` doc](https://github.com/dotnet/templating/blob/main/docs/Available-Symbols-Generators.md#guid) updated
- [x]  [`guids` doc](https://github.com/dotnet/templating/blob/main/docs/Reference-for-template.json.md#guids) added
- [x]  [`format` deprecated in `template.json`](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/template.json#L57)
