### ISSUE TITLE
Post Action remove projects to a solution file

### ISSUE THREAD

**Issue by Jaxelr** [dotnet/templating#4292]
I'm currently working on a client that uses some custom dotnet templates that would benefit from a feature on postActions that remove projects based on flags, behaving oppositely to the Add projects to solution file [postAction](https://github.com/dotnet/templating/wiki/Post-Action-Registry#add-projects-to-a-solution-file), something similar to:

```json
"primaryOutputs": [
    {
      "path": "MyTestProject.csproj"        
    }
],
"postActions": [{
  "description": "Remove projects to solution",
  "manualInstructions": [ { "text": "Remove project to solution manually." } ],
  "args": {
    "solutionFolder": "src"
  },
  "actionId": "FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF",
  "continueOnError": true
}]
```

My current workaround for this behavior is to have a base solution file that adds the projects as indicated by the flags of the dotnet new command, but during development it would be beneficial to compile and validate all features available, therefore i have added another solution with all the projects included that gets excluded on the packaging build on ci.

**Comment by bekir-ozturk** [comment]
Hi @Jaxelr,
 Thanks for the issue.
 Can you help us better understand your case by elaborating on why you need such functionality?

**Comment by Jaxelr** [comment]
Sure, simplifying my use case, consider the following template structure (inside my Content folder):

``` tree
.
├── .templateconfig
├── .editorconfig
├── Solution.sln
├── /src
│   ├── Program.cs
│   └── Api.csproj
│ 
├── /tests
│   ├── TestFixtures.cs
│   └── Api.Tests.csproj
│ 
└── /external
     ├── Program.cs
     └── Api.Client.csproj
```

The reasoning behind this structure is that some of the templates are used for internal and external api designs and not all the csprojs are needed or used during the API Development, but they are included as part of the same repository since they belong to the same business domain. I would ideally like all the csprojs to be compiled and tested while developing in Visual Studio, my current workaround is to add a Solution.Development.sln that gets excluded on the packaging step.

``` tree
.
├── .templateconfig
├── .editorconfig
├── Solution.sln
├── Solution.Develop.sln***
├── /src
│   ├── Program.cs
│   └── Api.csproj
│ 
├── /tests
│   ├── TestFixtures.cs
│   └── Api.Tests.csproj
│ 
└── /external
     ├── Program.cs
     └── Api.Client.csproj
```

**Comment by vlada-shubina** [comment]
@Jaxelr 

I would assume you conditionally include / exclude projects to the template based on the command / user input correct?
I would recommend instead of 'removing the solution', only include the projects needed for solution using conditions.

if this is the case, you can use [conditional syntax](https://github.com/dotnet/templating/wiki/Conditional-processing-and-comment-syntax#single-hash-line-comments) to include or exclude the projects from solution file content; in case projects are defined in solution file content in the template definition.

If you are using "add project to solution" post action, you can also use conditions to control it (https://github.com/dotnet/templating/wiki/Post-Action-Registry#base-configuration) or conditions over `primaryOutputs`.
Also you can use [`sources`](https://github.com/dotnet/templating/wiki/Reference-for-template.json#source-definition) to exclude unnecessary files from your template. 

Simplified example of configuration may be below:

```
  "sources": [
    {
      "condition": "(useTests)",  // useTests == true
      "source": "./tests",
      "target": "./tests"
    },
    {
      "condition": "(useSrc)",
      "source": "./src",
      "target": "./src"
    },
    {
      "condition": "(useExternal)",
      "source": "./external",
      "target": "./external"
    },
   ... //other files sources
  ],
"primaryOutputs": [
    {
      "condition": "(useSrc)",  
      "path": "src/Api.csproj"        
    },
    {
      "condition": "(useTests)", 
      "path": "tests/Api.Tests.csproj"        
    },
    {
      "condition": "(useExternal)",  
      "path": "external/Api.Client.csproj"        
    },
],
//post action will only add the projects enabled via primaryOutputs
"postActions": [{
  "description": "Add projects to solution",
  "manualInstructions": [ { "text": "Add generated project to solution manually." } ],
  "actionId": "D396686C-DE0E-4DE6-906D-291CD29FC5DE",
  "continueOnError": true
}
]
```
Let me know if you have more questions.

**Comment by Jaxelr** [comment]
Thank you for the clarification @vlada-shubina
