### ISSUE TITLE
Support for multi-value choice parameter

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#4490]
The suggestion is to implement new "flavour" of choice parameter allowing multi-values. This kind of symbol may simplify selection of platforms to be generated with the template. Multi-value (choice) parameter will allow several values to pick up the platforms needed.
This approach might be reused for auth for asp.net.

To implement this requirement the following change to existing `choice` symbol is suggested:
```json
 "symbols": {
    "Platform": {
      "type": "parameter",
      "description": "The target platform(s) for the project.",
      "datatype": "choice",
      "multiValue": "true",
      "choices": [
        {
          "choice": "ios",
          "description": "Target iOS"
        },
        {
          "choice": "android",
          "description": "Target Android"
        },
        {
          "choice": "catalyst",
          "description": "Target MacCatalyzt"
        }
      ],
      "defaultValue": "ios|android" //two values are split by |
    }
}
```

Such parameter can be added by user as `dotnet new template --platform ios android`. Suggested implementation for IDE: multi-picker.
It may be used in the conditions as `Platform == "ios"` or `Platform == android`. These conditions will be true if the value was set by user.

Example above doesn't have a way to utilize replacement for this kind of symbol. But if it's required, the following suggestion apply:
```json
 "symbols": {
    "Platform": {
      "type": "parameter",
      "description": "The target platform(s) for the project.",
      "datatype": "choice",
      "multiValue": "true",
      "choices": [...],
      "defaultValue": "ios|android", //two values are split by |
      "replaces": "%PLATFORM%",
      "multiValueSeparator": "|"
    }
}
```
In case of user input:` dotnet new template --platform ios android catalyst`, `%PLATFORM%` in template content will be replaced by `ios|android|catalyst`.
Tab completion in `dotnet new` should be adapted to support multi-value.

**Comment by phenning** [comment]
When calling from API, we pass in a dictionary of <string, string?> 

How should we pass multiple parameters in from the IDE? I'm assuming just joining them all with MultiValueSeperator?

Do we need to handle/encode a case where the name of the choice contained the value separator?

**Comment by JanKrivanek** [comment]
@phenning Phil can you please point me to API you are using? I'll add explicit unit test so that we have this case covered in CI

**Comment by phenning** [comment]
Here:

https://github.com/dotnet/templating/blob/806e7eb18b878dbd1209564ab38cfbe8c976b507/src/Microsoft.TemplateEngine.Edge/Template/TemplateCreator.cs#L50

**Comment by JanKrivanek** [comment]
Thank you for pointing.
Currently for this case the separator is implicit and not configurable (it's `|` and `,`, alternatively if none of those are present in parameter marked as multichoice (`allowMultipleValues:true`) then spliting on whitespaces is attempted).
Configuration or escaping of separators is not currently planned. Please let me know if you have concerns with this.

Btw. here is PR with proposal of the feature (it's described more from the point of CLI, but still might be helpful): https://github.com/dotnet/templating/pull/4567

**Comment by phenning** [comment]
Thanks for sharing the link.

A few concerns:
1. Changing the datatype to multichoice will break VS will handle these parameters as text fields. We currently use the dataType to determine our control type, and if unrecognized we treat it as a Text field (unfortunate - we should have just used the presence of  non null choices to consider this). This is especially concerning for Framework - as we treat that as a special parameter to drive things where we expect it to behave like a switch statement.

2. Even absent that, even if we had done that, changing the default value to allow multiple values causes an issue in trying to choose the default to select in a combo impossible.

We really need to consider the VS implications around backwards compatibility here and make sure that.  We likely will not be able to update Visual Studio with .NET 7 based template engine as soon as we would like, especially closer to GA. So templates must be careful to not use things from the template engine which are not supported in VS. 

For full compat, we should ideally:

1. Not change the dataType, instead, add a flag to indicate multichoice like Vlada has here.
2. Default value should remain a single choice, instead, add a second multiDefaultValue, so that hosts that support multichoice can use it instead, falling back to defaultValue if not present.

**Comment by JanKrivanek** [comment]
Thank you for feedback. 

The 1) is adressed (type remains `choice`, there is additional flag - `allowMultipleValues`, indicating the ability to accept multiple values). There is one instance in documentation changes where this is not reflected properly - I'm updating that. For 2) I see the concern - let's discuss and adress during todays sync
