### ISSUE TITLE
Enable using .NET SDK templates with Visual Studio

### ISSUE THREAD

**Issue by richlander** [dotnet/templating#4686]
There should be a way to use .NET SDK templates (`dotnet new -i`) with Visual Studio. I don't believe there is any such experience.

This issue would be best served by such a capability: https://github.com/dotnet/iot/issues/1173

**Comment by baronfel** [comment]
@phenning after installing these templates, the templatecache.json for the VS provider has the following data for the three templates here:

<details>
<summary>templatecache.json snippet of the three template configs</summary>
```json
{
            "Parameters": [
                {
                    "Documentation": "",
                    "Name": "DbContextName",
                    "Priority": 2,
                    "Type": "parameter",
                    "IsName": false,
                    "DefaultValue": "ApplicationDbContext",
                    "DataType": "string",
                    "DefaultIfOptionWithoutValue": null,
                    "Choices": null,
                    "Description": "",
                    "DisplayName": ""
                }
            ],
            "MountPointUri": "C:\\Users\\chethusk\\.templateengine\\packages\\Korzh.EasyQuery.AspNetCoreTemplates.4.3.1.nupkg",
            "Author": "Korzh.com",
            "Classifications": [
                "EasyQuery/View/Controller"
            ],
            "DefaultName": null,
            "Description": "",
            "Identity": "EasyQuery.AdvSearch",
            "GeneratorId": "0c434df7-e2cb-4dee-b216-d7c58c8eb4b3",
            "GroupIdentity": "EasyQuery.Templates.EasyQueryAdvancedSearch",
            "Precedence": 0,
            "Name": "EasyQuery Advanced Search View",
            "ShortNameList": [
                "eq.view.advsearch"
            ],
            "ConfigPlace": "/content/EasyQuery.AdvancedSearch/.template.config/template.json",
            "LocaleConfigPlace": null,
            "HostConfigPlace": null,
            "ThirdPartyNotices": null,
            "BaselineInfo": {},
            "TagsCollection": {
                "language": "C#"
            },
            "HostData": null
        },
        {
            "Parameters": [
                {
                    "Documentation": "",
                    "Name": "DbContextName",
                    "Priority": 2,
                    "Type": "parameter",
                    "IsName": false,
                    "DefaultValue": "ApplicationDbContext",
                    "DataType": "string",
                    "DefaultIfOptionWithoutValue": null,
                    "Choices": null,
                    "Description": "",
                    "DisplayName": ""
                },
                {
                    "Documentation": "The name of the model class for which we create a view with the full text search functionality",
                    "Name": "ModelClassName",
                    "Priority": 2,
                    "Type": "parameter",
                    "IsName": false,
                    "DefaultValue": "ModelClassName",
                    "DataType": "string",
                    "DefaultIfOptionWithoutValue": null,
                    "Choices": null,
                    "Description": "The name of the model class for which we create a view with the full text search functionality",
                    "DisplayName": ""
                }
            ],
            "MountPointUri": "C:\\Users\\chethusk\\.templateengine\\packages\\Korzh.EasyQuery.AspNetCoreTemplates.4.3.1.nupkg",
            "Author": "Korzh.com",
            "Classifications": [
                "EasyQuery/View/Controller"
            ],
            "DefaultName": null,
            "Description": "",
            "Identity": "EasyQuery.FullTextSearch",
            "GeneratorId": "0c434df7-e2cb-4dee-b216-d7c58c8eb4b3",
            "GroupIdentity": "EasyQuery.Templates.EasyQueryFullTextSearch",
            "Precedence": 0,
            "Name": "EasyQuery FullTextSearch View",
            "ShortNameList": [
                "eq.view.textsearch"
            ],
            "ConfigPlace": "/content/EasyQuery.FullTextSearch/.template.config/template.json",
            "LocaleConfigPlace": null,
            "HostConfigPlace": null,
            "ThirdPartyNotices": null,
            "BaselineInfo": {},
            "TagsCollection": {
                "language": "C#"
            },
            "HostData": null
        },
        {
            "Parameters": [
                {
                    "Documentation": "",
                    "Name": "DbContextName",
                    "Priority": 2,
                    "Type": "parameter",
                    "IsName": false,
                    "DefaultValue": "ApplicationDbContext",
                    "DataType": "string",
                    "DefaultIfOptionWithoutValue": null,
                    "Choices": null,
                    "Description": "",
                    "DisplayName": ""
                },
                {
                    "Documentation": "The name of the model class for which we create a view with data filtering functionality",
                    "Name": "ModelClassName",
                    "Priority": 2,
                    "Type": "parameter",
                    "IsName": false,
                    "DefaultValue": "ModelClassName",
                    "DataType": "string",
                    "DefaultIfOptionWithoutValue": null,
                    "Choices": null,
                    "Description": "The name of the model class for which we create a view with data filtering functionality",
                    "DisplayName": ""
                }
            ],
            "MountPointUri": "C:\\Users\\chethusk\\.templateengine\\packages\\Korzh.EasyQuery.AspNetCoreTemplates.4.3.1.nupkg",
            "Author": "Korzh.com",
            "Classifications": [
                "EasyQuery/View/Controller"
            ],
            "DefaultName": null,
            "Description": "",
            "Identity": "EasyQuery.GridFilter",
            "GeneratorId": "0c434df7-e2cb-4dee-b216-d7c58c8eb4b3",
            "GroupIdentity": "EasyQuery.Templates.EasyQueryGridFilter",
            "Precedence": 0,
            "Name": "EasyQuery GridFilter View",
            "ShortNameList": [
                "eq.view.gridfilter"
            ],
            "ConfigPlace": "/content/EasyQuery.GridFilter/.template.config/template.json",
            "LocaleConfigPlace": null,
            "HostConfigPlace": null,
            "ThirdPartyNotices": null,
            "BaselineInfo": {},
            "TagsCollection": {
                "language": "C#"
            },
            "HostData": null
        }
```
</details>

I've tried a few searches based on the short name, long name, tag collections, etc, but none cause the template to appear in the list. I also notice a few other templates that I have installed (like Falco and MiniScaffold) that don't show up in VS - is there some critical piece of information missing in template that would cause this behavior? I see these in the CLI listings.

**Comment by sayedihashimi** [comment]
I noticed that these templates don't have a `$.tags.type` declared (typically it's set to Project).

In VS, we do support templates that don't have a `$.tags.type`. We try to infer it. We will use Project if we see a *.*proj file in the folder containing `.template.config`, and we will assume `solution` if we see a .sln folder there.

In the case of these templates, there is no .csproj or .sln in the same folder containing the `.template.config`. So I wouldn't expect these to appear in VS because we cannot make sense of it.

![image](https://user-images.githubusercontent.com/1283154/167023627-d26bd52b-2f75-4ab3-8eb1-e7aaa767016e.png)

**Comment by baronfel** [comment]
Interesting - so as I'm looking at these templates they feel almost more like item templates for specific kinds of pages. Do .NET Templates integrate in VS with the New Item dialog?

**Comment by sayedihashimi** [comment]
For item templates it’s not technically supported yet. We have enabled a way for MAUI, but the implementation will change when constraints are in place. We are waiting until then to formally support them.

**Comment by baronfel** [comment]
Excellent! Ok then, I'm looking forward to taking another look at this issue as constraints land. Thank you for the clarification!

In our docs for template authors on this wiki and on docs.ms.com, is the rule above solid enough to codify for end users? We don't have guidance on 'making your template appear in editors', but I'd be happy to write it up if there's a known list of things to do.

**Comment by sayedihashimi** [comment]
@baronfel take a look at https://aka.ms/netcore-templates for additional info.

**Comment by baronfel** [comment]
Every time you point me to your template validation repo I get the itch to add its feature set to our msbuild template tasks in this repo.

**Comment by vlada-shubina** [comment]
@richlander is objective of original issue to allow users to install template packages from Visual Studio (besides `dotnet new install` way)? If so, I'll move the ticket to VS repo. 

The `type` issue might be solved by validation https://github.com/dotnet/templating/issues/3828 or constraints https://github.com/dotnet/templating/issues/3107 depending on expected behavior (if the template should be allowed in VS or not).

**Comment by phenning** [comment]
There are several separate issues here.

1. The original feedback issue that @richlander linked had to do with dotnet/iot and the directory based templates note being available in Visual Studio. This is now supported in Visual Studio 2022. This feedback issue could now be resolved.

2. There is some confusion about the metadata which needs to be supplied for projects to show up in Visual Studio, the "EasyQuery" templates don't seem to have any $.tags.type declared which is why they don't show up at all. This is an authoring problem, not a product issue, customers could be pointed to the validation tool or the build task when it exists.

3. For $.tags.type = item, like @sayedihashimi said, we support this today in Visual Studio 2022, but there is additional metadata that needs to be defined via the host file for it to show up. The metadata controls where in the hierarchy the template shows up, a capabilities filter for restricting to particular project types (optional) and the extension to use in combination with defaultName (required for auto numbering of default names in the new item dialog). We should have another discussion on whether we want to formerly support this outside of Maui scenarios now.

**Comment by richlander** [comment]
> This is now supported in Visual Studio 2022. This feedback issue could now be resolved.

Great. Thanks!

@Ellerbach @shaggygi

**Comment by baronfel** [comment]
So, action items for this issue in particular seem to be:
* better documentation about authoring/[linking to existing authoring resources](https://github.com/dotnet/docs/pull/29654)
* creating tools that can do some of this validation on our behalf. @sayedihashimi actually has made a package that does this validation, and I've implemented it in a community template [here](https://github.com/TheAngryByrd/MiniScaffold/pull/260). There are some UX things we should work out on Sayed's package, but these are minor and I think we could really get some value out of the package here.

**Comment by richlander** [comment]
It would also be good to document (both docs and blogs) about what template _users_ can expect from templates with VS.

**Comment by shaggygi** [comment]
@richlander  thanks for looking into the issue.  I had no idea it was added in VS17.  👍

the following adds it to the dialog.

```dotnet new -i C:\[PATH]\iot\tools\templates\DeviceBindingTemplate\dotnet_new_device-binding_csharp```

<img width="558" alt="image" src="https://user-images.githubusercontent.com/2956825/170797090-d0597d18-81be-40a1-a471-d50411c867da.png">

**Comment by vlada-shubina** [comment]
@baronfel updated docs with the reference in https://github.com/dotnet/docs/pull/29654

Validation tooling is tracked in https://github.com/dotnet/templating/issues/3828, until that's done we recommend to use [this ](https://github.com/TheAngryByrd/MiniScaffold/pull/260) tooling

**Comment by DavidBoike** [comment]
@sayedihashimi:

> For item templates it’s not technically supported yet. We have enabled a way for MAUI, but the implementation will change when constraints are in place. We are waiting until then to formally support them.

And @phenning:

> For $.tags.type = item, like @sayedihashimi said, we support this today in Visual Studio 2022, but there is additional metadata that needs to be defined via the host file for it to show up. The metadata controls where in the hierarchy the template shows up, a capabilities filter for restricting to particular project types (optional) and the extension to use in combination with defaultName (required for auto numbering of default names in the new item dialog). We should have another discussion on whether we want to formerly support this outside of Maui scenarios now.

I gather from these comments that item templates showing up in Visual Studio is still somewhat of a special case for MAUI only. Is there an issue somewhere tracking general scenarios outside MAUI?

**Comment by sayedihashimi** [comment]
Hi @DavidBoike I spoke with @phenning today regarding this.

We haven't done the work on our side to formalize the support for Item Templates that use the Template Engine constraints. Since we have a lot of other important work that we are doing, we will not be able to get to implementing that for a while.

Because of that, we have decided that we will make public the support that we currently have and make that supported.

@phenning can you give a pointer to some example Item Templates that @DavidBoike can look at to implement the templates? 

I can work on getting some docs created for this as well.

**Comment by DavidBoike** [comment]
@sayedihashimi that would be great, thanks!

**Comment by DavidBoike** [comment]
@phenning Any idea when I could get a link for those example item templates? I would love to work this into our latest release but I'm running out of time to work on it. While documentation would be nice, I'm guessing I could get things going with just a peek at a few examples.

**Comment by phenning** [comment]
> @phenning Any idea when I could get a link for those example item templates? I would love to work this into our latest release but I'm running out of time to work on it. While documentation would be nice, I'm guessing I could get things going with just a peek at a few examples.

First you need to specify "type": "item" in the tags of your template.json:

You'll also need to add an ide.host.json file next to your template.json, with at least the following values. This is an example of a MAUI item template.

```
{
  "$schema": " https://json.schemastore.org/ide.host",
  "appliesTo": "UseMaui",
  "defaultItemExtension": "cs",
  "itemHierarchyPaths": [ "Maui" ]
}
```

The key thing is specifying an **itemHeirchyPath** in the ide.host.json, the presence of this is what triggers us to show the item template in Visual Studio.

For **defaultItemExtension**, this should be cs, or whatever the item template's extension is for the primary file.

**appliesTo** is a project capability expression that must match in the project for this template to be shown in the item dialog. Note that we automatically filter on the ".NET" project capability as well, since this is only intended for .NET Core CPS based projects.

**itemHierarchyPaths** is an array of strings which control which node, I can provide more details, but this is pretty self-explanatory.
 
You’ll probably also want to do the following in the template.json as well:
•	Add a primary outputs and the open file in editor post action to open the generated file(s) to the template.json.


ItemHierarchyPath notes:
You can specify something like "itemHierarchyPaths": [ "AspNetCore/General", "AspNetCore/Data" ] to have the template appear in multiple nodes.

Also, we treat some path segments as tokens in order to provide localization (as of 17.7)
AspNet  = "ASP.NET"
AspNetCore = "ASP.NET Core"
Code = "Code"
Content = "Content"
Data = "Data"
General = "General"
Markup = "Markup"
Scripts = "Scripts"
Web = "Web"
WebForms = "Web Forms"

The maui item template is here;
[maui/src/Templates/src/templates/maui-contentpage-csharp at main · dotnet/maui · GitHub](https://github.com/dotnet/maui/tree/main/src/Templates/src/templates/maui-contentpage-csharp)

**Comment by DavidBoike** [comment]
Thanks @phenning, that's what I needed!

![image](https://github.com/dotnet/templating/assets/427110/8bb197d6-c9fa-42fd-b825-4fbe82fe3d69)
