### ISSUE TITLE
Readme.md says "new3" everywhere. Does that need to be updated?

### ISSUE THREAD

**Issue by shanselman** [dotnet/templating#480]
Readme.md says "new3" everywhere. Does that need to be updated? Happy to do it, just wanted to understand.

**Comment by chad-ramos** [comment]
@shanselman The way I view it is that the readme is focused on working with builds directly from this repository.  Being that there is no official documentation yet, I agree that this can be confusing to those jumping on board.

**Comment by mlorbetske** [comment]
As @chad-ramos mentions, `new3` is the command that gets built when building this repo from source, but it is close enough to `new` to be confusing.

@sayedihashimi thoughts?

**Comment by sayedihashimi** [comment]
@shanselman the readme is broken into two high level sections:

 1. Info for `dotnet new` users
 2. Info for template authors & those who build with latest

In *1* we use `dotnet new`

In *2* we instruct users how to build from source, which enables `dotnet new3`. We don't override `dotnet new` so that users can still have the stable version of `dotnet new`. In that section we use `dotnet new3` and I believe that's the correct approach.

Also considering that users are reading the github readme I think they will be interested in building and running the latest.

@shanselman thoughts?

**Comment by shanselman** [comment]
Gotcha. I feel that it'd be clearer if this sentence

> 
A new command dotnet new3 will be enabled which allows you to create files with the latest Template Engine.

was called out more. Like, it's just a sentence in the middle there. Maybe punch that up a bit?
