### ISSUE TITLE
Solution Templates output to wrong path in Visual Studio

### ISSUE THREAD

**Issue by Arthri** [dotnet/templating#4840]
I have a solution template that looks like this:
```
Solution.sln
Top-Level-File.txt
src/
  Project/
    Project.csproj
```
When creating a template through the .NET CLI, it mirrors the above folder structure. However, when doing the same in Visual Studio, it generates this instead:
```
Solution.sln - Visual Studio generated
Solution/
  Solution.sln - Original solution. Visual Studio deletes this shortly after creating the template
  Top-Level-File.txt
  Project/
    Project.csproj
```

My guess is this has something to do with "Place solution and project in the same directory". How can I workaround this? I need the files inside `Solution/` to be at the top level

**Comment by vlada-shubina** [comment]
this looks similar to https://github.com/dotnet/templating/issues/4654. 
Some explanation is also here: https://github.com/sayedihashimi/template-sample#how-to-create-a-multi-project-solution-template

iirc, there is no way to do it in Visual Studio unfortunately. 
@phenning, @sayedihashimi could you please confirm?

**Comment by phenning** [comment]
Since these are essentially project templates as far as Visual Studio is concerned, the project structure will always be relative to the project output folder, not the solution root folder. Checking "Place solution and project in the same directory" will more closely match your desired structure. Unfortunately, there is not a way to force that behavior. You should consider though how your template will behave if you add it to an existing solution as well. 

In  Visual Studio 17.2 and beyond you can bind to some custom host properties in order to modify your paths via source renames:
The following properties are available:

context:CreateSolutionDirectory - Set to true if the "place solution and project in the same folder" is not checked. 
context:IsExclusive - Set to true if this is a new template location into a new solution. False if it is being added to an existing solution.
context:SolutionName - The name of the solution.

You an reference these in template.json like the following:
    "IsNewSolutionProject": {
      "type": "bind",
      "binding": "context:IsExclusive"
    },

**Comment by Arthri** [comment]
Thanks for the replies! I understand that changing the default behavior would be massive, so I'm not really after that. I came from #4654 and I created this issue because it closed without workarounds. Anyways, I'm happy to hear about the context bindings, they were exactly what I'm looking for

By the way, is there documentation on the `context:*` bindings? I searched the .NET organization and this issue seems to be the only mention of them

Thanks again!
