### ISSUE TITLE
--package template parameter has changed to --param:package in .NET 5

### ISSUE THREAD

**Issue by vytas-dauksa** [dotnet/templating#5198]
One of our templates accepts `--package` template parameter, which worked fine in .NET 3.1, however since .NET 5 it's now changed to `--param:package`. I suspect `package` became a reserved keyword, but I am not able to find any documentation about such backward incompatibilities. Where could I learn more about this?

**Comment by vlada-shubina** [comment]
We introduced `--package` in .NET 5.0, and it became a reserved option. Basically all options described in https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new and children pages are reserved.

However, since .NET 7.0 we moved to new parser that allowed us to do subcommands. Since .NET 7.0 only parent command options and options that required for instantiations are reserved. 

It's not documented anywhere, we need to create an article on this.
