### ISSUE TITLE
Complex templates

### ISSUE THREAD

**Issue by dansiegel** [dotnet/templating#524]
I know you can currently pass flags to templates such as `dotnet new mvc -au Individual`. Is there any documentation on how to use this for custom templates. 

A couple of use cases:
- A template that could scaffold out a WebApi but have options to include an Angular SPA as a separate project and/or a Unit Test project, and/or a WebJob project
- A template that could scaffold out a Xamarin Forms project with options for which Platforms to include (iOS, Android, UWP), or whether to include a mobile backend, or whether to include UI tests
- Another complex scenario (and entirely different approach)... say I want to have some json spec like below where the template engine could scaffold out my models, and my DbContext, add it to my Startup class, and generate the ApiControllers for the Customer and Product. Would there be a way to even do this?

```json
{
  "UseEntityFramework" : true,
  "Models": [
    "Customer",
    "Product"
  ]
}
```

**Comment by mlorbetske** [comment]
The docs for symbols are [here](https://github.com/dotnet/templating/wiki/%22Runnable-Project%22-Templates#symbols-optional) - the actual configuration for `-au|--auth` is [here](https://github.com/dotnet/templating/blob/rel/vs2017/post-rtw/template_feed/Microsoft.DotNet.Web.ProjectTemplates.1.x/content/StarterWeb-CSharp/.template.config/template.json#L44-L59).

Using them to include/exclude particular features is documented [here](https://github.com/dotnet/templating/wiki/%22Runnable-Project%22-Templates#sourcesmodifiers-optional) - a usage example of this can be found in the templates [here](https://github.com/dotnet/templating/blob/rel/vs2017/post-rtw/template_feed/Microsoft.DotNet.Web.ProjectTemplates.1.x/content/StarterWeb-CSharp/.template.config/template.json#L20-L33) and the computed symbol that takes its value from a comparison with `auth` is [here](https://github.com/dotnet/templating/blob/rel/vs2017/post-rtw/template_feed/Microsoft.DotNet.Web.ProjectTemplates.1.x/content/StarterWeb-CSharp/.template.config/template.json#L64-L67). Code that reasons about the template parameter is [here](https://github.com/dotnet/templating/blob/rel/vs2017/post-rtw/template_feed/Microsoft.DotNet.Web.ProjectTemplates.1.x/content/StarterWeb-CSharp/Startup.cs#L26-L44) (it uses a different computed symbol `IndividualAuth` rather than `NoAuth` referred to in the previous link).

The third item here isn't something the engine currently does. The short version of the answer is that we're working on bringing scaffolding type features (and dynamic data features) in, but they won't be in for a while as there's a fair amount of design to do for it yet (#394 and #286 drive at the same goal). We should continue the conversation for "scaffolding" type features there (#394 for the ways we might want to represent source data and #286 for discussing the extensibility points that can be leveraged to add features that are very specific to a particular template or set of templates).

It is worth noting though that "runnable project generator" does not currently look at any data already existing in the output structure (and there aren't any concrete plans for it to so, as "scaffolding" type features - like the ones found in https://github.com/aspnet/scaffolding - would be implemented as a separate generator with syntax better suited to scaffolding type tasks than the runnable project generator syntax is) - which reduces the applicability of #286, but it may point at something that would meet your needs. The dynamic data type features that we're looking at have to do with collecting a template author or user specified data source, interpreting it and performing some sort of iteration over that source to repetitively pattern a section of code with standardized but highly configurable operations. Scaffolding (using https://github.com/aspnet/scaffolding as my point of reference) tends to be much more connected to the project and the operations it performs to generate the content are highly customized for both generating the specific content the user requested and getting it from the particular source the scaffolder operates on - making them poor candidates for generalization. We've also been working toward finding a way to get https://github.com/aspnet/scaffolding exposed as a Template Engine "generator" directly as well, which should unblock many of these use cases.

**Comment by sayedihashimi** [comment]
I have a new blog post on how to create templates at http://aka.ms/dotnetnew-create-templates

**Comment by dansiegel** [comment]
@mlorbetske Great resources thank you!
@sayedihashimi Awesome blog, also very helpful!

A couple of things I was noticing. The readme currently mentions that you can use compiler directives for conditionally including content say in a class. I think having a link to the "Runnable Project" template as @mlorbetske provided above would be a valuable addition. Also the following items, are a couple of areas where I think the documentation is particularly thin:

1) Handling conditions in a csproj file. From experience and cheating by looking at your templates, I can deduce that the correct way is to use a Conditional attribute on the element I want to evaluate in my template. I can see this really stumping people though.

2) I haven't really seen anything documenting the scenario where you have a template that depending on conditions could generate one or more projects such as a class library and a unit test project, and you would like to generate a solution file for that project.

**Comment by sayedihashimi** [comment]
@dansiegel thanks for the reply. For your "2", creating a multi-project template is no different from a single project template. You just have to move the `.template.config` folder up to the .sln file folder. For your class lib + test project you would need to:

 1. Create a multi-project template
 1. Add a parameter to include the test project
 1. Update the .sln file to have preprocessors. (Note: this may make the .sln file into a non-runnable format. I don't think .sln file has comments but not sure).
 1. Update `template.json` to exclude the test project based on the parameter

For the doc situation, I think the easiest thing we can do in the short term is to create a new repo which contains template samples. I think this would be easy to put together, the community can help, and we can use these samples in the docs we create as well.

For my blog post I created https://github.com/sayedihashimi/dotnet-new-samples/. We could use that as a starting point, but I'd like to get a repo into an official Microsoft org (more specifically in this organization). Thougths?

**Comment by dansiegel** [comment]
@sayedihashimi I would assume that would be the case. In my case it may take a little more playing with it to get something working. I just see those two particular cases being something that would really stumble a lot of people who may want to author a template. I really like your idea of having a home for template samples. I think the community will really benefit from that. Sometimes it just makes more sense when you look at a working example than a technical "how to".

**Comment by sayedihashimi** [comment]
FYI samples repository created at https://github.com/dotnet/dotnet-template-samples. I've also created a multi-project template sample at https://github.com/dotnet/dotnet-template-samples/tree/master/05-multi-project.

@dansiegel can we close this issue, or is there still pending work/questions here?

**Comment by dansiegel** [comment]
@sayedihashimi I'm going to close the issue. Just an observation, I do think it would be good to show the sln file generated in the  multi-project template. From what I've seen, VS & VS for Mac would eventually use this tooling, and they would both need solution files generated.
