### ISSUE TITLE
Applicationurl shouldn't randomly generate port 5060 or 5061

### ISSUE THREAD

**Issue by sammychinedu2ky** [dotnet/templating#5379]
I noticed a little error.
Port 5060 and 5061 aren't allowed by new browser versions due to the [natslip attack](https://chromestatus.com/feature/5064283639513088) (https://chromestatus.com/feature/5064283639513088). Port 5060 was randomly created for me in the `launchSettings.json` file which made me have issues accessing my API from the browser. I had to change the `applicationUrl` port manually.

if I can be shown the line where the port generation is done in the dotnet SDK, I would also appreciate it. Thanks

**Comment by kasperk81** [comment]
not auto generating blocked port is one part, other part is getting a diagnostics on app startup if any blocked port is in ApplicationUrls. startup code is in aspnetcore repo.

**Comment by Tratcher** [comment]
> not auto generating blocked port is one part, other part is getting a diagnostics on app startup if any blocked port is in ApplicationUrls. startup code is in aspnetcore repo.

Is that a common problem? Developers will either use the randomly generated ports or set their own. These specific ports are only blocked in browsers, right? They'd be fine for other clients for local development? In production it also isn't likely to be relevant, developers would use port 80/443 when interacting publicly with browsers.

**Comment by phenning** [comment]
All the port generation is done in a template engine generator on creation via the following, not from either of the host. One of the issues here though is that even though it would be fixed in the template engine generator, we would not have that fix available until VS was updated with that dependency.  I don't believe there is anything for us to do in VS/VSMac other than consume updated template engine binaries.

It would be nice if the port generator supported a passable exclusion range as a parameters, so that if there are additional ports in the future that need to be excluded, fixes could be made in the templates until an engine update can be made/inserted.

```
    "kestrelHttpPortGenerated": {
      "type": "generated",
      "generator": "port",
      "parameters": {
        "low": 5000,
        "high": 5300
      }
    },
```
