### ISSUE TITLE
Excluding source control configuration

### ISSUE THREAD

**Issue by mattkirschner** [dotnet/templating#5544]
My template project is connected to TFS source control and I'm having a heck of a time removing all the related bindings from new projects using this template. Right now, creating a new project results in a prompt stating that "The solution you are opening is bound to source control on...".

I think the crux of the issue seems to be with a few lines in the .sln file that need to be removed. Is there any documentation on how to edit the solution file during template install?

**Comment by vlada-shubina** [comment]
@mattkirschner could you please share the full template that has the issue? it might be simplified if you'd like to not to disclose it.

Couple of thoughts:
- if it's caused by extra line in sln, one of the ways may be to remove the line before publishing the template
- another way to may be do condition the line causing the problem as explained in https://github.com/dotnet/templating/wiki/Conditional-processing-and-comment-syntax#single-hash-line-comments. If you put it in condition that always results to `false`, the line won't be generated when instantiating the template.

**Comment by vlada-shubina** [comment]
Closing to inactivity.
