### ISSUE TITLE
Developers are informed of known package security vulnerabilities with UPDATE/UNINSTALL option

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/templating#5863]
# Background
Show known security vulnerabilities of a package and offer to update/uninstall (as part of update check). This requires API support from nuget.org

# Justification
- Aligns to the secure supply chain with NuGet theme

**Comment by YuliiaKovalova** [comment]
Our proposal for implementation:
Save in the cache a flag that identifies if there are any vulnerabilities presented in the package.
Display the list of the vulnerabilities on request - probably add a new subcommand for getting this info.

on install / update check if vulnerable - do not allow installation if  package is vulnerable and `--force` isn't specified
**Open question**: how to indicate package vulnerability on search call.

@baronfel , we invite you to discussion.

**Comment by baronfel** [comment]
The big question I have is - how do we detect vulnerability in a template package? Are there template packages that themselves have nuget dependencies? or do the projects _generated_ by the templates ship vulnerable versions? If the latter, then we somehow have to know what those packages and versions are so that we can ask NuGet if any of them are vulnerable.

**Comment by YuliiaKovalova** [comment]
We don't have much information here.
@baronfel , do you have a contact point from nuget side for getting info on how these vulnerabilities are declared?
