### ISSUE TITLE
Code surrounded by #if DEBUG statements is removed when creating a project from template

### ISSUE THREAD

**Issue by alfonsogarciacaro** [dotnet/templating#587]
In the Fable.Template.Elmish.React we have [some code surrounded by `#if DEBUG` statements](https://github.com/fable-compiler/fable-elmish/blob/acbc9c2bc74dcce1e2fec3f9fa1dd843db84957a/src/templates/react/Content/src/App.fs#L75-L77). However when generating a project using the template (`dotnet new fable-elmish-react -n myproject`) these lines get removed from the generated files. Is this intended, can it be avoided?

**Comment by sayedihashimi** [comment]
@mlorbetske is this because we have a hidden --debug switch? If so any workaround they can apply until we may be able to fix it?

**Comment by mlorbetske** [comment]
@sayedihashimi this is not related to any `--debug:*` directives. When we fully switch over to the new evaluator (where we'll need to determine the condition end in a form other than "it's a single token" or brace balancing), we'll do the same trick we do with the MSBuild evaluator to determine whether all symbols involved are defined in template.json. This work is tracked in #51.

@alfonsogarciacaro For evaluators other than the MSBuild evaluator, all directives that activate conditional are assumed to be directives for the engine unless condition processing is turned off locally. You can turn off condition processing for a block with `//-:cnd:noEmit` and `//+:cnd:noEmit` (which turn it off or on respectively & do not emit the token for the flag).

Note that for the 1.x CLI, this won't work correctly, you'll need to use `//-:cnd` and `//+:cnd` because these tokens weren't correctly mapped in that build.

See #432 for more context. The mapping token mapping issue is fixed in #433 and will ship with the dotnet CLI 2.0.

**Comment by alfonsogarciacaro** [comment]
Thanks for the answer @mlorbetske! The `//-:cnd` trick should do for now. And sorry for the duplication, I did search for `DEBUG` in the issues but forgot to check the closed ones :/
