### ISSUE TITLE
`dotnet new` emits files with two periods before extension

### ISSUE THREAD

**Issue by heaths** [dotnet/templating#5955]
### Describe the bug
Now that we've upgraded our repo requirements a la _global.json_ to .NET 7.0.11, our `dotnet new azsdkdbg` now emits files with two periods before the extension e.g., "Azure.Template..csproj", "Azure.Template..sln", etc.

### To Reproduce
1. Shallow clone the https://github.com/Azure/azure-sdk-for-net repo:
   ```bash
   git clone --depth=0 https://github.com/Azure/azure-sdk-for-net.git
   ```
2. Install the template:
   ```bash
   dotnet new install sdk/template
   ```
3. Use the template:
   ```bash
   dotnet new azsdk -o sdk --serviceDirectory test --groupName dotnet --clientName TestClient
   ```

### Exceptions (if any)
No exception, but show the files in the sdk/dotnet directory example `tree /f` and notice a number of generated files with ".._extension_" e.g., _sdk/dotnet/test/Azure.dotnet..sln_.

### Further technical details
This was working under previous SDK versions. See https://github.com/Azure/azure-sdk-for-net/tree/957a870c86b61c8f698d9915812a1575874545fa/sdk/template for the current template used in this issue.

**Comment by YuliiaKovalova** [comment]
Hi @heaths,

I took a closer look at your template and found this part causes the mentioned error: 
[ClientNameCapitalCase](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/template/.template.config/template.json#:~:text=%7D%2C-,%22ClientNameCapitalCase%22%3A%20%7B,-%22type%22%3A) references **C**lientName, instead of **c**lientName specified [above](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/template/.template.config/template.json#:~:text=%7D%2C-,%22clientName%22%3A%20%7B,-%22type%22%3A). 

It worked in .Net 6.0 because this ref symbol parsing wasn't case-sensitive (.ClientName vs clientName were considered equivalent)
So we strongly recommend you adjust the template to the changes in .Net 7.0 because it doesn't work as expected now.
