### ISSUE TITLE
Recover from corupt/missing packages.json

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/templating#6128]
### Is your feature request related to a problem? Please describe.

Corupt `packages.json` file leads to errors and burden of fixing is up on user.

### Describe the solution you'd like.

In ideal case this would be handled same as problems with `templatecache.json` - via recreating the file from scratch.
`packages.json` contains info from packages that are located in TE settings folder in `packages` folder - so it should be possible to crawle all the packages there and recreate the file. A warning might be handy in this case as operation might take a bit of time - so that user is aware that this is an exceptional situation (probably caused by some preceding manual intervention).

### Additional context

Related issues:
* https://github.com/dotnet/templating/issues/5972
* https://github.com/dotnet/templating/issues/5203

**Comment by baronfel** [comment]
Instead of recreating (which is also a good idea!) we should consider doing any writes to the cache in a two-phased manner:

* write any updates to a new template cache json in a temp location
* atomically move the new template cache json to the final location once it is completely written
* consider locking of this move operation across processes (via a lock file or equivalent)

**Comment by JanKrivanek** [comment]
The recreation of the file was meant for cases where the file gets manipulated and corrupted outside of control of the TE (e.g. via attempted manual changes).
But phasing the edits and guarding by mutex (already guarded IIRC) is a great idea - should be fairly simple and capable to resolve majority of problems with the packages.json lookup

**Comment by YuliiaKovalova** [comment]
close as low priority & corner case
