### ISSUE TITLE
Make Symbol Parameters Case-Insensitive

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/templating#634]
I've just realized that the `dotnet new` CLI is case sensitive when referring to the symbol names e.g.

`dotnet new mytemplate --name Foo --MySymbol MySymbolValue`

In this case I'm using a TitleCase symbol name and value which makes sense in `#if` pre-processor directives. However, in the CLI, I if I specify them in lower-case I get an error:

`dotnet new mytemplate --name Foo --mysymbol mysymbolvalue`

Doing a `dotnet new mytemplate --help` shows the TitleCase names. I think using lower-case symbol names should be allowed.

**Comment by mlorbetske** [comment]
@seancpeters can you get a feel for what's involved for doing this?

We currently support making the presentation of the template parameters consistent with the presentation environment (host) via files like [this one](https://github.com/dotnet/templating/blob/rel/vs2017/post-rtw/template_feed/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/EmptyWeb-CSharp/.template.config/dotnetcli.host.json).

**Comment by RehanSaeed** [comment]
It would be nice if the user could use any case. I don't thing using dotnetcli.host.json would give you that. One additional reason for doing this is that the name parameter is always lower case.

**Comment by mlorbetske** [comment]
Yep, I was referring to two different things. The CLI, by convention uses all lower case, hyphen separated words for full switch names and prefers (with the exception for things like -lang) single letter sort forms with lower case indicating positive use of the switch and upper case referring to the switch's inversion (ex. -m turns something on and -M explicitly turns it off). This means that the parser for the args is more than likely case sensitive (we use the same parser as the CLI itself) - which is my I've asked for this to be investigated, to see if it has a case insensitive mode or if one could be added. Since new doesn't have short form switches that have inversions (uld in mvc in the built in templates would be the best candidate at the moment), this change shouldn't break any existing templates if it is possible. I do suspect though that most people who would case mismatch a parameter like the ones you've mentioned would be trying to use an all lower case form to be consistent with the rest of the CLI, which is why I've suggested adding the host file to make the parameters match the currently used conventions while we investigate the possibility of case insensitivity.

**Comment by mlorbetske** [comment]
From the feel of the linked issue, this is unlikely to be addressed. To make things easier for the users attempting to specify the parameter names, I'd suggest using the host file to map the names that are easier to work with in the templates to ones that are easier to type at the command line.
