### ISSUE TITLE
Item Template copies .template.config

### ISSUE THREAD

**Issue by dansiegel** [dotnet/templating#769]
I'm seeing some really weird behavior when working with some Item Templates where when I create the item it also copies over the `.template.config` directory. You can see the template [here](https://github.com/dansiegel/Prism-Templates/tree/item-templates/content/XamarinItems). This results in a failure when trying to create a subsequent item since it finds a duplicate template.json and dotnetcli.host.json file.

**Comment by mlorbetske** [comment]
This is because the `.template.config` directory is excluded in the defaults for sources rather than being globally ignored ([source](https://github.com/dotnet/templating/blob/39608eb0b341175d6e1cbcaba437c70d9d3bc006/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/SimpleConfigModel.cs#L22-L32)). If instead of doing top level sources (which overrides the defaults), you used `modifiers` entries in an otherwise empty `sources` entry, it would have the same effect of excluding the different file sets but would preserve the defaults. Alternatively, the default patterns can be added back explicitly to each one of the excludes.

Top level sources are generally used to pull in different content source -> target mappings (ex. if you have defined content outside of the template directory that you wish to map in to the output directory, you'd use a source), for changing the set of files that gets included, copied, etc. based on conditions within the same source content directory, modifiers should be used instead.

**Comment by dansiegel** [comment]
changing that up to use modifiers instead fixed the problem. Thanks @mlorbetske
