### ISSUE TITLE
Azure Backend Api's

### ISSUE THREAD

**Issue by dansiegel** [dotnet/templating#781]
# Problem
A very common issue I keep hearing from the Xamarin community is a complaint that the Microsoft.Azure.Mobile.Server project only supports the classic ASP MVC and not Net Core. This is also problematic because it prevents the development of solutions that need to run off the cloud in a purely Linux environment. 

# Proposal
The new WebApi templates I believe would get you mostly there. I believe to make it stupid simple three things would need to occur. 

1) The API would need to look for an auth token with the header "X-ZUMO-AUTH"
2) Provide a [base Generic controller](https://github.com/Azure/azure-mobile-apps-net-server/blob/master/src/Microsoft.Azure.Mobile.Server.Tables/TableControllerOfData.cs)
3) Provide an [item template](https://github.com/Azure/azure-mobile-apps-quickstarts/blob/master/backend/dotnet/Quickstart/ZUMOAPPNAMEService/Controllers/TodoItemController.cs)

**Comment by mlorbetske** [comment]
I'm not very familiar with the particulars here, let's see what @sayedihashimi and @mhutch think is the best way to proceed

**Comment by sayedihashimi** [comment]
Seems like a great idea. Shouldn't this issue be on the https://github.com/Azure/azure-mobile-apps-net-server repo though? We've enabled all the features they need to create this template.
With that said, if they are not interested in creating these templates then my team may be interested. I'd like to see if they are up for it though first. Thoughts?

**Comment by sayedihashimi** [comment]
FYI related I found https://github.com/Azure/azure-mobile-apps-net-server/issues/215

**Comment by dansiegel** [comment]
@sayedihashimi I actually had raised the issue Azure/azure-mobile-apps-net-server#210 the other issue is actually a duplicate. It had also been raised here Azure/azure-mobile-apps-net-server#97. It would seem that they previously decided that it wasn't something they were going to pursue in that issue and also looks like Adrian is no longer with Microsoft so I'm not sure what's going on with the project. Considering how much more functional the WebApi template is out of the box now, I thought it might be better if it was just handled as an out of the box template that could be reused cross platform.

**Comment by mlorbetske** [comment]
Where are we on this one? Is it something we're going to pursue or are we thinking that the mobile apps folks will be doing something tailored for their service?

If we do intend to do this - do we intend to make a new template that has these customizations, change the WebAPI to always have it or add a switch to the WebAPI template that would bring these changes in?

**Comment by mhutch** [comment]
cc @pierceboggan

**Comment by RLittlesII** [comment]
Has there been any traction on this? 

@sayedihashimi can you provide any instruction or direction on how one could make the mobile service server sdk work with .NET Core? Based on your comment https://github.com/dotnet/templating/issues/781#issuecomment-301147047 it seems possible.

Everything that has been posted on the server sdk repo is leaning towards there will be no support, not a great answer for developers who are invested in this technology.

**Comment by sayedihashimi** [comment]
@RLittlesII I have moved to the Visual Studio for Mac team, so I cannot speak to this.

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by mahesh-anjani** [comment]
Is there any update on this? Will Azure Mobile Backend available for .Net Core and EF Core?

**Comment by bekir-ozturk** [comment]
cc @KathleenDollard

**Comment by baronfel** [comment]
The problem statement I'm seeing here is "users want to make servers with Azure Mobile Apps authentication".  There are three pathways that I'm seeing for resolution:

* The Azure Mobile Apps team create a .NET Template (like other teams do) that expresses their opinions on the best way to use the service. This is IMO the ideal solution - it keeps the template entirely under your control and aligned to your release schedule. The templating team would of course be on hand to offer support for developing that template.
* The Azure Mobile Apps team could work with the aspnet team to add auth support, controllers, etc to another template pack, like the existing `web` or `mvc` templates. This would be a less-than-ideal situation, as it makes the Azure Mobile Apps offering a) just one of many in the available authentication options for those templates, and b) locks you to the shipping cadence of the aspnetcore team
* We wait for more 'scaffolding' support to be built into the template engine (in whatever form that ends up taking) so that adding Azure Mobile Apps support can be done to any aspnetcore application as an additive change. This is not ideal because it has a very unclear time frame for delivery.

Having said all that, I really suggest the AMA team take the first option and author a template with our support.

**Comment by vlada-shubina** [comment]
According to https://github.com/Azure/azure-mobile-apps-net-server/issues/215 Azure Mobile Apps is not adding any new features to the product, as well as never supported .NET core, so suggesting to close this issue.
