### ISSUE TITLE
How to mark a template as a "project template"

### ISSUE THREAD

**Issue by SimonCropp** [dotnet/templating#866]
If i have an existing sln and project open in VS and i run the following in the package console

```
dotnet new xunit -o ClassLibrary1 
```
i get

```
[xUnit Test Project] is a project template. By default it's not created in a 
target location containing a project. Force creation with the -all flag.
```

So how do you mark a template as a "project template"

**Comment by mlorbetske** [comment]
In the "tags" section of your template.json, add type: "project" ([example](https://github.com/dotnet/templating/blob/rel/vs2017/3-Preview2/template_feed/Microsoft.DotNet.Common.ProjectTemplates.2.0/content/ClassLibrary-CSharp/.template.config/template.json#L14))

**Comment by SimonCropp** [comment]
where is the documentation for that?

**Comment by mlorbetske** [comment]
"tags" is a free form element in the schema, so technically anything goes (and that setting isn't guaranteed to be respected by all consuming systems). It is documented in the official schema (VS, VS4Mac & VS Code should all support referencing the schema for completion/documentation - otherwise, in looking at the source, it's at the very bottom http://json.schemastore.org/template)

**Comment by SimonCropp** [comment]
so shouldn't this be called out more explicitly in the doco so you dont get another person asking the same thing?

**Comment by mlorbetske** [comment]
Sounds good, let's call this out in #390
