### ISSUE TITLE
calculated parameters

### ISSUE THREAD

**Issue by lucamorelli** [dotnet/templating#905]
reading the https://blogs.msdn.microsoft.com/dotnet/2017/04/02/how-to-create-your-own-templates-for-dotnet-new/ I read this:

`The expression used in the condition here, (EnableContentPage), is very basic but, you can create more complex conditions using operators such as &&,||,!,<,>=,etc. For more info see https://aka.ms/dotnetnew-template-config. `

Looks like that I can create a complex condition inside the template, but since sometimes the expressions can be complicated and must replicated in more places in the template files, I would like to know if is possibile to move the definition and evalution of the expression outside the files itself in a single place.
I looked to the documentation and I don't understand if is possible: the more simple idea I have is to create some kind of parameter as a calculated field based on other paramters and conditions, and use this directly in the template files.

**Comment by sayedihashimi** [comment]
Hi @lucamorelli I'm not really following the scenario. Can you be more specific?

**Comment by lucamorelli** [comment]
if I need to add a condition like this
`if ( Framework == 'netcoreapp2.0' && Authentication == 'Azure AD' && dataBaseType != 'SqlServer)`

how can I express it in a more concise way ?

**Comment by sayedihashimi** [comment]
I'm not sure if this is what you are looking for so let me know if it's not.

If you need to use a condition in several places I believe that a `computed` symbol is what you need. For example see how `OrganizationalAuth` is defined in [here]( https://github.com/dotnet/templating/blob/rel/vs2017/3-Preview2/template_feed/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/StarterWeb-CSharp/.template.config/template.json#L240).

After creating that computed symbol you can use that in your `if` statements. So you can do

```
#if (OrganizationalAuth)
...
#endif
```
Example [here](https://github.com/dotnet/templating/blob/06ff66056de299fbf4c87d81e016ff650fe99c09/template_feed/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/StarterWeb-CSharp/Startup.cs#L53)

Instead of

```
#if (auth == \"SingleOrg\" || auth == \"MultiOrg\")
...
#endif
```

**Comment by lucamorelli** [comment]
thanks, looks like it's what I was looking for. Can you add a sample about this in the samples repo? I looked for something similar, but I haven't found anything similar neither in the sample repo nor in the main branch of this repo

**Comment by sayedihashimi** [comment]
I created https://github.com/dotnet/dotnet-template-samples/issues/19 to track creating a sample for this.
